### ISSUE TITLE
Problems with follow-the-leader AI in follow-the-leader mode

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1203]
**Author: devlabn**

STK 0.8.1
openSUSE 13.1

I can't explain the problem in my words, so I'm adding the issue description as some quotes from IRC, the time codes aren't links in Trac:
[<i5150pc> 
2 things: Why does it have power ups, and why is the AI leader kart a bit slow? 
[19:53](19:51]) <Arthur_Den> the leader uses the standard AI as far as I know so I don't know why it would be slower than otherwise
[<i5150pc> because some how the player kart outruns the leader AI kart
[19:55](19:54]) <Arthur_Den> yeah you need to stay behind the leader
[<Arthur_Den> often the leader gets hindered by the other AI which is too stupid to know it shouldn't do that
[19:58](19:56]) <i5150pc> and causes the player to be in problems when that happens
[<Arthur_Den> true
[19:58](19:58]) <i5150pc> that counts as a bug?
[<Arthur_Den> I'd think so yeah
[19:58](19:58]) <Auria> this could certainly be improved
[19:59] <Arthur_Den> current follow the leader AI is pretty oblivious of the whole mode so it doesn't do like it would if it were tailor-made for that mode 

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1147

**Comment by Alayan-stk-2** [comment]
Now : 
- The FTL leader has a special item list. No cake, rare bowling ball (to discourage being directly behind), many zippers and bubble shield. This gives it a boost.
- In the few years since the issue was created, FTL leaders were given a bonus distance at the start compared to other karts to help them stay ahead soon after the start.
- The FTL leader is set to use a boosted AI (nitro and items at the moment ; if other things are added to the boosted AI in the future it will get it automatically)
- The FTL leader is not affected by the rubber-banding rules : in low difficulties, it won't slow down if ahead of the player. This means that it will build up a lead rather easily compared to other AI karts, so staying behind the leader won't mean having all the other AI karts very close.

While enhancements are still possible, the mode should be much less frustrating now.
