### ISSUE TITLE
Avoid race condition on shut down

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#1529]
Stacktrace:
http://pastebin.com/CWMf4zt9

**Comment by hiker** [comment]
The new console should not be affected but this anymore. In case of a valid command it could cause a crash (i.e. if the command is entered just as stk is exiting), but since this is very unlikely and additionaly this is a debug console, which is not started by default (since b59194cdf3d1d5461e50f3d6e78be91359e5b3db) this is acceptable.
