### ISSUE TITLE
Weather effects are not visible when you look backwards

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1704]

**Comment by hiker** [comment]
Not a release blocker.

**Comment by qwertychouskie** [comment]
Just a stab in the dark, but maybe weather surfaces are one-sided, and thus cannot be seen from the other side?

**Comment by Elderme** [comment]
No, we cannot see  weather effects when looking backwards because they are generated with a box particle emitter placed in front of the kart. I think there is two way to fix the issue:
- move the particle emitter behind the kart when looking backward

or
- attach the emitter to the camera instead of the kart

**Comment by Benau** [comment]
My fix 1704 branch did move the particle emitter behind the kart when looking backwards which is done in local player controller, actually by changing the absolute transformation (rotation) of emitter, may be we can force it to emit particle at any axis (#788)
