### ISSUE TITLE
LoD is based off of kart's position instead of camera's

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1742]
Makes the new FPS camera slightly less useful, as it can't capture highly detailed models unless the kart is right beside it.

**Comment by Flakebi** [comment]
This behaviour is intentional ([here](https://github.com/supertuxkart/stk-code/blob/master/src/graphics/lod_node.cpp#L80) introduced by [this commit](https://github.com/supertuxkart/stk-code/commit/21683251a2fb8f68b0d7f54dc24677fd00633f97)).

I can't see where the camera is set now (beside of the end screen and kart movement obviously), so I hope this was removed :)
Any comments @auriamg, @vlj?

**Comment by auriamg** [comment]
This is intentional because of shadows, when rendering shadows the camera will move above the track but LOD should still be focused around the kart

Perhaps for the FPS camera the kart could actually be moved behind the camera? Sounds a bit silly I know, but stk generally assumes that the kart is where you are

**Comment by Flakebi** [comment]
How about adding the "real" position of the camera as an attribute which stays the same during the whole rendering process?

By the way, I wasn't able to find the code that changes the camera position for shadows (but I believe you, it's there), could you please tell me where it is?

**Comment by auriamg** [comment]
Yes, a "center" position (that is usually the position of the kart) would work.

As for shadows, I can't tell exactly since that's vlj's specialty, sorry
