### ISSUE TITLE
Breaking XML compatibility with old addons

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1784]
I think it's time to break the compatibility with the old XML format. Currently we are still backward compatible and a track made for supertuxkart 0.7 will open with 0.8.2.

While I'm generally not against breaking the backward compatibility I think it's the good time to do it now for several reasons.

* People will have to re upload their addons. Since we have broken the compatibility with the old addons website.

* The new exporting scripts are way easier to use compared to the previous one. Plus we have one to convert old tracks. It's very easy to take an old track and to port it. Just run the script and export it.

* We have a documentation available on our wiki explaining how to do that.
http://supertuxkart.sourceforge.net/Track_Maker%27s_Guide_2#Converting_an_old_track_to_the_new_engine

* We have a new engine that has a different philosophy of doing stuff compared to previous one

* This might confuse people into thinking they can use the old exporter to export old tracks. While this will work this isn't recommended and the result will look ugly/bad

--

To make the transition easier I recommend to add two links on the addons website about:
How to make your own addon ?
How to convert a previous addon ?
http://supertuxkart.sourceforge.net/Track_Maker's_Guide_2

The idea is to encourage and make it easy for people to try the new exporter and the new engine.
By reading the documentation they might be interested in improving the track and thus producing a far better result.

We might loose some old addons but I think at the end there will be a general improvement.
As an example I can upload Island track (before Gran Paradiso Island)

**Comment by hiker** [comment]
While I am not against increasing the version number stk supports (and of the exporter), it also means that people who have downloaded addons (i.e. our fans) can't use them anymore, and they can't even get them since they are not on the new addon server.

What about increasing the version number for the web page (i.e. only accept addons with the latest exporter), but leave the minimum supported version for stk the way it is, so that currently installed addons still work?

**Comment by auriamg** [comment]
Done
