### ISSUE TITLE
Remove 'version' numbers from karts and tracks

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1786]
Tracks and karts directories should not contain a 'version' number (or whatever the 20_ and 30_ is). The directory names are used as identifiers in the game. So changing the directory names because the model was changed/updated will make saved data invalid (e.g. user created GP, last track, last kart), and could even result in stk crashing (e.g. 'nolok', 'tux', 'overworld' are atm hardcoded in the game, so changing e.g. tux to 20_tux would break stk).

**Comment by samuncle** [comment]
Let me explain why I have done this

Back in time, one year ago I needed a simple way to make the difference between tracks that were next gen and those who weren't.
The prefix 20_ isn't the version number of the track. It means: they use a "new 2.0 philosophy" and are using the full "power" of the new engine. It could be ng_ for next gen or something else.

The road of the tracks might seems similar to the old version but each 20_ are in fact brand new track. They have also brand new names. Amazonian Journey != Cocoa Temple.
Special Tracks and karts like nolok & tux won't be changed with a 20_ prefix.

These prefix won't be changed unless the engine is completely different.
I have no problem with the idea of changing the challenges files etc according to the name of the track.
20_chocolate should be renamed 20_cocoaTemple and 20_island to 20_granParadisoIsland.

Since we have to change anyway the name, I will keep doing that. Please don't remove the 20_ prefix it's an easy and useful way for me to sort out stuff. For instance when I open blender it's very easy to see what tracks are next gen and what aren't next gen
![screenshot - 09 01 2015 - 16 38 16](https://cloud.githubusercontent.com/assets/6406045/5682192/809869f4-981e-11e4-844d-c99a8ed4e110.jpg)

I also wanted to use that in the documentation to write something like: All tracks with 20_ are next gen track you can take example about how it works.

1) If an old track has a minor update, it won't have a 20_ prefix
2) If a new track has a minor or even big update the prefix 20_ will remain
3) the prefix 30_ was an error and I will change it to 20_
4) If there is a big change in the engine, brand new tracks made for it will have a 30_ prefix but tracks with 20_ won't change to 30_
5) Since name of all 20_ tracks are different to the old version the name has to be changed anyway

Thanks for your understanding
Sam

**Comment by samuncle** [comment]
One more thing. If you want by all the means to remove the 20_ prefix, just add a new folder named nextgen-tracks so we can have a clear separation between old and new tracks.

That would solve the issue easily

**Comment by hiker** [comment]
There might be a misunderstanding: if you really want to use the 20_ prefix in the media repo, that's fine, since it does not affect any code or cross references (though tbh I still don't see a good reason for it ;)  ). But for the assets they should be removed:
1. It does not affect any use case you have, opening in blender and pointing new users will be done in the media repo only
2. Since the directory names are actually IDs, there are several risks and inconveniences involved in changing them: 
 1. The IDs can be used in various places: GP,  challenges, (perhaps in achievements?), hard-coded in stk (e.g. which tracks are intro, overworld, win or lose GP animations; which kart is the default kart on new start, which karts have special boss powers, ...). So renaming them is unnecessary work, and has the risk that we might miss some occurrences and introduce bugs in the game. Of course when we add/remove karts/tracks we need to check this. I am talking about minimising risk and unnecessary work. We had broken GPs in the past because of this renaming (and auria or I had to go and fix this later).
 2. It invalidates any saved history files (e.g. I have a selection of history files used to reproduce physics problems. If the karts are renamed I need to modify those history files or else they won't work anymore).
 3. It invalidates any saved user config (e.g. last used karts) - admittedly not a major issue :smirk:.
 4. It is very inconvenient for developers having to remember which kart/track has a 20_ prefix now. Using command line optons to directly start a track with a certain kart now requires us to remember which kart/track might have a 20_; same when looking at the xml files of a track or kart. I also often remove kart.xml files in order to start stk faster: rm */kart.xml; svn revert beastie/kart.xml tux/kart.xml  (or just removing the karts with way too many bones). It all means to inconvenience all (well, not sure if all - but some :wink: ) coders.

So, samuncle, feel free to use whatever way you want in the media repo (I admit I would prefer to have media and assets name identical, but a 20_ as prefix is easy enough to handle - besides we already have differences, e.g. olivermath vs mathclass) - prefix, new directory. Or of course a ticket with tracks to be replaced could be used (including the list of already improved assets), or nice wiki page documenting the tracks and karts (which could be used to point new users to, it could even describe what is special about a track, what new users might want to study).  I'll finish the renaming, in order to finish #1894 .

**Comment by hiker** [comment]
Karts renamed in r16105, tracks renamed in r16106. Changes to challenges etc in 8203d6b

**Comment by samuncle** [comment]
I am terribly disappointed to see this especially since you kept the wrong name 

Gran paradiso island is still called island. Basically hiker you took your time to do this wrong 

While you wanted so much to correct this for the "cleanliness " of the name they are misleading for people 

I'm disappointed and angry to be honest especially since auria said that keeping the prefix wasn't a big issue 

And nope I don't recall I agreed sorry for that.if I did I probably mentioned to use THE CORRECT NAME not for misleading the people with the wrong name 

[00:58] (hiker) Auria: while renaming the tracks, should I also update some clearly wrong names? E.g. star track for enterprise

:( :(
Also you didn't asked me if I had committed all my changes in the media repository which could lead to conflict 
It's not like a text file you can't merge two blends. It's either one version or another one.
I don't mess up with code file so please don't mess up with art file 

[00:59] (Auria) hiker: if you wish, though we must update them everywhere. As for myself, am I happy to have a "unique ID" that doesn't need to perfectly match the label, IMO the label needs not be the label

Sure so why not just renaming them with a random Id :p like gdg63453g. As you said you are programer not artist and even if you are programer I'm sure you wouldn't accept if cpp files where named in misleading name 

What am I supposed to do except saying I'm sad to see that and disappointed.

**Comment by samuncle** [comment]
Edit:

I just saw you renamed star track into stk enterprise. So why not doing the same with gran paradiso island ? And chocolate ?

Again total inconsistencies

**Comment by samuncle** [comment]
Edit 2:
There is no way for me to rename the track since there is nothing in the documentation about that process.
A checklist would have been helpful so please can you do it so we have a reference about how to handle renaming

**Comment by hiker** [comment]
First of all, you are quoting things incorrect in a very bad way: the last 'quote' you copied starting with 'hilker' gives the impression that I have said that. That's not true! Auria wrote that, and used 'hiker:' to ping me. You must have somehow cut out her name when quoting - but you are quoting her, not me!

1) I did not take my time fixing this. You told me that you would do it, since you suggested to use proper and consistent names (which we all agreed with) and you wanted to document it. Since we are very close to the RC, and I am aware that you are busy, I did at least the important bit of this ticket, leaving the rest for later when you would have finished the naming scheme. Since you quote IRC, you should have seen my reasons for not doing more: 
"01:18 < Auria> also you named it chocolate whereas the name of the track is cocoa temple ;)
...
01:18 < hiker> I know, I didn't want to change that, since it's .... his :P
"
I was really afraid about upsetting you, since you are so sensitive about me changing what you consider "your stuff" - not that I even expected you saying: "Thank you for helping me out when I don't have enough time to do what I told you I would do", but I actually tried to avoid upsetting you. To be honest, I am not sure what name you would have preferred for 30_chocolate: cocoa? cocoa_temple?

Sorry for upsetting you trying not to upset you :).

2) I did not want it for the cleanliness, I wanted it to avoid the inconvenience for developer (and perhaps reviewers who want to show or test a certain track that's otherwise locked) to have to remember if a track is this gen or next gen or some other number that makes no sense ;) You suggested to rename all tracks to have a clear naming scheme (which I toally agree with).

3) I did not touch anything in the media repo, as you have requested in the past. So even if you have not committed something, no problem, I did not break anything. I told you that you can use whatever naming scheme you want in the media repo,

4) Please check the ticket that I opened on your request:
"02:55 < hiker> samuncle_: I opened 1894 for the documentation"
Check the ticket: #1894 work done, documented and link added to the ticket, and ticket closed.

I take it that I now have permission to touch your tracks, so I'll rename them.

The fact that you agreed with renaming tracks and introducing a proper naming scheme was done in PM, I won't quote this here.

**Comment by hiker** [comment]
Renamed chocolate and island in r16110, updated stk-code in 5c4f1f7. Closing this ticket, a proper naming scheme for all tracks can be implemented later.
