### ISSUE TITLE
Pidgin hat is misplaced

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1803]
![scotland-2014 12 17_18 57 01](https://cloud.githubusercontent.com/assets/2053884/5476419/5b715dee-862a-11e4-91ec-b708e11f3439.png)
![scotland-2014 12 17_19 00 49](https://cloud.githubusercontent.com/assets/2053884/5476421/5bb1a46c-862a-11e4-8705-a912892c3878.png)
![scotland-2014 12 17_19 05 47](https://cloud.githubusercontent.com/assets/2053884/5476420/5b939206-862a-11e4-9cb5-0bbf22a6f74b.png)

**Comment by deveee** [comment]
Marked as 0.8.2 because it should be checked. Probably hat for pidgin, puffy and maybe other karts should be removed from xml file before release.

**Comment by GreenLunar** [comment]
> puffy and maybe other karts should be removed from xml file before release.

Do you mean that puffy and maybe other karts would no longer be available by default?

**Comment by deveee** [comment]
@GreenLunar 
```HAT for pidgin, puffy and maybe other karts```

Puffy with a christmas hat is rather not possible ;) We should disable it for this kart.

**Comment by deveee** [comment]
Ok, I fixed hat position for adiumy. Everything other looks fine. 

Hats for puffy and pidgin weren't displayed, but I removed these lines from xml files to be sure that they are not displayed somewhere under ground or in other strange place.

I leave this opened because we should check why hats don't work with pidgin.

**Comment by auriamg** [comment]
Fixed in SVN, the bone had the wrong name
