### ISSUE TITLE
Game crash after taking screenshot HD 4600 full screen

### ISSUE THREAD

**Issue by math07** [supertuxkart/stk-code#1818]
Hello,
When you take a screenshot in full screen mode(doesn't occurs when windowed), the game crash with HD 4600 latest driver. With my nvidia card, no problems. The crash occurs also in latest STK official release.
It enters : 
void IrrDriver::doScreenShot()
m_video_driver->createScreenShot(); (COpenGLDriver::createScreeshot)
and crashs in this function almost at the end by doing glReadPixels(0,0,ScreeSize.Width, ScreenSize.Height, fmt,type,pixels)

I debuged it and tried to fix it but wasn't able yet

**Comment by vlj** [comment]
I didnt write the code to store the screenshot. But if it works I think it's a fine fix.

GL_FRONT is the buffer "returned" by the app to the OS and that will be presented on screen.
The GL_BACK buffer is the buffer used to draw things. Each frame the front and back buffer are being swapped (that's double buffering) so that the user doesn't see "frame in progress".
I don't know where the glread is taking place but if it's used before the backbuffer is cleared or after it is written to but not swapped, then it contains correct content (of course there might be a frame latency but it's unfortunatly unavoidable)

**Comment by vlj** [comment]
Is the bug fixed ?

**Comment by math07** [comment]
Yes! thanks for your feedback.
