### ISSUE TITLE
[Linux] Window is not accessible if the saved position is out of range

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#1861]
When I first run STK while having attached a second screen and then launch it again without the second screen, I can't see the window anymore because the saved x-coordinate of the window is too high. For me this isn't a problem because I can simply edit the config.xml, but no one who is only playing STK wants to do that.

A possible solution would be to check if the saved positions are lower than the screen size.

**Comment by konstin** [comment]
I don't see why this shouldn't be done in irr_driver. But in my driver settings there is an option where you can select having the screen as a seperate display in X. My knowledge about all those X functions is very limited so I can't help with that. But I also remeber that there is a command to launch a second X screen in paralell (reachable with ctrl+alt+F8), but I can't remember it. Anyway, there should be a function to get the currently active display.

**Comment by auriamg** [comment]
Regarding 2, yes move window will work when there are multiple screens, that's actually why this was implemented in the first place, to make STK remember on which screen it should open

**Comment by deveee** [comment]
Auria, yes, but even if I have two physical screens, these functions report that I have one big screen 3286x1080.

When you start second X (ctrl+alt+F8), you open second display, not screen.

And this code ideally should be in irrlicht because it is operating system specific. Auria even created a patch which is already in upstream irrlicht. And it simply creates window in specified place.

**Comment by deveee** [comment]
Fixed in bab97833b7315753856caa18427c3484bf1748f8
