### ISSUE TITLE
Update info.plist with minimum OSX version

### ISSUE THREAD

**Issue by davidak** [supertuxkart/stk-code#1863]
Version 0.8.1 works fine

if you can't fix this problem for this old OS Version, add a dependency on a newer one

```
Process:         launchd [28390]
Path:            /Applications/SuperTuxKart-0.8.2-beta.app/Contents/MacOS/SuperTuxKart
Identifier:      net.sourceforge.supertuxkart
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  launchd [235]

Date/Time:       2014-12-31 20:13:26.397 +0100
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          96102 sec
Crashes Since Last Report:           4
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      7C4F96F2-E52A-4BEB-B70E-58F1A76B44BD

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x000000008fe01030
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x00000000  ebx: 0x00000000  ecx: 0x00000000  edx: 0x00000000
  edi: 0x00000000  esi: 0x00000000  ebp: 0x00000000  esp: 0x00000000
   ss: 0x0000001f  efl: 0x00010202  eip: 0x8fe01030   cs: 0x00000017
   ds: 0x0000001f   es: 0x0000001f   fs: 0x00000000   gs: 0x00000000
  cr2: 0x8fe01030

Binary images description not available


Model: iMac11,3, BootROM IM112.0057.B00, 4 processors, Intel Core i7, 2.93 GHz, 16 GB, SMC 1.59f2
Graphics: ATI Radeon HD 5750, ATI Radeon HD 5750, PCIe, 1024 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 2.1.14.6
Bluetooth: Version 2.4.5f3, 2 service, 12 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: WDC WD1001FALS-40Y6A0, 931,51 GB
Serial ATA Device: HL-DT-STDVDRW  GA32N
USB Device: Hub, 0x0424  (SMSC), 0x2514, 0xfd100000 / 2
USB Device: Keyboard Hub, 0x05ac  (Apple Inc.), 0x1006, 0xfd140000 / 5
USB Device: Apple Keyboard, 0x05ac  (Apple Inc.), 0x0221, 0xfd142000 / 6
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0xfd120000 / 4
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8502, 0xfd110000 / 3
USB Device: Hub, 0x0424  (SMSC), 0x2514, 0xfa100000 / 2
USB Device: Hub, 0x050d  (Belkin Corporation), 0x0237, 0xfa140000 / 5
USB Device: USB-PS/2 Optical Mouse, 0x046d  (Logitech Inc.), 0xc050, 0xfa130000 / 6
USB Device: Internal Memory Card Reader, 0x05ac  (Apple Inc.), 0x8403, 0xfa120000 / 4
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 3
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8215, 0xfa111000 / 7
FireWire Device: Rev2, Drobo, Up to 800 Mb/sec
```

**Comment by auriamg** [comment]
Hi, the beta is advertised as working on OSX 10.9 and 10.10 (simply because I no longer have access to older versions of OSX and Apple does not provide the tools to build for older versions), so unless someone with an older version of OSX can provide a binary there is likely little to do.

You say "add a dependency on a newer one" which indeed would be ideal, but to be honest I have no idea how to do that. A google search yielded only outdated information and dead links. If someone knows how, please tell me ( the only thing I found is http://www.bignerdranch.com/blog/requiring-a-minimum-version-of-os-x-for-your-application/ but apparently that no longer works since 10.4 )

**Comment by davidak** [comment]
i looked into a package that doesn't start and found the Key mentioned in that blog post, so it still works.

```
	<key>LSMinimumSystemVersion</key>
	<string>10.7</string>
```

![bildschirmfoto 2015-01-02 um 01 44 08](https://cloud.githubusercontent.com/assets/91113/5593681/905a711e-9221-11e4-9269-81cba8dcc63b.png)

the also do it this way: https://github.com/atom/atom/issues/1598

until someone have provided a binary there should be a hint on the download page, when 0.8.2 is released.

maybe i will look at it but i have limited time and lot's of things i want to do.

http://supertuxkart.sourceforge.net/Building_and_packaging_on_OSX

was it easy on 10.6 to build? only following some simple steps?

**Comment by auriamg** [comment]
Okay thanks, will look to add the key to info.plist

Now unfortunately 10.6 is probably out of the picture, because STK uses C++ 2011 and I think 10.8 is the first OS where Apple provides a compiler recent enough. So maybe if building from 10.8 one could enable 10.7 compatibility, but 10.6 I doubt it
