### ISSUE TITLE
Some friends in profile are always online

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1868]
Hiker, I don't know if you are thaaat frequently online or if there is a bug somewhere. But you and aaditya are always online on my friends list. It doesn't matter on which day or hour.

**Comment by hiker** [comment]
At least in my case that is because often I would abort stk (or it would crash ;) ), without the logout code being run. I've opened https://github.com/supertuxkart/stkaddons/issues/42 to improve the server. For now I'll leave this ticket open since I seem to remember that I noticed at least once or twice that the logout code appear not to be working, e.g. the waiting time might be too short, resulting in cancelling the thread too early.

**Comment by hiker** [comment]
Leyyin spotted the problem and fixed it in:
f18167d345bfe920569ba673faf7709dc80a6ba8

He also added an hourly cron job that logs people out if they have not sent a ping for 5 minutes.
