### ISSUE TITLE
SegFault with LANG=C

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1905]
Running bbf8a6c on Ubuntu 14.04 x86_64, setting
```
export LANG=C
```
causes a SegF during initialization:
```
[debug  ] translation: Env var LANGUAGE = 'C'.
[debug  ] translation: Language ''.
src/tinygettext/dictionary_manager.cpp:106: tinygettext::Dictionary& tinygettext::DictionaryManager::get_dictionary(const tinygettext::Language&): Assertion `language' failed.
Aborted (core dumped)
```

**Comment by math07** [comment]
Which langage is that : lang=c ?

**Comment by math07** [comment]
I don't know how the config.xml file managed to get in a state like that ? 


    <language value="C" />

What were you doing before it occured ?

On a positive note, if this behavior happens with a release package, the assert isn't done and STK doesn't crash because it is intelligent enough to fall back on english language, And the user would have to choose back in language in the setting.
