### ISSUE TITLE
High-def textures in Island causes crash in stk

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1908]
When I started stk without user config (i.e. I get all defaults), stk crashes with "bad allocation" when I load Island track. Reason appears to be high-def textures which are now enabled. Platform: windows, hd3000.

**Comment by vlj** [comment]
Unfortunatly there's nothing I can do. The crash very likely happens because the textures use too much memory. In theory OpenGL driver should use memory swapping when we exhaust vram (or directly read from main memory) and not crash.

Unfortunatly OpenGL doesn't have a way to know how much memory we have. There are extensions for ATI (which just gives hints, not real number) and NV, I'm not even sure there is one for Intel. And even if there was I have no idea how much texture are used in maps before loading them.

**Comment by hiker** [comment]
Fixed in e17add7bc8f628339cc6ab97268e8917277c7386
