### ISSUE TITLE
Potentially unfortunate phrasing on airline poster in Gran Paradiso

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1927]
![stkflag_oceanicairlinesad_a](https://cloud.githubusercontent.com/assets/8258259/5890169/a88bc910-a403-11e4-88e4-1ef01661b374.png)

Not sure if intentional, but pretty dark if so.

**Comment by samuncle** [comment]
Some precisions here

1) Oceanic Airlines isn't a real airline company (and it won't become a real one anywhere soon).
2) It's not a real one because it's used in many TV shows, video games, drama, etc (most notably lost) as THE airline that will have a problem (hijacking, crashes, fire etc).

Their slogan "Explore the ocean with us" isn't a reference to a real life event (in fact the post was created way before them. It's a reference to the TV series lost and other stuff 
https://en.wikipedia.org/wiki/Oceanic_Airlines

The slogan is a bit "dark comedy" but again it's not intended to hurt anyone nor to make a reference to the real life
(I know personally someone who lost a family member in a plane crash)

**Comment by stkAnon** [comment]
Oh, okay. Just thought I'd point it out on the off chance that it was accidental.
