### ISSUE TITLE
Icons installed in the wrong path on Linux

### ISSUE THREAD

**Issue by akien-mga** [supertuxkart/stk-code#1942]
Testing 0.8.2-beta2, I noticed two things with the icons:
- Two icons are installed in ```$prefix/share/icons/hicolor/*/supertuxkart.png```. The logic is good, but actually they should be in the "apps" subdirectory, i.e. ```$prefix/share/icons/hicolor/*/apps/supertuxkart.png```
- The icons installed in ```$prefix/share/pixmaps``` are duplicates of the ones in the hicolor theme, and are probably not needed (at least they are not needed on recent systems).

**Comment by akien-mga** [comment]
The "apps/" string should be added here:
https://github.com/supertuxkart/stk-code/blob/master/CMakeLists.txt#L436-L437

For the pixmaps icons, it's your call.

**Comment by deveee** [comment]
Thanks for notice it. I will correct it soon.

I'm also not 100% sure if icons and supertuxkart.desktop file should be
installed in $PREFIX/share/(...) or just in absolute path /usr/share... If
you will install game for example in /opt directory, you won't get shortcut
in menu because it will be installed in
/opt/supertuxkart/share/applications/supertuxkart.desktop.

About /usr/share/pixmaps directory, I often see that icons are duplicated
in these two places. I think it's not that bad and user can easily find
they if he need.

**Comment by deveee** [comment]
Fixed in this commit: 2c8639f105e0381875b5c3ec70fd385a0abd4f4a.

Note that if you just use ```make install``` instead of creating .deb file, you need to use also ```gtk-update-icon-cache /usr/share/icons/hicolor/``` to make .desktop file working.
