### ISSUE TITLE
Multiplayer over LAN

### ISSUE THREAD

**Issue by amritkrs** [supertuxkart/stk-code#1966]
Any one working on making it multiplayer over LAN, because that will make it one of the most popular game.

**Comment by pb-programmer** [comment]
So I installed the new 0.8.2-beta2 build via precompiled windows binaries. (beta1 has been uninstalled while attempting to install beta2). Since it kept my previous graphics settings I can't tell wether "first startup" works fine now or not, but setting the gfx-level manualy caused the same error as with beta1

Graphical Effects Level 1 (vanilla startup, no previous GEL > 3 used):
![olivermath1-gfx1_01](https://cloud.githubusercontent.com/assets/9591354/6081320/f3b3b0f0-ae18-11e4-9f2c-756a5b2e0e1c.png)
![olivermath1-gfx1_02](https://cloud.githubusercontent.com/assets/9591354/6081324/fa3fa3ac-ae18-11e4-8e60-e136bcbd3861.png)

Graphical Effects Level 2:
![olivermath1-gfx2_01](https://cloud.githubusercontent.com/assets/9591354/6081349/1ebea7d2-ae19-11e4-8dd9-dc155e9e6253.png)
![olivermath1-gfx2_02](https://cloud.githubusercontent.com/assets/9591354/6081350/20b719ca-ae19-11e4-9c48-c9579668bdaa.png)
![olivermath1-gfx2_03](https://cloud.githubusercontent.com/assets/9591354/6081351/21ea042e-ae19-11e4-89f3-c7ac329f21da.png)

Graphical Effects Level 3:
![olivermath1-gfx3_01](https://cloud.githubusercontent.com/assets/9591354/6081360/28e2b636-ae19-11e4-9abf-1480be1c0fde.png)
![olivermath1-gfx3_02](https://cloud.githubusercontent.com/assets/9591354/6081361/28f9d4b0-ae19-11e4-80ba-0837a279edba.png)

Graphical Effects Level 4:
![olivermath1-gfx4_01](https://cloud.githubusercontent.com/assets/9591354/6081367/2f8f28fc-ae19-11e4-9c64-038f42a51c24.png)
![olivermath1-gfx4_02](https://cloud.githubusercontent.com/assets/9591354/6081366/2f8f19de-ae19-11e4-9b97-f946def089cc.png)

Graphical Effects Level 5:
![olivermath1-gfx5_01](https://cloud.githubusercontent.com/assets/9591354/6081371/324dc3c8-ae19-11e4-9e51-de8eeee31035.png)
![olivermath1-gfx5_02](https://cloud.githubusercontent.com/assets/9591354/6081370/324a0ba2-ae19-11e4-98bc-9a19128d749a.png)

Graphical Effects Level 1 (after GEL 5 was used since last program start):
![olivermath1-gfx1pre5_01](https://cloud.githubusercontent.com/assets/9591354/6081396/619045ca-ae19-11e4-924f-7d78de3b89d2.png)
![olivermath1-gfx1pre5_02](https://cloud.githubusercontent.com/assets/9591354/6081397/61910f64-ae19-11e4-951c-f5d6e170d10d.png)
![olivermath1-gfx1pre5_03](https://cloud.githubusercontent.com/assets/9591354/6081398/619155c8-ae19-11e4-91e3-7d31394a8662.png)

Resolution was 1600x900 px (native screen resolution) in fullscreen mode
My system specs haven't chanced since last post, but a bit more detail:
Intel HD Graphics 4000  from Lenovo subvendor
GPU @650MHz (650MHz idle stk-menue, ~950MHz while in a race) GPU-Clock, 800MHz Memory-Clock (4 ROPs, 8 TMUs, 16 Unified Shaders)
DX 11 with SM5.0 is supported as well as OpenCL and DirectCompute 5.0
"Graphic-BIOS" (as told by CPU-Z): 2161_RYan PC 14.34 (dated 12/07/2012)
Driver Version: igdumdim64 9.18.10.3359 / Win7 64 (most recent as told by "Lenovo support center")

CPU:           Intel Core i7 3520M @ 2,9GHz
RAM:          8GB DDR3 @ 800 MHz
Mainboard: Lenovo 2353CTO (Intel QM77 southbridge)
BIOS:          G7ETA1WW (2.61)  (dated 09/01/2014)

**Comment by hiker** [comment]
Hi,


> Any one working on making it multiplayer over LAN, because that will
> make it one of the most popular game.
I am not sure that LAN networking will, WAN more likely ;)

But otherwise we have a nearly finished LAN-only implementation from
GSoC, which just needs to get some better support (and testing, it was a
student work, but I haven't had time to go over it yet). I will be
working on networking after the next release.

Cheers,
   Joerg

**Comment by amritkrs** [comment]
Thanks Joerg, waiting for it to become a networked game.

**Comment by hiker** [comment]
*grin* I did not mean that you should not do it, just to be aware of what is already there, and to discuss your work with us. For example:
- LAN-server detection is completely missing and would be a great addition
- not using the online server for starting a LAN game (well, kind of related to the previous point).

**Comment by mirandadam** [comment]
Hello, @hiker, what is the current status on this? Is there a pull request or a fork of that multiplayer code somewhere that I could review and/or contribute to?

 I understand this issue is already closed, but I see no other open issue concerning the review of said GSOC project (or networked multiplayer, for that matter). I did a quick online search and could not find the contributed code either. I apologize if I missed something obvious.

Me and my kids love this game, thanks for the great work.

Best,
--Daniel

**Comment by qwertychouskie** [comment]
The basic support for networked multiplayer is already in the game, though it is hidden in the 0.9.2 release, so you will have to use the Git version.  Also, [the rewind branch](https://github.com/supertuxkart/stk-code/tree/rewind) contains some more work.

**Comment by fin-atem** [comment]
any updates on lan support? i downloaded the latest version for macos (0.9.3) and noticed the only multiplayer option is another player on the same computer, and i think wan support.

**Comment by qwertychouskie** [comment]
The current release doesn't have support yet, but the next release probably will.  Time Trial mode currently works pretty well, though normal races still have some bigger issues.  Most of the work is in `master`, but a bit is in `curved`.
