### ISSUE TITLE
Create User 'Existing Online Account', is confusing with 3 fields.

### ISSUE THREAD

**Issue by leyyin** [supertuxkart/stk-code#1977]
![supertuxkart_028](https://cloud.githubusercontent.com/assets/1269608/6156284/780b0994-b241-11e4-9a22-212de744d2d2.png)

The field 'Name' is kind of confusing. There should be only 2 fields there.

Also as a side note, the API now exposes the real name of the user and register API will also accept a new field with the real name.

**Comment by hiker** [comment]
TBH, not sure what to do. The online user name will be filled with the name, so there is no need to type the name twice. But because of duplicated online name we have to give the user the option to enter a different local and online name (e.g. even if 'joerg' as online name is taken, I would still prefer to have 'joerg' shown when I play).
I am not too sure about using real names tbh - could this have security implications (e.g. storing real names of minors?) 
Also, an online name might be shared among different local users (e.g. if you want to play story mode again from scratch, you can create a new local user, but still use your existing online account to stay in touch with friends).
Any suggestion how you would want to improve this? Always use the online name as local name?

**Comment by auriamg** [comment]
I suggest placing "Online username" first, since that's what people expect to fill first, and maybe place the local name at the bottom, separated from the rest (people usually expect the username+password pair, so making it visually distinct makes it clearer it's something else). Perhaps rename it too, something like "Local alias" ?

Mockup :
![stk_tmp](https://cloud.githubusercontent.com/assets/4296971/6158823/6a234852-b21c-11e4-86c9-a239a19f10c7.jpg)


Of course the local alias field would continue being pre-populatedf from what you type in the first textbox

**Comment by leyyin** [comment]
@hiker So from what you described, the "Name" field (should be renamed) acts more like a alias. 
What @auriamg  suggested above in the mockup, I think it's very good :smiley: .

**Comment by hiker** [comment]
No, name is the local name - for example it could be 'hiker'. The online name might be hiker050403 ... since hiker was already taken by someone. I find the description 'local alias' more confusing - what is that supposed to be - an abbreviation? How does it work with two local accounts sharing the same online account?
And main issue: the three screens are identical, that's only one object. So, making one screen different is some work (esp. so short before a release).
We could rename 'Name' to 'Local name' (though I seem to remember that I had this originally, and auria found that too technical).
Should we perhaps just change the title of the tab? New account with existing online user?
The 'new account' tab - does it have the same problem (sorry, I am too 'close' to be able to judge that)?
Or of course we just skip the whole local/online name connection thing, and have either local only account (that can never go online,or perhaps only with an automatic rename), or online accounts (and people have to accept the name hiker050403 ;) ). But tbh, I don't want to do this change before the release, it would be a lot more work.

One other consideration: I would expect that only a very minority will ever use this option - existing accounts will pick up the local name already, no need to create a new one; new player will mostly use offline or online only, only a few local accounts would actually use an existing user name

**Comment by hiker** [comment]
One idea: should we perhaps rename 'name' to 'profile'? Or "name on this computer"?

Otherwise I admit I can't see what's confusing there, but of course I implemented it :P

**Comment by leyyin** [comment]
I did not find the 'new account tab' to be confusing because I expected the Name to be something like the real name, but on 'existing online account tab' I was confused about the "Name".
The easiest solution would be to just rename the "Name" field to "Local Name" or "Name on this computer".
