### ISSUE TITLE
Update the pot file

### ISSUE THREAD

**Issue by SafaAlfulaij** [supertuxkart/stk-code#1991]
Hello.
Just a suggestion, Why not making a cron job to update the pot file and the translations (from Transifex) everyday?
I'm suggesting this as the string "You have %d new friend requests!" is plural in the source code but singular in the pot and po files. Also You don't need that if statement if it's a plural string ;)

**Comment by hiker** [comment]
We are (I hope) shortly before declaring the string freeze for the next release. In the past we have always updated the pot file manually, mainly at times when we are getting closer to a release - mostly to avoid translators translating strings that might change again later.
I'll see what others have to say about this.

**Comment by Alayan-stk-2** [comment]
The practice of updating manually the pot file has continued ever since this issue was opened.

This reason still stands :  
> to avoid translators translating strings that might change again later

With the more massive changes for the next release, the pot file has been updated manually several times, and it has actually been slightly annoying for translators because some new strings have been revised and needed to be translated again. If it had been updated automatically every day, many more such changes would have happened.

Therefore, this feature is not desirable considering STK's current development process.
