### ISSUE TITLE
Build Failure on latest commits

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#1993]
I don't know why, but the latest git commits fail to build on my machine. 

build log: http://pastebin.com/n2MdtHRL 

the build fails with these errors:

/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: lib/irrlicht/libstkirrlicht.a(CIrrDeviceLinux.cpp.o): undefined reference to symbol 'XConvertSelection'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: note: 'XConvertSelection' is defined in DSO /usr/lib64/libX11.so.6 so try adding it to the linker command line
/usr/lib64/libX11.so.6: could not read symbols: Invalid operation

**Comment by deveee** [comment]
It's rather strange because this function is there for a long time. And 
it works for other people.

Which version of cmake do you use? Did you update it recently or so?

My cmake version does more checks, for example:

-- Looking for XOpenDisplay in 
/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in 
/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so 
- found

I don't see it in your logs.

Or maybe you used some specific cmake options?

**Comment by cap44** [comment]
i use cmake 3.2.0 
I updated it, but until yesterday it worked

**Comment by deveee** [comment]
I fixed problem with x11 library in current git. Now it works for me with cmake 3.2.0-rc1.

Though I'm not sure what about your second error... I can't reproduce it.

**Comment by hiker** [comment]
This is not a release blocker at this stage, since all builders can actually build it.

**Comment by deveee** [comment]
Is this still not working for you? Or was it something wrong in your system? I'm asking about libGL.so problem.

**Comment by cap44** [comment]
@deveee no. turns out that the GPU driver broke

**Comment by deveee** [comment]
Ok, so ticket can be closed.
