### ISSUE TITLE
second gamepad controller has little control on single player

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2013]
beta 0.8.2
I tried a solo party with two controllers plugged. The first controller works fine, the second one should not have any effect on my kart, however i could 
   - see backwards
   - "move" the kart. each time i pressed the button to go forward the kart moved a little forward and stopped.

**Comment by auriamg** [comment]
Is the second controller correctly configured? Also playing single player with 2 gamepads is certainly asking for trouble, in single player it's strongly recommended to use a single gamepad

**Comment by hiker** [comment]
I seem to remember that we added some support for this for players who do not use the gamepad to select the kart, so in case of single player we might accept events from a 'non-connected' controller. Since it causes more confusion not to be able to use a controller, then getting events from a 2nd controller, that's a won't fix.
