### ISSUE TITLE
creepy girls on "gran paradiso island"

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2014]
beta 0.8.2
- There is no colision with the girls playing volley ball on gran paradiso island
- Sara Princesses have no eyes

**Comment by samuncle** [comment]
Hi thanks for your report.

For Sara's eyes I have included them in the trunk so in the upcoming release it should be okay.

I will enable physic for library objects. I wasn't sure yet how to do that. Should I just enable physic and set the shape to real ? or create an invisible object for colision only to reduce the amount of poly in the physic engine.

Also for trees I feel the only thing that needs to collide is the trunk, since it would become quickly annoying if for a little leave you are stopped.

**Comment by hiker** [comment]
Hard to say which would be work better/faster - an approximate shape (cylinder), or an exact shape. 
I'd say to just get an approximate shape, but feel free to try both of course.

**Comment by hiker** [comment]
Postponed.

**Comment by samuncle** [comment]
I have added a physical limit so you can't pass trought objects like people cheering or trees.

However there is an issue, even if the object that define the limit is "physic" only, is displayed in supertuxkart. 

Maybe the node management system doesn't recognize the flag "physic only"

**Comment by samuncle** [comment]
It's now corrected but there is other objects that should be changed. Se #2061 for more information
