### ISSUE TITLE
Easter egg mode is broken in Hacienda track

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2024]
Now we have invisible wall in hacienda track and it's not possible to collect all eggs. We should move these eggs or remove invisible wall in this place.

**Comment by auriamg** [comment]
Hi, could you perhaps detail where this happens? Looking in blender, it doesn't really seem to me the walls have moved

**Comment by deveee** [comment]
![zrzut ekranu z 2015-03-08 08 36 41](https://cloud.githubusercontent.com/assets/5108558/6545023/49f77d9a-c56e-11e4-9537-3629206941ab.png)

I think that this place is quite good for easter eggs. Is this invisible wall really needed there?

**Comment by samuncle** [comment]
okay it should be done. I just removed the invisible wall + improved the section.

Please take in mind if you add eggs since it's an official game mode, the sections where they are should be fully working section without bugs or missing part. In many cases stuff near the track aren't fully made since there is no point of visiting these part.

If you want to put an egg there just make sure it's a visitable part and not like in this case with missing faces and walls.
