### ISSUE TITLE
Adding CLI options to toggle shadows/lights/etc

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2092]
We should have a way to change the default configuration by CLI option (maybe an option to load an alternate file, or something similar) it will become easier to do benchmarks with STK.

http://www.phoronix.com/forums/showthread.php?117175-Running-Benchmarks-On-The-Newest-Open-Source-OpenGL-3-1-Game&p=484950#post484950

**Comment by hiker** [comment]
Not sure what exactly you mean - you mean command line option to specify graphical options? Or a different user config file?

Anyway, I am unassigning me, that's a simple task can be done by anyone.

**Comment by hiker** [comment]
Since I noticed the discussion about this on IRC: the idea of this ticket is to add command line options, which would make it easier to benchmark different configurations. For example, you could do:
````
./bld/bin/supertuxkart --enable-glow --enable-bloom ... (profiling option for an automatic run)
./bld/bin/supertuxkart --disable-glow --enable-bloom ... (profiling option for an automatic run)
./bld/bin/supertuxkart --enable-glow --disable-bloom ... (profiling option for an automatic run)
./bld/bin/supertuxkart --disable-glow --disable-bloom ... (profiling option for an automatic run)
```
Naming of the options is of course up to you. This would be much simpler for people who want to automatically benchmark stk (compared with providing different config files).

Note that setting these options would most likely make them permanent in the user's config.xml file (since the user config is written back at exit - though of course that could be disabled in case of command line changes)
