### ISSUE TITLE
Nessie's Pond is unbalanced

### ISSUE THREAD

**Issue by alketii** [supertuxkart/stk-code#2105]
I have won all levels in Story Mode with Intermediate but not Nessie's Pond, it is un-winnable with Novice and Intermediate modes, time runs out no matter what, but I won it as Expert mode.

**Comment by auriamg** [comment]
Fixed in 1cc3a0f0b83b88fc11d0c1383cacd2882cac1d39

**Comment by samuncle** [comment]
This is uber major isn't it ?
Since are distributing a game that isn't possible to finish :|

**Comment by samuncle** [comment]
I would agree to do a quick hotfix since it makes the game impossible to finish in easy and it's only a xml file to update. OF course we could wait until 0.9.1 but we don't know how much time it will take to do 0.9.1.

IMHO it's rather quick to change so why not doing it

**Comment by hiker** [comment]
Afaik the track and the easy/medium times have not been changed since  06/10/2012 (r11668 on svn) - so those values have been used since 0.8. So I don't think there's any need to release a quick hotfix now. We could create a web page with the fix description (i.e. how to fix it for the three supported platforms, and/or link to the new file), and tweet about this (and post, ..), add a news entry perhaps :)

**Comment by Wuzzy2** [comment]
This is beatable for me, with lots of skidding and nitro. :)
In 0.9:
I won on Intermediate in 02:39:40. First try.
I won on Novice in 03:27:70. Also first try.
I also won on Expert, but I don't know the time anymore. But Expert was not the apparent problem, anyways.

Disclaimer: I am not a STK novice, so my times may NOT be the best reference. ;)

As a general note: I think you should not blindly trust player reports who claim that something is “unbeatable” or blindly tweak time limits. Please, please also quickly test for yourselves.

**Comment by alketii** [comment]
Well I don't know about you, but other tracks/levels i won pretty easy, most on first try, this was way to problematic, i tried more than 20 times.

**Comment by deveee** [comment]
I don't think it's thaaat unbalanced. At least not enough to release hotfix just because of this one issue.

I played it few times:

beginner (required 3:45)
- with powerups: 3:06
- without powerups: 4:12

expert (required 2:45)
- with powerups 2:32

It is "unbeatable" when you don't use any powerups. But you should win it without problems when you sometimes use nitro/skidding/zipper/plunger.

**Comment by auriamg** [comment]
deveee: thanks for testing. It's not unbeatable, though the bug is that on easy, the game should be very easy - as long as you don't fall off the road more than a couple times you should win. But indeed this probably does not require a quickfix

**Comment by ianclever** [comment]
in intermediate and expert is quite possible, the only way that still could not win was in easy even with nitro and skidding. The closest I could get was missing

**Comment by auriamg** [comment]
Closing since the challenge has been tweaked
