### ISSUE TITLE
Race start sound repeat bug

### ISSUE THREAD

**Issue by coreybruce** [supertuxkart/stk-code#2153]
When you start up a race the sound of it starting before the actual race keeps repeating non stop for the whole entire race and is really annoying.

**Comment by Wuzzy2** [comment]
I can confirm this and I can provide more information about this.

This bug happens if you continue a saved grand prix. It seems only to happen after you have done so, I have never experienced the bug in other situations.

Also, this bug seems to continue for all future GP races (even non-GP) in the same STK session as well. If you restart STK, the sound weirdness is gone, until you continue a GP again.

The sound in question sounds like the “last lap” sound, but sometimes it is strangely distorted.

STK version: 0.9

**Comment by gameslayer** [comment]
Try starting a race in single player, it will always do the bug on any track on Super TuxKart 0.9.

**Comment by Wuzzy2** [comment]
Sorry, not for me. I can only confirm this under the conditions I posted previously.

Could you please describe how you experience this bug?
I.e. what exactly did you do after you started STK?
When does the sound play?
What does the sound sound like?
Does my bug report somehow match your bug? Maybe we both are talking about 2 different bugs?! :D

**Comment by gameslayer** [comment]
Everytime you start a race it will play the race startup noise than will repeat it nonstop and no it doesn't help it will only stop if you quit the race back to the menu.

What is the bug you are experiencing?

**Comment by Wuzzy2** [comment]
> What is the bug you are experiencing?
See my posts.
It seems our bugs are not quite the same. I never experienced your bug, the startup sounds only plays once, so it works for me. :-/
I'll open a new issue for “my” bug.

**Comment by gameslayer** [comment]
I will have to re download and see if this bug still occurs

**Comment by hiker** [comment]
If you could test current git, that would be great - we've done some significant work on audio - though I have the feeling that there might be a problem with your sound card, or driver or so (no one else has reported this kind of problem, apparently there is a similar repeated-sound issue, but it's not at all reproducible, while your problem appears to be). Otherwise wait for the next release .

**Comment by qwertychouskie** [comment]
@gameslayer Is this still an issue with 0.9.2-rc1?

**Comment by gameslayer** [comment]
I will have to try I haven't played it for a long time

**Comment by Alayan-stk-2** [comment]
It's at least still an issue on 0.9.1.3 (linux mint repo version). I'm not sure about the triggers - I know it's important for a bugfix - but there is indeed an issue (it doesn't happen consistently to me)

**Comment by deveee** [comment]
Is this the same as #2169? Are you able to reproduce it under valgrind? This is certainly an issue in 0.9.2, though it never occured for me in git version.

**Comment by deveee** [comment]
See https://github.com/supertuxkart/stk-code/issues/2169
