### ISSUE TITLE
My rank jumps around from 1st to 3rd on Northern resort

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2176]
When I play the Northern Resort and am in the lead, my rank sometimes and seemlingy randomly changes from 1st to 2nd or 3rd and then back to 1st again. I am sure I was not overtaken because I was >10 seconds in the lead. Does anyone else in here have noticed something like this?

I am absolutely not sure, but maybe this has something to do with the many bridges and tunnels.

STK version: 0.9

**Comment by hiker** [comment]
This might just be caused by driving slightly off road, and then STK finding an unexpected 'closest' quad it assumes the kart to be on. Could you provide details where this happens? Either a short video, or screenshot before (i.e. you as #1), and when you start to be #2/3.

**Comment by hiker** [comment]
I just realised that it could also be (esp. in N.R.) the AI falling into a hole ... i.e. being off track, but flying close to a different part of the track. When it gets close enough, it would be considered ahead of you, but the moment it is rescued it will be behind you again.
It's hard to prevent this, e.g. if you take an 'unexpected shortcut' somehow (cutting corners in math class or farm), STK does just exactly the same thing in the case of N.R., but it leads to incorrect results.
I see two options to improve this: either put in an invisible cylinder in the 'hole' of N.R. (which avoids that the karts will cross the center of the whole and getting closer to the other end) - but I am not sure if this will even work in all circumstances (if the kart would fly from say '6 o'clock' to 12 o'clock it would hit the cylinder, and the issue would be prevented. But if it flies from 6 o'clok to 9 o'clock, it might miss the the cylinder).
Other option would be to include an invisible rescue plane (or even use the existing texture that should have the rescue property set). Then if the kart is on top of a rescue property, do not try to find/estimate a new location on track, but instead keep the old one. Again, not sure if this would work in all cases, since the kart might be tumbling - esp. with the upcoming work of being able to drive on the walls.
We might just accept this otherwise ;)

**Comment by Wuzzy2** [comment]
Sorry, I don't really know where exactly it happens. I am not sure if I can see a certain pattern in this. :-/
