### ISSUE TITLE
C++11

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#2273]
Some code already uses C++11, but in some cases this is disabled for Max OS X. So when can/should C++11 be used? This should also be documented e.g. on the wiki.

**Comment by konstin** [comment]
leyyin suggested the following: (see https://etherpad.fr/p/stk_coding_convetion if it's still there)

1. use C++11 smart pointers  http://en.cppreference.com/w/cpp/memory
2. Use nullptr instead of NULL http://en.cppreference.com/w/cpp/language/nullptr
3. Use C++ static_cast instead of C style casts http://en.cppreference.com/w/cpp/language/static_cast and https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Casting
4. Use C++11 ranged for loops where possible http://en.cppreference.com/w/cpp/language/range-for
5. Try to respect coding convention?
    *  http://supertuxkart.sourceforge.net/Coding_Style
    *  https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Conditionals
    * Sometimes we are all guilty of writing if(something) instead of if (something), maybe add a linter on github?

**Comment by auriamg** [comment]
The OSX attempts at not using C++ 11 are mostly outdated, this was from a time where we tried to retain compatibility with older OSX versions, we have now given up on that and only support 10.9+, so anything supported by recent gcc/clang should be okay

Regarding the various features, we should check what versions of each compiler support them, some c++11 features were only implemented in very recent versions of some compilers but I don't know which ones by heart

**Comment by hiker** [comment]
I am not a friend of linter, because often we do some strange indentation (or not follow other coding style rules in detail) to improve readability.

Re if() - note that this is not and never was a coding style requirement for us. I think it mostly started to creep into the code because editors (e.g. VS) added this by default.

C++11 - I don't want to spend a lot of time changing e.g. 100's of casts to static_casts, I admit I don't see any sense to do that (most of our casts are used to avoid compiler warnings like comparing unsigned with signed - if anyone wants so spend time on that, it would be better to find out which of our signed ints can be unsigned etc, so that any cast would not be necessary anymore)

*grin* And I like the recursion that our coding style states to use our coding style ;)

**Comment by leyyin** [comment]
@hiker Nobody said anything about changing all the old code, but if you modify or add new code maybe use static_casts instead of C style casts :smiley: . Main advantage of static casts is that they are checked at compile time.
