### ISSUE TITLE
Clean stun server list

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#2274]
Some of the stun servers in the list in the config file don't work any more. They should therefore be removed from the list.

**Comment by hiker** [comment]
Ideally we should try to sort/prioritise stun servers, so that not working ones will (over time) not used anymore. E.g.:
give each stun server a weight, starting at say 20. On each successful connection the weight is increased by 1, otherwise it is decreased by 1. Clamp this value by [1,40], and randomly select a server based on weight.
Additionally we should be able to update the stun server list from our server.

**Comment by Alayan-stk-2** [comment]
@Benau I see you removed stun servers that don't support IPv6. What's the status for this issue ?

**Comment by Benau** [comment]
if you don't need to "Additionally we should be able to update the stun server list from our server", then this can be closed

**Comment by Benau** [comment]
maybe we can use srv record instead of getting from stk-addons (or vampy!) ![](https://lihkg.com/assets/faces/pig/dance2.gif)

https://en.wikipedia.org/wiki/SRV_record

**Comment by Benau** [comment]
not sure if you think it's complicated lol https://github.com/supertuxkart/stk-code/commit/a3a80f886f34e85a4da14fdad75d4644d336365c ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif) ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/364936e37bb768c96eb95c95ccefc43ffef8174d
![](https://cdn.lihkg.com/assets/faces/pig/drum.gif)
