### ISSUE TITLE
Translation files update are needed?

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2298]
Let take Chinese Traditional one for example, as I see, all strings should get translated already,but somehow are left in english in stk for some strings.

After looking deeper, some are because of wrong input msgid, like "Collect blue boxes : they will give you weapons or other powerups" but in stk show "Collect blue boxes( . They)...", using the correct string in stk will make it translate.

Some are because of wrong wrapping line (maybe)? like the "follow the leader" help message,I don't know how to fix, but there's a chinese translation for that string.

Some are because of plural aware string like "Confirm resolution within %i seconds", changing seconds to second make chinese translation shown (as no plural in chinese). Don't know what to do for other languages, even for languages that use plurals form (like spanish), it still get untranslated. Maybe tinygettext need to be configured more?

3 problems apply to all languages too.

**Comment by hiker** [comment]
The FTL string is not caused by line wrapping, but by us removing a space before a ':'. Similar style fixed causes the other translations to not work atm.

Transifex should mark these strings to be reviewed..

The plural strings were only added in June, so they would not be in transifex yet. Auria has just updated the translations, it might be a few hours before this is reflected in transiflex. Then all should work as expected.

Thanks for the ticket!
   Joerg
