### ISSUE TITLE
Collision shape wrong position in overworld

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2300]
Collision shape wrong position in overworld for big doors
![overworld_bug](https://cloud.githubusercontent.com/assets/4296971/9537069/0956dc24-4d02-11e5-9a9a-cb4f9c231cf3.jpg)

**Comment by auriamg** [comment]
The physics debug now shows the right thing, but the collision doesn't actually work

**Comment by hiker** [comment]
When the doors are declared as static-object (inside the <track> section), it works - but then it appears that the if-statement in the xml does not work (i.e. you get both doors). Using static-object was the 0.9 approach, and it would mean that the meshes are simply converted and added to the track mesh.

Using the box shape also has the disadvantage that the collision with the wall happens before the wall is touched - because of the 'door knocker', which makes the AABB bigger.

Otherwise I am still not sure why no collision is happening. The collision is actually detected (i.e. callback in stk's physics function is called) - but no push back of the kart. Probably the doors are the wrong body type (kinematic instead of static?)
