### ISSUE TITLE
Improve (V)RAM usage by loading fewer textures

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2316]
Currently STK loads all textures from the data/textures/materials.xml.  this made sense years ago when STK had few global textures, but now there are a LOT more and this uses a lot of ram/vram. We should switch to a better texture loading strategy

**Comment by qwertychouskie** [comment]
Wow... over 250 textures loaded!?! No wonder RAM and VRAM requirements are so high!

**Comment by SuicSoft** [comment]
@qwertychouskie What are these textures for ? And also does STK render the whole track scene or only the part visible.

Also I can play STK with these settings

- Advanced pipeline
- Shadows at low quality
- Bloom
- God rays
- Global illumination
- Image based lighting
- Glow
- Whether effects
- No texture compression (since it causes particle glitches)
- Use HD textures
- Animated scenery
- Anisotropic X4

On my laptop (with Radeon HD 7640g) with 512MB VRAM and 2GB shared without using swap and the game is around 20  - 40 FPS (with fglrx or Windows 10 , Ubuntu 16.04 driver is sooo slow).

So I seem to be able to run the game perfectly with 512MB VRAM ?

**Comment by deveee** [comment]
Easy way to improve RAM usage is that texture size could depend on selected
resolution. We don't need 1024x1024 textures for 1024x768 resolution. The
non-HD property in options works generally fine, so we could just use an
additional multiplier and always scale textures related to window
resolution. This could decrease RAM usage from ~850MB to say ~400-500MB or
something around it for lower resolutions.

**Comment by SuicSoft** [comment]
@auriamg Will doing this make STK slower ?

**Comment by auriamg** [comment]
@SuicSoft no. it may shift loading times around a bit but in the end it won't be slower, it may even be faster on lower-end GPUs

**Comment by Benau** [comment]
Branch merged
