### ISSUE TITLE
Abyss: falling in the canal in the last curve before checkpoint counts a finished turn

### ISSUE THREAD

**Issue by akien-mga** [supertuxkart/stk-code#2318]
As shown in this screenshot:
![addon_abyss-2015 09 20_11 00 25](https://cloud.githubusercontent.com/assets/4701338/9979977/2df4914c-5f87-11e5-8877-d81985064d45.png)

This seems to happen regardless of whether one falls in the canal at its beginning or at the end. The pick-up mechanism with Thunderbird works fine, but it counts as if the player was already past the start line (as shown in the screenshot where "Tour 2" is shown even though I'm still in the first turn).

When using this trick in the last turn, one can easily go from last kart to first one, since one can save ~10-15 s.

**Comment by auriamg** [comment]
Thanks for the bug report. The tracks has had a few improvements since the preview version was released, and this problem doesn't seem to exist anymore. So I'm pretty sure that when we release the final version of this track it's going to be okay. So I'm closing this as fixed, though if when we finish and release this track you find more issues of course don't hesitate to report them! Thanks
