### ISSUE TITLE
Hole in fort magma

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2332]
![fortmagma-2015 09 30_09 50 05](https://cloud.githubusercontent.com/assets/4296971/10236318/3a7bd62a-6872-11e5-8e21-b0bbf818ab7c.png)

Unfortunately, we lost a bit of work on fort magma when sourceforge crashed and restored from an earlier backup...

**Comment by cap44** [comment]
Can confirm

**Comment by deveee** [comment]
@auria, do you mean files corruption or just that older version
without some commits has been restored from backup? I have assets and
media repo as git locally, maybe I have these commits.

**Comment by auriamg** [comment]
@deveee : as far as I know, a few commits were lost. If you still have media repo from before the sf issue, and you had updated to latest version right before the crash, you could share your fort magma media repo files, maybe we can get some data back :)

**Comment by deveee** [comment]
I checked and unfortunately I don't have these commits :(

**Comment by leyyin** [comment]
Logs for the fortmagma track, I last updated last week I think
```
------------------------------------------------------------------------
r16420 | auria | 2015-08-28 16:56:03 -0700 (Fri, 28 Aug 2015) | 1 line

Add lossless version of texture
------------------------------------------------------------------------
r16406 | auria | 2015-08-27 18:07:43 -0700 (Thu, 27 Aug 2015) | 1 line

Tweak fort magma to be less dark
------------------------------------------------------------------------
r15767 | auria | 2014-11-12 15:12:18 -0800 (Wed, 12 Nov 2014) | 1 line
```

Do you know on what date the commits were made or what was the commit message and when SF crashed?
Maybe we can ask in the forums if they have updated the media repo right before the crash.
Also, this is a bit worrying, losing your work because of Sourceforge (and their service seemed to be very unreliable in the last year or so).

**Comment by deveee** [comment]
The storage fault was 16.07.2015. But even if you have these commits 
locally, they won't be visible in main branch and you will need to find 
them manually. I suppose that they are lost because it's not needed to 
update media repo that frequently.

Here is full email from sourceforge:


SourceForge experienced a storage fault on 2015-07-16.  Service restoration
has been in-progress since that time, and our latest full status update 
is online at:
http://sourceforge.net/blog/sourceforge-infrastructure-and-service-restoration-update-for-724/

Subversion data has generally been restored to the 2015-07-14 backup. 
We have identified
497 Subversion repositories which received commits after 2015-07-13 and 
before the storage fault.
Your project, supertuxkart, is one of those repositories.

To determine which repositories are missing recent commits, we compared the
revision count currently in your repository on disk (Current revision on 
disk)
to the revision count seen by our repository tracking (Current revision 
in database).
The repository tracking database does not house a full copy of your 
commit data.
We determined data needed to be committed again because the Current revision
on disk is less than the Current revision in database.

Analysis of your repository compared to our SCM repository tracking data 
shows:
Current revision on disk: 16349
Current revision in database: 16350

Recent commit events tracked in database:
r16349	samuncle	Wed Jul 15 2015 23:14:36 GMT+0000 (UTC)	Add many new 
textures for an upcoming map
r16350	samuncle	Wed Jul 15 2015 23:29:39 GMT+0000 (UTC)	I forgot to add 
volumetric objects


Since commits were made to your repository after our restore point, it 
will be necessary
for you to coordinate within your team to ensure these changes are 
recommitted.

We recommend you make a backup of your existing repository checkout, 
then make
a fresh checkout of the repository in another directory, copy over any 
changes
and commit. Depending on the number of developers on your team and the 
granularity
of change tracking you need for these uncommitted changes, you may need 
to tune
this process for your project. Please coordinate with the other 
developers on
your project team before committing.

If you have any follow-up questions or concerns, please contact the
SourceForge Support team by submitting a ticket at:
https://sourceforge.net/p/forge/site-support/new/

Thank you,

SourceForge Support

**Comment by auriamg** [comment]
Fixed in SVN by reverting the castle to a previous version, the little bits that were lost can be redone for next version
