### ISSUE TITLE
Numeric values for the speedometer

### ISSUE THREAD

**Issue by RQWorldblender** [supertuxkart/stk-code#2339]
It's hard for me to tell precisely how fast I drive a kart (either in metric or imperial units), as the place where the numeric speed value used to be is replaced by the rank number, which I personally think could be moved next to each kart icon in the rank area. Next to the speedometer, there is the nitro meter, which I also have no way to tell the numeric value of. This makes it hard for me to tell whether I have collected enough nitro in the challenges that involve collecting them. To make it clear on what the values represent, I prefer that units accompany them in order to reduce ambiguity, and those should be placed in areas that are comfortable to place and read.
I may like to see showing/hiding them as an option so that these numeric values wouldn't cause for those who like the current speedometer setup.

![screenshot from 2015-10-06 20 47 46]
(https://cloud.githubusercontent.com/assets/13372387/10327330/a53f43b4-6c6b-11e5-941f-e2fedc615260.png)

**Comment by deveee** [comment]
A lot of people complain about speedometer which shows rank number instead of speed value. I personally was thinking that it is simply broken and always shows me speed value "1" :P But it is actually minor thing and if some people decided that it should show rank number, it's not a big problem for me.

Adding an option to show/hide numeric values doesn't have sense for me - it's just a speedometer.

**Comment by samuncle** [comment]
It would be better IMHO if it display the speed instead of the rank. It's very confusing I just learned now it display the rank. I thought it was broken :P

**Comment by RQWorldblender** [comment]
Well, I gotta see why the rank number would be displayed if not the speedometer and/or the nitro value will be brought back. I will accept the defense if I think it will make sense.

**Comment by hiker** [comment]
Not knowing exactly how fast you are is done on purpose: STK is not a realistic simulation, it focuses on fun and just driving - numbers are not really necessary for that. If you play with more karts, not all karts are shown in the rank area, so we can't display it there anyway.

Nitro display: similar reason as speed - we want to focus on 'just drive', not on optimising the last drop of nitro (together with air pressure, terrain, ...). There are games that focus on more realistic simulations, but stk is not one of them.

Challenges display a line at the target value, so that should be easy to see.

PS: Sorry, I forgot to publish this comment when closing the ticket

**Comment by deveee** [comment]
@hiker you actually didn't close this ticket. Not sure if you wanted to do it or not.

**Comment by hiker** [comment]
*grin* Yes, I didn't want to appear not wanting to discuss this (*grin* too many negatives?) So, feel free to comment, even if I close it now :)

**Comment by brmbrmcar** [comment]
The option would be easy to implement. It should be implemented.

**Comment by RQWorldblender** [comment]
Okay, at least showing the speed value can be an option, but not the default.

**Comment by brmbrmcar** [comment]
It makes no sense to show position there anyway, instead showing it above the rank would make more sense.

**Comment by Arthur-D** [comment]
Why do you need more information? I have never really seen the need for watching how fast I was driving, I am simply driving as fast as possible under the current condition.

**Comment by Alayan-stk-2** [comment]
Even if the numbers are deemed unnecessary (which neglects that numbers can be fun for some), displaying the rank there is confusing.

This is not an expected behavior for a speedometer, and most new players will think it's broken/be confused for some time before understanding what it does.

This alone is enough reason to change it.

**Comment by qwertychouskie** [comment]
Instead of showing 1, 2, 3, 4, etc. ideally it should show 1st, 2nd, 3rd, 4th, etc.  This simple addition should eliminate any confusion.

A MK Wii screenshot for comp:
![](https://gamefaqs.akamaized.net/screens/2/b/9/gfs_93390_1_16.jpg)

**Comment by Arthur-D** [comment]
The problem with 1st, 2nd etc is that different languages have different pluralization rules. Some even start with the plural form, so in English that would be st1, nd2 and so on. Quite complicated to get right for every language.

Of course we could decide that we only use English for the rank, and I think most players would have little problem with that - few games support as many languages as we do. But another solution would be to go back to showing how many ranks there are in a given race. Examples: 1/4, 2/9. One potential confusion with low numbers could be that people think it's the current gear, but anyone knowing how gears work should know that you don't start at 4/4 gears and move down in numbers. So I think it would be a good solution which we actually used before.

**Comment by brmbrmcar** [comment]
But it should stay away from the speedometer. Otherwise it always looks broken.

Also speed is a useful comparison - especially if you were to do it for a ghost kart. Exact numbers make much more sense than a rough graph.

And don't assume ALL players can understand English, even just a bit; they can't. They may understand st or whatever as it wouldn't matter too much, but it would still raise questions as to what it means.
