### ISSUE TITLE
Add engine click click noise when the kart isn't moving

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2340]
To increase the soundscape diversity and since we got now a noise for nitro boost, I have decided to add a click click cooling sound when the kart stops after some time (a few sec).

When you drive and you stop your car you can hear the sound of the engine cooling. It's a nice touch + a nice idle thing.

I have already found a sound http://freesound.org/people/zimbot/sounds/203069/
If nobody do it, I will probably implement this myself with the help of someone from the team

**Comment by hiker** [comment]
When on earth do karts actually stop in the game so that you would hear that sfx? When they hit an obstacle, then the crash sfx is playing, and the kart will quickly start again. And even then the engine sfx is always playing anyway.
Adding sfx just because we can is not a good idea (performance-wise), esp. since I still hope one day to get kart specific sfx, which would be much more important.
