### ISSUE TITLE
Consolidate achievements, players, and online profile

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2347]
I have created a concept to reduce some UI redundancy and hopefully make things take less space but also not be any less logical or hurt discovery of these features. Descriptions inside each image; if I have overlooked anything or you have questions about the concept please comment.
![online_menu_consolidation1](https://cloud.githubusercontent.com/assets/5515261/10420073/6f765188-7089-11e5-9b53-044f2cc13555.jpg)
![online_menu_consolidation2](https://cloud.githubusercontent.com/assets/5515261/10420074/6f79cad4-7089-11e5-85e0-8c44634c4586.jpg)
![online_menu_consolidation3](https://cloud.githubusercontent.com/assets/5515261/10420075/6f810a74-7089-11e5-9340-4625fa179036.jpg)

**Comment by auriamg** [comment]
Another mockup to keep the discussion going

![mockup](https://cloud.githubusercontent.com/assets/4296971/10420282/d87dd254-705d-11e5-86fd-a01ea45a3c4d.jpg)

A few points IMO :
* this screen does too much stuff, it's a player switcher, a profiles management screen and a login screen. IMO we are still putting too much on the same screen
* Not sure I like the use of icons as profile switcher. It's not too clear it's a switcher, plus for most people there will be 1-2 profiles which means poor use of horizontal space (plus a single icon floating in the middle of the screen is a little weird)

**Comment by krobonil** [comment]
and one more mockup:
![bildschirmfoto 2015-10-20 um 14 41 27](https://cloud.githubusercontent.com/assets/9907631/10607282/cc115310-7738-11e5-9450-f6e63a84ff38.png)

I like the idea with the profile switcher. I tried to combine the ideas and made a vertical one.
With this layout we don't need the "Rename" button - What do you think about?

**Comment by auriamg** [comment]
krobonil: this looks good, however the main issue with this design is that with out current GUI engine, this screen would only work with a mouse, our engine is not sophisiticated enough to enable gamepad navigation of suck a complex screen

**Comment by krobonil** [comment]
That's true - Thank you for the feedback.
I found a way, which would be also friendly for gamepads and keyboards.
How about this solution here?

![bildschirmfoto 2015-10-21 um 16 26 49](https://cloud.githubusercontent.com/assets/9907631/10639435/997a9d20-7810-11e5-826a-06be493d4f38.png)

This one looks pretty similar to your idea. I just made the window-size smaller and gave a black background to make focusing easier.
After the button OK this Window will appear:

![bildschirmfoto 2015-10-21 um 16 26 55](https://cloud.githubusercontent.com/assets/9907631/10639447/a7c8c6ea-7810-11e5-8590-cc84c30f4869.png)


I believe this way will make it easy to switch a profiles fast without seeing too much settings.
-> Just hit Enter for the main-menu.
Players with more time can choose here the "View Profile" and land on a similar window like Arthur-D made.

On this way is for a password change no retype of the old password required,
because it has already been entered.

**Comment by Arthur-D** [comment]
It looks quite good, the latest one, though I dunno how it would fare with a controller, but it would probably work I would think.

**Comment by Alpt** [comment]
Adding to the brainstorming:

 Use the player's icon as the button for switching player in the main menu screen. See image below, on the top right:
 
![stk-resized](https://cloud.githubusercontent.com/assets/8207321/17806285/e888024a-6603-11e6-829d-8e3fb92b57d5.png)

 In the Login screen and the Player switch screen remove the "Add player", "Remove player"
, "Rename player" buttons. In other words, let the login screen be just a login screen.

Add the change-password button in the Options -> Players screen and remove it from Online -> Settings. It is enough placed in Options -> Players, there is no need to create another settings screen.

**Comment by qwertychouskie** [comment]
I created a modified version of the pettanent files for @Alpt 's first point:  [usericon.zip](https://github.com/supertuxkart/stk-code/files/446105/usericon.zip)
Replace the files with matching versions in the zip and recompile to test.

**Comment by qwertychouskie** [comment]
Actual patch: [use_user_pic.patch.txt](https://github.com/supertuxkart/stk-code/files/446185/use_user_pic.patch.txt)

**Comment by CodingJellyfish** [comment]
I thought about it for a while, and the current replication on player profile inside and outside online menu makes sense. The online account has friends and change email/password settings, and the offline users would have achievements only, so split them up is okay. Also putting player selection and player profile screen together breaks the hiearchy between player and player profile (Since each player has a different player profile) so the current screen is still the best solution.
