### ISSUE TITLE
Sound effect issues on Cocoa Temple

### ISSUE THREAD

**Issue by onetrev** [supertuxkart/stk-code#2377]
Within about the first 10-20 seconds of racing this track, I start to get serious sound playback glitches.  Once this issue starts it does not stop until I quit the race. There is what sounds like audio clipping, a very clear echoing of sound effects and music, and the music playback tempo slows right down. 

If I race this track with just MUSIC enabled, this does not occur. If I race the track with ONLY EFFECTS enabled it occurs within basically the same time frame.

System Details:
STK 0.9.1
Dell XPS 13 - Intel i5-5200u
Intel Display Audio / Intel SST / Realtek HW Audio Codec 
Windows 10
(sorry don't know which or these actually is responsible for audio)

**Comment by hiker** [comment]
Not sure if this might be an issue with your sound card, or computer. What FPS do you get when you run without sfx (and a single kart)?  (see http://supertuxkart.sourceforge.net/Artist_Debug_Mode to enable artist debug mode, when you then right click during a race, you will get a popup menu where you can select to show the FPS).

We could try to see if this is one particular sfx causing this issue. Make a copy of the file .../data/tracks/cocoa_temple/scene.xml, then open this file in an editor, and start removing the lines with 'sfx' in it, e.g.:
```` <object type="sfx-emitter" id="Empty.043" sound="exotic-birds_2.ogg" rolloff="0.050" volume="1.0" max_dist="130.0" xyz="179.54 5.78 120.78" hpr="0.0 -0.0 0.0" scale="127.61 127.61 127.61">
  </object>
````
Make sure to delete everything from the begin ('<object...') to the end of this tag ('</object>').

Do this one by one, and see if a certain sfx causes the problem (or if the problem goes gradually away).
Just to be sure: when I asked you previously to test this by driving in reverse - did you use any AI , or where you driving alone (if this problem is still related to the bridge sfx, the AI could still trigger the problem).

**Comment by onetrev** [comment]
Well the computer should easily have the power. Sorry I forgot to report FPS details....

3 AI carts - average 28FPS, nothing lower than 20ish FPS
1 AI cart - average 30FPS, nothing lower than 24ish FPS

And yes I did definitely test with NO AI carts, and the issue still occurs. The FPS doesn't seem to be affected when it happens, though it does seem a bit less smooth, maybe that part is just in my head due to sound being totally insane. :)

I'll start testing SFX objects now if I can and report back on that if I complete it.

**Comment by onetrev** [comment]
Testing complete! I tested as directed, removing one object at a time, such that each time there were less. 

Things got better for sure around 4th and 5th objects that I removed. Definitely when the 5th  (id="Empty.047") one was gone, music and sound effects played back perfectly for all 3 laps.

To make sure it wasn't one of those two objects I restored the file and just removed those two objects, but playback was still broken. So my assessment is the less of them in there is what solved it. Not sure if that helps at all, hopefully does.

Thanks!

**Comment by qwertychouskie** [comment]
@onetrev The was a recent audio leak fixed in Git, can you retest?

**Comment by onetrev** [comment]
Dang, I wish I could but I don't have the same machine anymore. Sorry!

**Comment by qwertychouskie** [comment]
No problem.  Maybe close it since it can't be tested currently, and someone can make a new issue if they ever have that problem again?

**Comment by onetrev** [comment]
Agreed. I feel confident it's fixed. :)
