### ISSUE TITLE
License of the Antarctica engine

### ISSUE THREAD

**Issue by est31** [supertuxkart/stk-code#2381]
Hi,

from reading the [COPYING](https://github.com/supertuxkart/stk-code/blob/master/COPYING) file, it seems that you license the Antarctica irrlicht fork under the GPL. Is that true?

If it were, it would be very unfortunate, as it makes use by non GPL-compatible code impossible (third party games using it as engine, like #2358), and it also prevents one to backport patches to upstream irrlicht. For example, I would want to backport commit 5117ab0a0ecc5e79df2f19d6cb5b201ee77384d4 .

**Comment by est31** [comment]
(Unrelated note: I have found a way around backporting 5117ab0a0ecc5e79df2f19d6cb5b201ee77384d4 , a working fix requires three lines to be changed, that's all.)

**Comment by deveee** [comment]
@est32 IIRC just fourth parameter in XConvertSelection shouldn't be None to avoid a crash. I'm additionally waiting until I receive clipboard event before reading.

You can assume that all my changes in CIrrDeviceLinux.cpp are under zlib license. Should I note it somewhere?

From more interesting things, there is improved resolutions handling using xrandr. It supports multiple monitors, allows to use rotated screen and avoids some issues with restoring resolution on exit. The code could look better (I should at least use goto instead of hacking it using while+break), but now I don't want to modify something that works fine.

The only problem that I see is that when we force in xorg.conf to use xinerama, then xrandr extension is not available, and then we don't have information about screen size. In this case we just use windowed mode.

**Comment by auriamg** [comment]
Actually we would like to use more permissive licenses, but STK is an evolution of the old TuxKart game which was released under GPL and as such everything we touch becomes GPL because of that. Changing that would probably require getting permission from every contributor to relicense, which is pretty hard to do

**Comment by deveee** [comment]
As I understand he just want to port some changes to upstream irrlicht, which is under zlib license. I mean the code in stk-code/lib/irrlicht. If some of them are useful for upstream irrlicht, I'm fine with it.

Antartica engine is not easily portable and is part of the game. It would require to change whole STK license. And actually I don't want to use anything other than GPL for Supertuxkart.

**Comment by est31** [comment]
Backporting some patches is one question. The much larger other question would be about whether antarctica can be used by external programs that aren't GPL compatible. Not from a technical standpoint, which is separate, but from a license standpoint.

For example, minetest couldn't be ported to Antarctica without a license change.

**Comment by deveee** [comment]
But at this stage it's hard to determine what is the "engine" and what is the "game" because this code is mixed. The engine is not standalone library. And at least I don't want the situation that some chinese people sell slightly modified STK version for Android without publishing the source code. It's just my opinion, I don't know what others think.

**Comment by qwertychouskie** [comment]
Since 
> Actually we would like to use more permissive licenses, but STK is an evolution of the old TuxKart game which was released under GPL and as such everything we touch becomes GPL because of that. Changing that would probably require getting permission from every contributor to relicense, which is pretty hard to do.

and

> Antartica engine is not easily portable and is part of the game. It would require to change whole STK license. And actually I don't want to use anything other than GPL for Supertuxkart.

Can this be closed?
