### ISSUE TITLE
Going backwards and then forwards can cause you to win the race

### ISSUE THREAD

**Issue by TrevorDecker** [supertuxkart/stk-code#2385]
If you go backwards along the track about 30 meters and then go forwards again you will win the race without completing the entire circuit

**Comment by hiker** [comment]
Is this in any track, or just in one specific track?

**Comment by qaugustijn** [comment]
I have tested in Amazonian Journey and Scotland and it didn't work, I stayed in last place. At which track does it work?

**Comment by qaugustijn** [comment]
It is probably the checkline of one specific track, look at this picture:
![checkline-supertuxkart](https://cloud.githubusercontent.com/assets/16267411/12009610/121b6248-ac80-11e5-8de2-12c624dcb9ae.png)
You drive backwards across the checkline and then across the finish. If you cross all checklines and you drive across the finish, you have win the lap. It means that the checkline too close of the finish and there are no other checklines. You can fix it by yourself, if you can make good / simply tracks in blender. If the track is a add-on, go to the add-on page of supertuxkart and look if the source is available. If it is a standard track then download the source with git or svn on: https://svn.code.sf.net/p/supertuxkart/code/media/trunk/tracks/ . Open the blender file and search for all checklines. Move them further away of the lap line or finish. Export as a STK track and drop all files in supertuxkart.

I hope that this will succeed.

**Comment by Alayan-stk-2** [comment]
The issue of being able to win a race by validating checklines going backwards still exist in the current git (tested on shiny suburbs), though the official tracks have multiple checklines protecting them.

**Comment by auriamg** [comment]
At this point I would consider it fixed, since all tracks from the main game now use checklines properly. The documentation explaining how to make addons also explains that it is required to to use several checklines. Some add-on tracks might not do that properly, but at this point it's the responsability of these addons' authors to make sure they follow our guidelines when making addons (or, users can also just avoid cheating to get a proper experience when playing addons, you know ;) )
