### ISSUE TITLE
Missing life models for new karts

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2389]
Some of the new karts (not sure exactly which) are missing tire models on the back to indicate how many lives they have left in Battle Mode. This causes the game to exit unexpectedly with the lines
```
[error  ] main: Exception caught : Model '' cannot be found.
[error  ] main: Aborting SuperTuxKart.
```
after one of the affected karts lose a life.

This ticket depends on #2387

**Comment by Benau** [comment]
It turns out to be a different issue, some karts (like blinky, gnu, xue) don't need "wheels" to move, which lead to missing of wheel-*.b3d.

https://github.com/supertuxkart/stk-code/commit/239412327ad0fa65e1070d1344a5db174af7be83

Should be better now

Notice: This is unrelated to the spare tires on the back, which all karts will have two on their back.
