### ISSUE TITLE
STK 0.9.1 FTBFS on Debian armhf

### ISSUE THREAD

**Issue by Vincent-C** [supertuxkart/stk-code#2411]
(Forwarded from https://bugs.debian.org/808716)

STK 0.9.1 fails to build on armhf only; the full build log can be found [here](https://buildd.debian.org/status/fetch.php?pkg=supertuxkart&arch=armhf&ver=0.9.1-1&stamp=1450754030), tail of build log as follows:

```
lib/angelscript/projects/cmake/libangelscript.a(as_callfunc.cpp.o): In function `CallSystemFunction(int, asCContext*)':
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc.cpp:680: undefined reference to `CallSystemFunctionNative(asCContext*, asCScriptFunction*, void*, unsigned long*, void*, unsigned long long&, void*)'
collect2: error: ld returned 1 exit status
```

This is similar to #2119 and #2194 (which was fixed in the Debian package for STK 0.9.0 by applying #2195 / #2211 as a patch to the package), but there's now a new armhf-specific build failure in 0.9.1. @jcowgill, do you perhaps know how to fix this? Thanks!

**Comment by Vincent-C** [comment]
@auriamg / @hiker, what version of angelscript is currently embedded in STK 0.9.1? Does it include [this commit](http://sourceforge.net/p/angelscript/code/2177/)?

**Comment by Benau** [comment]
#define ANGELSCRIPT_VERSION_STRING "2.30.0 WIP" in lib/angelscript/include/angelscript.h

guess it doesn't have your patch, sorry about that...

**Comment by deveee** [comment]
@Vincent-C angelscript has been updated in may last time: https://github.com/supertuxkart/stk-code/commit/c48037984ddb71e33ddba507bbab57b735dd6413 so your commit is unfortunately not available in our sources yet. Maybe we should update angelscript, or at least apply this patch.

Vincent, I know that this is unrelated thing, but you are preparing STK builds, so I have occasion to contact you. STK 0.9.1 causes this issue:
https://github.com/supertuxkart/stk-code/issues/2190
which affects multiple users, because this is valid for every intel graphics card which we support (sandybridge and newer) for mesa >= 10.6. And unfortunately there is no easy solution atm. More info for example here:
https://bugs.freedesktop.org/show_bug.cgi?id=92759
http://patchwork.freedesktop.org/patch/67844/
This has been workarounded on our side. If you are interested in it, I can prepare a patch for STK 0.9.1 and will attach it to bug report or mailing list on Debian.

**Comment by Vincent-C** [comment]
@deveee If it's not too much trouble, please file a bug report with a patch, thanks! As long as that mesa patch makes it into an upstream stable release, I guess it's fine, but in the meantime there's still a delay between that happening and the fixed mesa version migrating to debian/ubuntu, and also it'll affect users on stable debian/ubuntu releases who want to use backported packages, so I'd prefer patching STK in this case.

**Comment by Vincent-C** [comment]
Regarding angelscript, in hindsight that was sort of a silly question for me to ask, given that I was able to rebase the patch from #2211 for STK 0.9.1, so of course the patch wasn't applied (and the build is failing *with* the patch applied in debian). c480379 suggests that taking a look at the diff between the version of angelscript embedded in 0.9.0 and 0.9.1 to try to figure out why it's failing to build on armhf isn't really feasible either (>10k lines of changes sounds like a nightmare to review). Not sure what the best approach is at this point...

**Comment by jcowgill** [comment]
Hi, this appears to be a Debian specific bug in the `fix_angelscript_build_on_non-x86_arches.patch` patch. After [this revision](https://anonscm.debian.org/viewvc/pkg-games/packages/trunk/supertuxkart/debian/patches/fix_angelscript_build_on_non-x86_arches.patch?r1=15643&r2=15642&pathrev=15643), the top of that patch contains this:

```diff
--- a/lib/angelscript/projects/cmake/CMakeLists.txt
+++ b/lib/angelscript/projects/cmake/CMakeLists.txt
@@ -102,12 +102,12 @@
     endif()
 endif()

-if(ANDROID)
+if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^arm")
     enable_language(ASM)
     if(CMAKE_ASM_COMPILER_WORKS)
-        set(ANGELSCRIPT_SOURCE ${ANGELSCRIPT_SOURCE} ../../source/as_callfunc_arm.cpp ../../source/as_callfunc_arm_gcc.S)
+        set_property(SOURCE ../../source/as_callfunc_arm_gcc.S APPEND PROPERTY COMPILE_FLAGS " -Wa,-mimplicit-it=always")
     else()
-        message(FATAL ERROR "Android target requires a working assembler")
+        message(FATAL ERROR "ARM target requires a working assembler")
     endif()
 endif()
```

You need to restore the line beginning `set(ANGELSCRIPT_SOURCE`.

**Comment by Vincent-C** [comment]
Whoops...I'm not sure how that happened. Thanks for pointing that out, and sorry for the noise!
