### ISSUE TITLE
Porting all on GitHub

### ISSUE THREAD

**Issue by SilverLuke** [supertuxkart/stk-code#2412]
Hello, this is my first "request" on Github, so sorry if this should be inappropriate.
For convenience you could move stk-media-repo and stk-assers (actualy on Sourceforge) to Github, and begin to create/porting a wiki for developers on GitHub?

**Comment by deveee** [comment]
I had full stk-assets history converted to git when we were migrating from svn to git. I'm not sure if I still have it somewhere. However there were some reasons to decide that svn should be used for assets. Generally it is working better with large binary files. Though still I personally prefer to use "git svn" over svn ;)

We could also use github instead of sf to provide stable binaries to download. Other quite big projects use it, for example freecad.

**Comment by SilverLuke** [comment]
I personally think is better use one platform, but if "svn" is better for large binary file, 
I'm good with it.ok

**Comment by Benau** [comment]
hiker told me because when there's a release, we will reach around TB traffic, which github may complain about that.....

**Comment by deveee** [comment]
Here is what github says:
https://help.github.com/articles/about-releases/
"We don't limit the total size of your binary release files, nor the
bandwidth used to deliver them. However, each individual file must be under
2GB in size."

Also freecad has about 5000 downloads per week:
http://sourceforge.net/projects/free-cad/files/
We have about 2000-2500 downloads with slightly higher file sizes. But it's hard to say how many downloads they have on github because I don't see any statistics there.

**Comment by leyyin** [comment]
Unfortunately Github does not have very advanced download tracking.
https://help.github.com/articles/getting-the-download-count-for-your-releases/

And by accessing the API with https://github.com/mmilidoni/github-downloads-count for [`FreeCAD 0.15`](https://github.com/FreeCAD/FreeCAD/releases/tag/0.15) you get:
```
FreeCAD-0.15.4671_x64_mac_osx.zip: 39041 downloads
FreeCAD-0.15.4671_x64_windows_setup.exe: 229546 downloads
FreeCAD-0.15.4671_x86_windows_setup.exe: 66629 downloads
FreeCAD-0.15_manual.pdf: 14906 downloads
LibPack_11.1_x64_VC12.7z: 4134 downloads
LibPack_11.1_x64_VC9.7z: 2037 downloads
LibPack_11.1_x86_VC12.7z: 1911 downloads
LibPack_11.1_x86_VC9.7z: 1460 downloads
```
The total bandwidth of those files is:
`(119*39041 + 193*229546 + 167*66629 + 24.7*14906 + 351*4134 + 355*2037 + 288*1911 + 274*1460) / 1024 / 1024 = 60.62 TB`

I really like Github but it lacks the download tracking we see in Sourceforge.

**Comment by auriamg** [comment]
In any case do not confuse source control hosting and downloads hosting, those are 2 separate issues

With regards to source control hosting, IIRC we had a discussion with someone from the github staff when moving STK to github and they old us that our assets and media repositories were quite borderline for git hosting and that git might have some trouble with them, which is in good part why we decided to stick to svn for those
