### ISSUE TITLE
Unable to nitro while turning left.

### ISSUE THREAD

**Issue by Dugglez** [supertuxkart/stk-code#2421]
yeah

**Comment by Cobiskuit** [comment]
What is your setup? Are you using a keyboard or a controller? Could be an issue with key rollout.

**Comment by Arthur-D** [comment]
Most likely same reason as #2185 which is a hardware limitation.

**Comment by Dugglez** [comment]
@Cobiskuit keyboard

@Arthur-D Looks quite similar so probably.

**Comment by Dugglez** [comment]
It's great how you guys are telling me why this is happening, but i really want to know how to fix it.

**Comment by Arthur-D** [comment]
Well, as explained in the ticket there's only two workarounds. One is rebinding your steering keys to different ones, the other is using different hardware, which may or may not be practical. Gamepad, "gaming" keyboard (which supports using more keys at the same time) or steering wheel.

Since buying new hardware is a bit unreasonable to expect I suggest the first option, unless you have a gamepad or similar lying around. Hope this helps.

**Comment by Dugglez** [comment]
just tried wasd but it just felt too unnatural

guess i'll never nitro left again. :(
