### ISSUE TITLE
Billboards vs materials

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2427]
Billboards are currently hardcoded to be transparent, and do not use the material system

Previously, they were forced into "additive"; in ea02f232dc84325c0623e1b6169dd0bb65aa8db9 I changed them to normal blending. But ideally they should follow our material system and do whatever is specified in materials.xml

**Comment by auriamg** [comment]
As of now the most important cases (additive, blending) are supported, the rest are lower priority until we find a proper use case

**Comment by samuncle** [comment]
maybe we could have Alpha Testing (to create impostor for trees) and improving performances.

That would be pretty much the only case left.

**Comment by Benau** [comment]
Actually if i modify my cpu particle to allow non-uniform size, we can use the cpu particle shader to draw billboard, and the logic for sorting alphablend/test/additive for drawing can be shared, just add something like addbillboardnode to the manager.

And deve after a simplfied shader my phone no longer crashes, so no workaround.

Maybe we can draw a specific explosion particle .png for android and use alpha test with it

**Comment by deveee** [comment]
@Benau For me allow to set min/max particle dimensions in .xml would be best solution. So that you can declare that single particle can be at most 30% or 50% screen width. I was trying something like this with gpu particles and it helped for performance, but it wasn't 100% correct.

And if not, then we can just use specific .xml for explosion on android with less and smaller particles, so that it won't cause that big slowdown.

And btw. just a minor issue, but now particles in explosion effect take whole space immediately. Previously they were all starting in the center. Not sure if it's intended.

**Comment by Benau** [comment]
With 2427 merged using alpha test with tree is possible (need devee find out if it slows down his phone...)
