### ISSUE TITLE
More Specific Multiplayer Join Text/Explanation

### ISSUE THREAD

**Issue by egirsova** [supertuxkart/stk-code#2462]
As of right now it says "Everyone: Press 'Select' now to join the game!" in the multiplayer join screen. I'm wondering if we can make that more specific? If there are multiple configurations, maybe indicate what specific key needs to be pressed (aka what the 'Select' key actually is). 

For example, something like the following: 

Everyone: Press 'Select' now to join the game!
Player 1: \<Enter\>
Player 2: \<Tab\>
...
etc.

I think this would make it more clear because it can be confusing for a first-time player. At least I remember having difficulties figuring out exactly what was expected of me as the user. Thoughts?

**Comment by Benau** [comment]
Actually we can use "fire" button instead, as some players using same keyboard may have "return" key bind the same.

For your idea, I'm not sure using Player 1-4 will be enough for the screen...

**Comment by auriamg** [comment]
I'm all for making it clearer, though the specific way that was suggested cannot quite work, as we don't know who player 2 is before they join (i.e. if there's 4 controllers connected into 4 USB ports, we can't tell which controllers will be use - especially since on some OS, fake gamepads are reporteds, many linux systems report hard disk interferometer as a gamepad, and also some player might decide to use the keyboard. Finally, we don't have very specific key names, for gamepads we could only say "Press button 3" or something like that as we don't have actual button names for different gamepad brands).

So all in all not a bad idea but not quite feasible. Not sure if you have another idea

**Comment by egirsova** [comment]
That's a good point. If we can't make it more specific in terms of the key itself, then I would suggest just making a minor change to something like "Everyone: Press the 'Select' key to join the game!" rather than just "Everyone: Press 'Select' now to join the game!". I remember when I first read that I thought it was referring to some sort of "Select" button on the game screen itself (which I obviously couldn't find). 

Do you think that change would be confusing for players? I doubt players would try to look for a key actually called "Select" on their systems but I guess it could happen.

**Comment by auriamg** [comment]
Maybe just adding a gamepad icon next to the text would be enough to make it that much clearer

I know there were other changes we wanted on that screen, for instance there should be no player by default, the first player should also ave to press fire, otherwise its pretty confusing

**Comment by qwertychouskie** [comment]
"Everyone: Press the 'Select' button/key to join the game" would be better, as "key" for a gamepad could be confusing.  Also, the exclamation point seems not quite right.

**Comment by auriamg** [comment]
Yeah, that is quite a minor change but it does help a bit, I've committed a text change in 8c29fb01f6921e0f8c3d4b600929cbf3d800c0ff

I used "button" only instead of "button/key", I think even for keyboard users button is clear enough

Of course there are further ways this could be improved but this is a first step...
