### ISSUE TITLE
roatated sky

### ISSUE THREAD

**Issue by GetHandle7** [supertuxkart/stk-code#2463]
When advanced pipeline is turned off on version 0.9/0.9.1, player(s) on the top half of split screen have a sky that rotates on the wrong axis as they turn. This changes the orientation of the equatorial plane instead of rotating the sky from a vertical axis. The issue does not occur for the player on the bottom half of split screen or when advanced pipeline is on. Tested on Ubuntu 14.04 and Mint 17.2.

**Comment by deveee** [comment]
I tested it on nvidia with current drivers and I see exactly the same behaviour, so this must be something wrong in our code.

**Comment by Odd0002** [comment]
This does not seem to happen when the legacy (< OpenGL 3.1) renderer is used.

**Comment by deveee** [comment]
The sky rotation works properly. Generally the problem is here:
![zrzut ekranu z 2016-04-26 22-30-52](https://cloud.githubusercontent.com/assets/5108558/14833255/a2e32c24-0bfe-11e6-838f-dc72f30e8e5c.png)
It should draw two the same sky boxes (on top and on bottom). But on top it draws top part of the skybox, and on bottom it draws the bottom part. As a result, we see top part of the skybox for first player, which looks strange. The bottom part looks fine.

Atm. I have no idea what's wrong. Viewports seem to be set properly.

**Comment by deveee** [comment]
Actually this screenshot is better because it shows that this game is started for two players ;)
![zrzut ekranu z 2016-04-26 22-23-25](https://cloud.githubusercontent.com/assets/5108558/14833344/1d2251ae-0bff-11e6-8dd0-75166ecf9cf1.png)

**Comment by deveee** [comment]
It looks like gl_FragCoord gives us values of whole screen instead of current viewport. Here is a ugly workaround:

```
diff --git a/data/shaders/sky.frag b/data/shaders/sky.frag
index eb339c8..cd80cf1 100644
--- a/data/shaders/sky.frag
+++ b/data/shaders/sky.frag
@@ -4,7 +4,7 @@ out vec4 FragColor;
 
 void main(void)
 {
-    vec3 eyedir = vec3(gl_FragCoord.xy / screen, 1.);
+    vec3 eyedir = vec3(vec2(mod(gl_FragCoord.x, screen.x), mod(gl_FragCoord.y, screen.y)) / screen, 1.);
     eyedir = 2.0 * eyedir - 1.0;
     vec4 tmp = (InverseProjectionMatrix * vec4(eyedir, 1.));
     tmp /= tmp.w;
```

But the real reason is sitll unknown :P

**Comment by deveee** [comment]
Slightly modified patch applied here:
https://github.com/supertuxkart/stk-code/commit/58f7424b4f31fd0d6d3db6b34e3b09b027ac8da7

As written in the commit message:
The problem was with shader-based pipeline with disabled "advanced effects" in options.

In this case we don't use RTTs and gl_FragCoord contains values in range of whole window. So fo 2 players we still get gl_FragCoord.y = 0..window_size instead of gl_FragCoord.y = 0..window_size/2.

The easiest way to solve it seems to be modulo it by current viewport size. It should be compatible with advanced pipeline as well as single-player games.

**Comment by deveee** [comment]
If nobody complains, then I cherry-picked this commit to 0.9.2.
