### ISSUE TITLE
Boost from drift should be dependent on severity of drift

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2487]
In Mariokart, when drifting, how quickly the boost comes depends on how hard the drift is.  In Supertuxkart, shallow drifts can be used on straightaways to move much faster.

**Comment by deveee** [comment]
I agree in 100%. I always use skidding on wide straight roads because it allows me to run faster.

**Comment by auriamg** [comment]
This is not a bad idea, though we would need to find a way to determine what is an "easy" drift though, that's not so obvious to determine programmatically

**Comment by hiker** [comment]
That should just depend on the angle: i.e. if you left skid, and fully turn left --> high accumulation (shorter time) and/or stronger bonus acceleration  if you left skid but turn right (nearly straight), low accumulation (high accumulation time) and/or weaker bonus.

We need to decide what we prefer - shorter accumulation time or stronger bonus. I'd guess that shorter accumulation time works better, since the stronger bonus might be a challenge to control (esp. for the AI, which is already struggling a bit with skidding).

Implementation would be easy, but still scheduled for 0.9.3 - it might affect all our challenges, AI behaviour, might even need more tweaking to established tuning parameters.

**Comment by Arthur-D** [comment]
If we still aim this for 0.9.3 it should probably be done soon or there will be little time for testing, especially if we need to retest all challenges. Otherwise it should probably be postponed.

**Comment by qwertychouskie** [comment]
Maybe this should be added as an option in `stk_config.xml`.  That would allow easy testing.

**Comment by Alayan-stk-2** [comment]
Here is an idea about how to do this : 
- Configurable factors for mild/normal/severe drift used as multipliers to the time needed to get the bonus. Say 2 for mild drift, 1,5 for normal and 1 for severe ; with current time corresponding to 1.5.
- More feedback in GUI with a progress bar ; the point at which the bonus first becomes available being clearly marked. (Maybe something like my mockup for #3149 - the two could use a similar system, with maybe icons for each to clearly distinguish them). The full bar would correspond to the "red drift" (should the bonus scale between the two or remain fixed ?)

**Comment by Alayan-stk-2** [comment]
The current system, while not ideal, is "good enough" for now - the gameplay remains challenging and interesting. I don't expect to work on this before the next release, and I don't think anyone else in the team will either.

Postponing.

**Comment by Flexmaen** [comment]
I'm new to this game, but this drifting behaviour doesn't make sense to me.

If you enter an online server as a newbie, everyone else just seems to be much faster than you from start even if you think you got a perfect start. After a while I noticed that all of these players learnt how to permanently drift on straight roads to get a higher speed. This certainly is some kind of skill but it rather feels like a cheat that ruins the fun of the game for me.

So, before having any chance against other online players you don't have to improve how to get around the curves. Instead you'll have to learn how to get a higher top speed on straight roads by using this drifting trick that doesn't exist in any other kart games.

**Comment by Threepbrush** [comment]
I love to drift in racing games; it worked in SuperTuxKart more than six years ago when I played with our daughter - it was fun. Now - out of a sudden - it's a pain?!? Please fix this; thanks.

**Comment by Flexmaen** [comment]
But skidding on a straight road just doesn't make sense... I wonder if there is any other racing game where you should do so.
Skidding on curves yes - but not on the straight road.

**Comment by Flexmaen** [comment]
How about just offering an option that drifting does not speed up the car?

**Comment by Alayan-stk-2** [comment]
STK is in many ways a game of timings. Learning the timings for skidding allows to anticipate the exact moment a skid bonus is going to happen. Making the skid bonus dependent on the angle the kart is turning at breaks this.

Besides, making straight lines in tracks slower and easier is not desired. To make karts faster on straight lines without the current mechanic would require going towards driving simulators physics where you must strongly brake before curves and the play is all about exiting the curve with as much speed as possible.

> If you enter an online server as a newbie, everyone else just seems to be much faster than you from start even if you think you got a perfect start. After a while I noticed that all of these players learnt how to permanently drift on straight roads to get a higher speed. This certainly is some kind of skill but it rather feels like a cheat that ruins the fun of the game for me.

Newbies should lose consistently to good players.

If friends of different levels want to play together, the handicap system is there (although it should be enhanced).

As for online play with strangers, ensuring closer races would be good, but this require server restrictions based on ranking points, and enough players to populate the different server levels. It would be a better experience but it's harder than it seems.

> Instead you'll have to learn how to get a higher top speed on straight roads by using this drifting trick that doesn't exist in any other kart games.

Incorrect, it was very prominent in Mario Kart DS https://mariokart.fandom.com/wiki/Snaking

In STK it is comparatively easy to learn to skid however, and more importantly it's part of what makes the game unique and interesting for many players.

> How about just offering an option that drifting does not speed up the car?

This can be done editing kart_characteristics.xml if you prefer it for local play ; but there is little reason to make it a game option.

```
              bonus-speed="4.0 6.0 7.5" bonus-time="3.0 4.0 5.0"
              bonus-force="300 400 500"
```

**Comment by Dr-Lambda** [comment]
In Mario Kart DS repeatedly drifting back and forth on straight roads was called "snaking". It is the feature that makes the game competitive. It was also very controversial. Casual players disliked it because it forces skill expression so that only the best players can win. Competitive players liked it because it allows skill expression so that only the best players win. I think whether you like it or not just depends on whether you want a shallow, relaxed game where anyone can win or a deep, challenging game which takes practice to really get good at.

These two groups of players probably cannot really have much fun playing with each other as what they want out of the game is opposed to each other. You cannot have the skill ceiling be low and high at the same time. The best way to make a game fun for both is probably to add a ladder system with something like ELO so that casual players can have fun low on the ladder against other casual players in matches where snaking does not occur and competitive players can have fun high on the ladder against other competitive players in matches where snaking does occur. Of course, this does require there be enough players of both groups to work well.

For me, in Super Tux Kart I got creamed online too by a snaker when I was new to online. But I loved it. It gave me something to do: find out how he drove so fast and learn to do it too. When I discovered snaking I was happy with it. It adds a whole layer of depth to the game and gave me something fun to practice. And once mastered, it makes driving the straight paths much more fun as instead of just holding forward you are actually engaged in something challenging.

But I do think it would be nice to have the game teach snaking to players somewhere, like in a special tutorial after the player beats the normal Story Mode. This would make it easier for people who appreciate it to learn about it and I think after beating Story Mode many people will probably be ready for the next big step in Super Tux Kart racing.

Also, that few other kart racing games feature snaking is a reason to keep it in as it means it helps differentiate Super Tux Kart from the rest. It even sets it apart from Mario Kart DS as snaking there works differently.

**Comment by Alayan-stk-2** [comment]
> The best way to make a game fun for both is probably to add a ladder system with something like ELO so that casual players can have fun low on the ladder against other casual players in matches where snaking does not occur and competitive players can have fun high on the ladder against other competitive players in matches where snaking does occur. Of course, this does require there be enough players of both groups to work well.

Yes, trying to match new players with other players that are not too strong to make casual online multiplayer more enjoyable for them is a desirable goal. We've got some ideas of improvements that could make it easier to match players with others of comparable skill, but at the same time growing the online playerbase will be a challenge.

> But I do think it would be nice to have the game teach snaking to players somewhere, like in a special tutorial after the player beats the normal Story Mode. This would make it easier for people who appreciate it to learn about it and I think after beating Story Mode many people will probably be ready for the next big step in Super Tux Kart racing.

"Skidding challenges" for the Story Mode are planned for STK 2.0. Basically time-trial challenges, but you also have to do a minimum number of drifts over the course of the race. The player wouldn't have to master doing them in all situations to complete the challenge, but they would have to engage with the mechanic rather than ignore it completely.

> It even sets it apart from Mario Kart DS as snaking there works differently.

It's different in the kart movement, and it's also much less taxing on the fingers to execute.
