### ISSUE TITLE
Every user data is lost when upgrade STK with Ubuntu

### ISSUE THREAD

**Issue by Flaburgan** [supertuxkart/stk-code#2496]
Each new version of Ubuntu brings a new version of STK, and each time I upgrade I loose all my won tracks, high score... The user profile is not upgraded. Does anybody know why, and how I can fix that?

**Comment by qwertychouskie** [comment]
Just a guess, but probably on purpose, as tracks are changed and switched out with each version, e.g. "Oliver's Math Class" was made longer in STK 0.9.1.

**Comment by Flaburgan** [comment]
Wow, no more launcher in the side? Such a shame, I found this track perfect. Anyway, I don't see why the whole user profile has to be erased, I understand that new track can't be already won, but custom race, score and time...

**Comment by auriamg** [comment]
In the case of 0.8 to 0.9, it's also because we had major changes to the engine, and the two versions are just not compatible in general. Also, keeping highscores would make very little sense because in addition to some tracks changing, kart physics also changed, so old version and new version times just can't be fairly compared

**Comment by qwertychouskie** [comment]
Can this be closed as invalid then?  One thing I would like to see for 0.9.2 though is to have the path for such files changed from `~/home/qwerty/.config/supertuxkart/0.8.2/` to `~/home/qwerty/.config/supertuxkart/0.9.2/` so that Supertuxkart can be reverted on the system or multiple versions installed without issues, or having the data stay in place after an upgrade.  For example, the upgrade from 0.9 to 0.9.1 kept my best times for "Oliver's math class", even though the track was lengthened.

**Comment by auriamg** [comment]
Closing as invalid

Indeed we do plan to rename the folder when we make breaking changes. The math class one is something we forgot, it's a bit unfortunate but probably not worth reverting all settings just for that?
