### ISSUE TITLE
Taking screenshot in fullscreen gives black image

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2537]
STK 0.9.2 on Windows 7.

If i press PrtSc to take a screenshot when STK is running in fullscreen and insert the image in a image editor i just get a totally black image in correct size.

Running in window mode i can take a screenshot just fine.

**Comment by auriamg** [comment]
I can't reproduce this issue on my computer

Just to clarify, when you press PrintScreen, the screenshot is saved in %appdata%\supertuxkart\0.8.2\screenshots , the file there is invalid?

**Comment by scootergrisen** [comment]
I do have the screenshot at %appdata%\supertuxkart\0.8.2 and they look correct (not black)
I did not know they where saved there.

I was trying to capture the screen like i do with other programs. Press PrtSc in Windows to capture the screen to clipboard and then paste in a image program.

I can do it and the pasted image is in correct resolution, but all black.

**Comment by auriamg** [comment]
The screenshot in the 0.8.2 folder is the STK-implemented functionality.

The other functionality (print to clipboard) you are trying to use is handled by windows, not by STK. This may be a windows limitation, not an STK limitation. In any case since we do offer an official way to take screenshots, there is no major issue here and we have no interest in trying to debug Windows' native screenshot tool.
