### ISSUE TITLE
I see "Error downloading news"

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2546]
STK 0.9.2 on Windows 7.

When first starting STK i see this text scroll at the bottom of the screen.

    Error downloading news: 'Could not resolve host name'.

I don't like when software tries to make connections and download stuff without my knowledge.

It gives the impression that STK needs a network connection to work well.

**Comment by scootergrisen** [comment]
![stk4](https://cloud.githubusercontent.com/assets/1836590/16540485/b4b3d718-4066-11e6-894b-a585e03cccb2.png)

**Comment by auriamg** [comment]
But was it a case that you didn't have a connection to the internet, or another issue?

"I don't like when software tries to make connections and download stuff without my knowledge.", we ask first, there is a popup asking permission first (I know you've seen this popup because you've created tickets about it ;) )

**Comment by scootergrisen** [comment]
I was not connected to internet.

You mean the dialog about submitting hardware statistics? I think i choose No on that one.
So are you saying if i choose No that i should not get the "Error downloading news: 'Could not resolve host name'." message?

**Comment by auriamg** [comment]
The checkbox I was referring to is called "Connect to the Internet" in the options, if that is disabled then STK should not connect at all to the internet.

Closing this ticket because there actually is no bug here, STK tried to download news but couldn't reach the server and thus displayed an error message, no problem here
