### ISSUE TITLE
Improve the first dialog the users see (about submitting hardware statistics)

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2547]
I might have reported this problem before but i can't find it so here we go again just to make sure.

I download STK 0.9.2 (not using apt-get) on Debian Jessie and first time i run STK i get this long message about STK wants to connect to internet and send hardware statistics and stuff and there is a Yes and No button on the bottom.

But the question is hidden in the middle of the long message so its really not a nice welcome when this is the first time you get when you run STK for the first time.

Would be must better to have to question at the bottom just before the Yes and No buttons on a line of its own.

The URL is not clickable.

Generally lacks some newlines.

The Yes and No button could be places horizontal.

Perhaps add a close button or a X to the top right to close the dialog for users that do not want to read the text and make a decision.

**Comment by Benau** [comment]
You suggested before:
https://github.com/supertuxkart/stk-code/issues/2465

**Comment by scootergrisen** [comment]
So now both are closed... so how can i report a bug about it if they keep getting closed?

**Comment by scootergrisen** [comment]
What happended to the image i uploaded?
Are images removed when the issue is closed?

**Comment by auriamg** [comment]
@scootergrisen , your efforts are appreciated, but this is a bug tracker designed to report **bugs**, for instances crashes, errors, etc. "I think this dialog is not pretty", while valuable information, definitely does not constitute a bug.

As explained the previous time you submitted this, some things (like clickable URLs) are not doable due to limitations in our engine.

Generally speaking, this dialog could maybe be slighyly better (a lot of our GUI could be better, we are aware).  This might eventually done as part of a GUI overhaul but for the moment with our efforts on networking we do not have time to spend on such minor improvements, and the current GUI is working as expected, just not as pretty as you'd like

**Comment by scootergrisen** [comment]
The reason why i write about this specific dialog is because it is the first thing the user see right after the LOADING screen so i think so for me its not just any dialog, its a dialog that all the new users see the first time they run the game and that is why i think its a good idea to make it better so users have a nice experience with starting the game for the first time without having to read alot of text and make decisions, but can focus on having fun playing the game.
