### ISSUE TITLE
Outdated Tux blend file in media repo

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2550]
We don't have the latest version of the tux kart in the media repo

**Comment by Benau** [comment]
http://forum.freegamedev.net/viewtopic.php?f=18&t=6220

Seems no blend provided at the first place :/

**Comment by Benau** [comment]
Media repo updated, but some problems:

I don't know if we wanna keep old tux, so i renamed it old_old_tux, as already a old_tux there

PSD file from the zip can't all be uploaded. Not sure if because of its size(one is 25m)
Failed with:
```
傳送檔案資料.svn: E000013: 送交失敗 (細節隨附):
svn: E000013: Can't open file '/svn/p/supertuxkart/code/db/transactions/16719-d79.txn/next-ids': Permission denied
```

Do we really need them?

And here's the link for the zip:
https://app.box.com/s/6pf4o1kis6sow4ttpkwmyj38risr1k85

**Comment by Benau** [comment]
removed old*tux*, XZed the PSDs
