### ISSUE TITLE
Show keep resolution right after change

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2553]
If i change the resolution in STK i have to wait for all the character icons to load before i get the... do you want to keep this resolution Yes No...

I suggest showing the dialog before, so you can quicker answer Yes or No instead of having to wait.

**Comment by Splamy** [comment]
That would defeat the purpose of this dialog. It is there in case the screen stays black or has any other loading problems to revert automatically to the old settings.

**Comment by auriamg** [comment]
As Splamy mentionned. Another better idea though would be to be able to change resolution without having to reload everything. This is not possible in the current engine however. I'm closing this ticket since it's not feasible / defeats the purpose. If you wish you can open another ticket about chagning resolution without reloading, however it would be unlikely to be worked on anytime soon since that's pretty hard to do
