### ISSUE TITLE
GLES does not work on RPi

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2590]
```
[ 35%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COctreeSceneNode.cpp.o
[ 35%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COctreeTriangleSelector.cpp.o
[ 35%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COGLES2Driver.cpp.o
In file included from /tmp/stk-code-master/lib/irrlicht/source/Irrlicht/COGLES2Driver.cpp:8:0:
/tmp/stk-code-master/lib/irrlicht/source/Irrlicht/COGLES2Driver.h:37:29: fatal error: EGL/eglplatform.h: No such file or directory
 #include <EGL/eglplatform.h>
                             ^
compilation terminated.
lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:1641: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COGLES2Driver.cpp.o' failed
make[2]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COGLES2Driver.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
CMakeFiles/Makefile2:290: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/all' failed
make[1]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/all] Error 2
make[1]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/tmp/stk-code-master/BUILDDIR'
```

**Comment by deveee** [comment]
Try to install libegl-mesa-dev and libgles2-mesa-dev

I wanted to try to run it on rpi, but I didn't have a time yet.

I'm not 100% sure if OpenGL ES is enough to have 3d acceleration on
raspberry. It works for me with combination GLES + DirectFB for other
games, but I never checked GLES + Xorg. Maybe it would require some
additional work to use DirectFB in STK.

And anyway rpi has only OpenGL ES 2.0 (at least rpi2 with proprietary
drivers, I didn't check rpi3 with mesa vc4), so it will use only fixed
pipeline.

But it would be nice if you could make some tests :)

W dniu niedziela, 31 lipca 2016 qwertychouskie <notifications@github.com>
napisał(a):
> [ 35%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COctreeSceneNode.cpp.o
> [ 35%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COctreeTriangleSelector.cpp.o
> [ 35%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COGLES2Driver.cpp.o
> In file included from
/tmp/stk-code-master/lib/irrlicht/source/Irrlicht/COGLES2Driver.cpp:8:0:
> /tmp/stk-code-master/lib/irrlicht/source/Irrlicht/COGLES2Driver.h:37:29:
fatal error: EGL/eglplatform.h: No such file or directory
> #include <EGL/eglplatform.h>
> ^
> compilation terminated.
> lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:1641: recipe for
target
'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COGLES2Driver.cpp.o'
failed
> make[2]: ***
[lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COGLES2Driver.cpp.o]
Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
> CMakeFiles/Makefile2:290: recipe for target
'lib/irrlicht/CMakeFiles/stkirrlicht.dir/all' failed

**Comment by qwertychouskie** [comment]
```
[ 38%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleGravityAffector.cpp.o
[ 39%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleMeshEmitter.cpp.o
[ 39%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticlePointEmitter.cpp.o
[ 39%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRingEmitter.cpp.o
[ 39%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRotationAffector.cpp.o
In file included from /tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CParticleRingEmitter.cpp:7:0:
/tmp/stk-code-master/lib/irrlicht/include/IAttributes.h:19:24: fatal error: quaternion.h: No such file or directory
compilation terminated.
In file included from /tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CParticleRotationAffector.cpp:5:0:
/tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CParticleRotationAffector.h:8:39: fatal error: IParticleRotationAffector.h: No such file or directory
 #include "IParticleRotationAffector.h"
                                       ^
compilation terminated.
lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:2193: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRotationAffector.cpp.o' failed
make[2]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRotationAffector.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
The bug is not reproducible, so it is likely a hardware or OS problem.
lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:2170: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRingEmitter.cpp.o' failed
make[2]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRingEmitter.cpp.o] Error 1
make[2]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
CMakeFiles/Makefile2:290: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/all' failed
make[1]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/all] Error 2
make[1]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/tmp/stk-code-master/BUILDDIR'
```
Using open-source VC4 mesa driver (by enabling the "Experimental OpenGL driver" in raspi-config, compiling in GLES mode (-DUSE_GLES2=1).

**Comment by deveee** [comment]
These errors look very strange for me. It complains that quaternion.h is
missing, but it doesn't complain for any other include from this directory,
for example matrix4.h which is included a line before in this file. All
these files are available in lib/irrlicht/include. Also
IParticleRotationAffector.h is available there.

I'm also not sure what you mean by saying that this bug is not
reproducible? Was you eventually able to compile it?

It's just an idea, but is /tmp partition on raspberry pi large enough to
compile STK? Some systems use tmpfs by default and /tmp uses 10% of RAM
memory or something similar.

W dniu niedziela, 31 lipca 2016 qwertychouskie <notifications@github.com>
napisał(a):
> [ 38%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleGravityAffector.cpp.o
> [ 39%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleMeshEmitter.cpp.o
> [ 39%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticlePointEmitter.cpp.o
> [ 39%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRingEmitter.cpp.o
> [ 39%] Building CXX object
lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRotationAffector.cpp.o
> In file included from
/tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CParticleRingEmitter.cpp:7:0:
> /tmp/stk-code-master/lib/irrlicht/include/IAttributes.h:19:24: fatal
error: quaternion.h: No such file or directory
> compilation terminated.
> In file included from
/tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CParticleRotationAffector.cpp:5:0:
>
/tmp/stk-code-master/lib/irrlicht/source/Irrlicht/CParticleRotationAffector.h:8:39:
fatal error: IParticleRotationAffector.h: No such file or directory
> #include "IParticleRotationAffector.h"
> ^
> compilation terminated.
> lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:2193: recipe for
target
'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRotationAffector.cpp.o'
failed
> make[2]: ***
[lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRotationAffector.cpp.o]
Error 1
> make[2]: *** Waiting for unfinished jobs....
> The bug is not reproducible, so it is likely a hardware or OS problem.
> lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:2170: recipe for
target
'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRingEmitter.cpp.o'
failed
> make[2]: ***
[lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CParticleRingEmitter.cpp.o]
Error 1
> make[2]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
> CMakeFiles/Makefile2:290: recipe for target
'lib/irrlicht/CMakeFiles/stkirrlicht.dir/all' failed
> make[1]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/all] Error 2
> make[1]: Leaving directory '/tmp/stk-code-master/BUILDDIR'
> Makefile:117: recipe for target 'all' failed
> make: *** [all] Error 2
> make: Leaving directory '/tmp/stk-code-master/BUILDDIR'
>
> Using open-source VC4 mesa driver (by enabling the "Experimental OpenGL
driver" in raspi-config, compiling in GLES mode (-DUSE_GLES2=1).

**Comment by qwertychouskie** [comment]
I didn't say it was not reproducible, the make command did.

**Comment by deveee** [comment]
Maybe try to run standard compilation (without GLES) to see if this issue
is related to GLES.




W dniu niedziela, 31 lipca 2016 qwertychouskie <notifications@github.com>
napisał(a):

**Comment by qwertychouskie** [comment]
OK, I figured out the issue, my compile script can't be in `/etc/cron.hourly/` as compilation takes more than an hour, and clearing out the old files is one of the first things the script does.

**Comment by Benau** [comment]
So can I close this?

**Comment by qwertychouskie** [comment]
This can be closed, but there is probably another issue coming soon related to getting hardware acceleration to work.

**Comment by deveee** [comment]
@qwertychouskie Could you check if current git version works on Raspberry Pi? It should work, but I'm not sure if we have to set ForceLegacyDevice in graphics restrictions. The rpi GPU supports only OpenGL ES 2.0, but I remember that it was reporting GLES 3.0 for me... maybe it was just software rendering.
