### ISSUE TITLE
Fonts do not render properly in Windows

### ISSUE THREAD

**Issue by ScttB** [supertuxkart/stk-code#2596]
<img src="http://img.ctrlv.in/img/16/08/08/57a8fcc3cbe8f.png">

I don't have any information that could help you fix this, though.

It is obviously broken.

**Comment by Arthur-D** [comment]
Should be fixed already in the development version.

**Comment by qwertychouskie** [comment]
That is the "Outdated Drivers" dialog, try updating your drivers.

**Comment by ScttB** [comment]
@qwertychouskie Display Drivers? Do I need DirectX or something? Because I have the latest display drivers for my ThinkPad T410.

**Comment by qwertychouskie** [comment]
Download the drivers directly from the Intel site, computer manufacturers usually are bad about keeping updated drivers on their site.  http://www.intel.com/support/detect.htm?iid=dc_iduu

BTW, this is what the dialog should look like: ![img](http://i.imgur.com/IO0qIHY.png)

Also, you almost certainly will not be able to use the advanced pipeline with 1st-gen Intel HD Graphics, I can hardly use it on my 2nd-gen.  You may want to use a computer with a more powerful graphics card, but as a minimum, turn the advanced pipeline off in the settings, otherwise you probably will not get a playable framerate.

**Comment by ScttB** [comment]
@qwertychouskie I have OGL 2 installed. so i might have to manually install OGL 3.x.
no idea if the builtin graphics even support it but it's worth a try since my freind's linux computer just won't start it up. (white screen, pc almost locks up, and pc is probably crap)

**Comment by ScttB** [comment]
@qwertychouskie also yes it's possible to manually install OGL, i had to do it before since my graphics driver wouldn't install it for me a long time ago

**Comment by qwertychouskie** [comment]
First, try using the link to automatically update the drivers, the newest drivers should have OpenGL 3.3 built-in.  If that doesn't work, you may have to dual-boot Linux, as the Linux drivers support the first-gen graphics better.

See https://software.intel.com/en-us/forums/developing-games-and-graphics-on-intel/topic/281262

**Comment by deveee** [comment]
We certainly should do something with it because this problem is very common for ironlake graphics cards. 

Could you try to set ```force_legacy_device parameter``` to "true" in config.xml file? It can be found in ```%appdata%\supertuxkart\0.8.2```. It's just an idea, but maybe it creates OpenGL 3.1 context even if it doesn't really support it.

**Comment by qwertychouskie** [comment]
If it was creating an OpenGL 3.1 context, that dialog shouldn't exist though...

**Comment by deveee** [comment]
@qwertychouskie Old drivers sometimes do strange things. For example there is one radeon drivers version that reports that it supports OpenGL 3.1, but it supports only GLSL 1.3. The GLSL 1.4 support is guaranteed by OpenGL 3.1 and we require it in STK. 

Maybe we have similar situation with intel ironlake. It has partially done OpenGL 3.1 support, so it was able to create GL 3.1 context, but it reports only OpenGL 2.1, so we assume in STK that lagacy context has been created (and we display warning message). I don't have better idea why legacy pipeline doesn't work for these graphics cards.

**Comment by ScttB** [comment]
@deveee it worked yay

**Comment by deveee** [comment]
Ok, it should be fixed in these commits: https://github.com/supertuxkart/stk-code/commit/c7d970b7455c5545c81f1f942e8d802f31c50835 https://github.com/supertuxkart/stk-code/commit/a001505abd2b2a49acdeced43501a4d26c2833d4

I re-create the OpenGL context with ForceLegacyDevice parameter when I detect buggy driver.

**Comment by ScttB** [comment]
@deveee Has it been compiled for Windows yet

**Comment by Benau** [comment]
No, you will need to wait for next release
