### ISSUE TITLE
Improve STK's Antarctica engine performance

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2600]
When turning on advanced pipeline without changing any other settings the FPS gets reduced from 100 to 35 - 20.Enabling more affects makes old levels (like the Northern Resort) still have playable frame rates of around 25 - 20 but newer levels like Cocoa Temple and Paridiso Island get around 12 - 17 FPS.

Could this be a limitation of hardware (3 year old laptop with discrete-class graphics) or is STK's new Antarctica Engine un-optimized 

HP Pavilion g7 2269wm with AMD A8-4500M and Radeon HD 7640G

**Comment by qwertychouskie** [comment]
Part of this could be related to the fact that you are not using Compute Shaders, could you try with the open-source driver (and revert the manual changes to `graphics_restrictions.xml`), and see if it makes a difference?

**Comment by SuicSoft** [comment]
@qwertychouskie Uninstalling FGLRX makes STK say that my drivers are too old and show a black screen when settings a graphics setting of 3 or higher.I have re-enabled the compute shader

Also other games are now playing choppy.Should I try the AMD Catalyst beta driver or RadeonSI

**Comment by Benau** [comment]
RadeonSI

**Comment by Benau** [comment]
Also seems that radeonsi doesn't support compute shader (at least for my card)

**Comment by SuicSoft** [comment]
@Benau How can I install it on 14.04 ?

**Comment by auriamg** [comment]
It is known that the antarctica engine is indeed not perfect and performance could probably be improved a little.

However, according to http://www.game-debate.com/hardware/?gid=1024&graphics=Radeon%20HD%207640G, the Radeon HD 7640G GPU is not very powerful (it's rated as being not even close to be able to run modern games properly). So while it is true that we could improve antarctica a bit, it is very unlikely that this GPU will ever be able to run STK smoothly using the shader pipeline. This is why we allow disabling the shader pipeline however. So bottom line, if you have a gaming PC you can run STK with the advanced pipeline, if otherwise you have a non-gaming PC like yours then indeed you will need to run it without the advanced pipeline

**Comment by SuicSoft** [comment]
I updated the drivers and turned off ambient and now my FPS is always above 25 with an average of 30.

**Comment by auriamg** [comment]
Glad to know you could get it to work a bit better!

**Comment by SuicSoft** [comment]
Also now if I enable advanced pipeline without any other settings I get 60 - 70 FPS (VSync off).So I think that the old drivers were the ones causing all the lag

**Comment by SuicSoft** [comment]
@auriamg STK has improved a lot in performance since then.Now at those same settings I get close to 60 FPS and at ultra I get 20 FPS
