### ISSUE TITLE
glClientWaitSync bug on intel hd3000 windows

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2606]
The ce38df26 commit triggers a bug on intel hd3000 windows, that part should be reverted or improved

**Comment by deveee** [comment]
Just note that it is caused by this modification:
```
     while (reason != GL_ALREADY_SIGNALED)
     {
         if (reason == GL_WAIT_FAILED) break;
-        StkTime::sleep(1);
-        reason = glClientWaitSync(m_sync, GL_SYNC_FLUSH_COMMANDS_BIT, 0);
+        reason = glClientWaitSync(m_sync, GL_SYNC_FLUSH_COMMANDS_BIT, 1000000);
     }
     glDeleteSync(m_sync);
     PROFILER_POP_CPU_MARKER();
```

This modification gives 2-3% additional fps on my Intel HD4000 on linux.

I suppose that the hang is caused by infinite loop, because glClientWaitSync can return GL_ALREADY_SIGNALED, GL_TIMEOUT_EXPIRED, GL_CONDITION_SATISFIED, GL_WAIT_FAILED, but we break the loop only when the result is GL_ALREADY_SIGNALED or GL_WAIT_FAILED.

I handled the GL_CONDITION_SATISFIED in this commit: https://github.com/supertuxkart/stk-code/commit/150e40e4e8413b775cceca79ca795f4283dff5c7 but still it is possible that some buggy drivers will return infinite GL_TIMEOUT_EXPIRED

cc: @robclark

**Comment by auriamg** [comment]
Thanks, that seems to correctly solve the issue I was experiencing
