### ISSUE TITLE
Fix redirect from old site to new one

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2629]
When you click on a link that hasn't been updated for the new domain name (which are most links across the web), e.g. http://supertuxkart.sourceforge.net/Download, it redirects to the main page of the new site, instead of the specific page.

**Comment by auriamg** [comment]
that would need quite a bit of work as the old website and new websites don't always have the same pages. someone would need to build some kind of mapping table. is it worth it? probably not

So if someone contributes a fix we'll accept it but I'm closing this as a task since it's only a minor annoyance and not something that we need to fix

**Comment by qwertychouskie** [comment]
Although a fix for all pages would be to complicated, maybe at least fix it for the main pages, e.g. FAQ, Download, etc.

**Comment by konstin** [comment]
We could certainly do that, but it wouldn't be very useful as the biggest part of the users - about two thirds - is redirected from the main page anyway.
