### ISSUE TITLE
Lines across track with shadows enabled

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2640]
### System Informanation (HP Pavilion g7 2269wm) :
- CPU : AMD A8-4500M
- GPU : AMD Radeon HD 7640G discrete-class graphics (using default drivers)
- RAM : 6GB 1600mhz DDR3
- OS : elementary OS Loki (Liqourix kernel 4.7)

If shadows are enabled in STK I get these lines across the track.

![scotland-2016 09 24_14 52 54](https://cloud.githubusercontent.com/assets/13938848/18807530/5d7ce104-8267-11e6-8af7-5936418af92b.png)

Happens on both git and 0.9.2 versions.

**Comment by deveee** [comment]
This is not really a bug, but our shadows implementation works in this way. If you want to have better shadows, you can enable "enable_esm" parameter in config.xml, but it is slower. You can also increase shadows resolution so that these lines will be less visible.

**Comment by SuicSoft** [comment]
@deveee Maybe we should make a new shadows implementation which doesn't have this (if this is possible with being negative on performance)

**Comment by deveee** [comment]
If you can do it, then why not :)

**Comment by SuicSoft** [comment]
@devee Ok , maybe possible for me to replace it with a better implementation ;) (btw , which file is the source for the shadow code located)

**Comment by deveee** [comment]
This is the sunlightshadow.frag shader.

Actually I was experimenting with this shader some time ago and I solved it with this patch:
```
diff --git a/data/shaders/sunlightshadow.frag b/data/shaders/sunlightshadow.frag
index df86d22..4b2a052 100644
--- a/data/shaders/sunlightshadow.frag
+++ b/data/shaders/sunlightshadow.frag
@@ -35,7 +35,7 @@ float getShadowFactor(vec3 pos, int index)
     for (float i = -1.; i <= 1.; i += 1.)
     {
         for (float j = -1.; j <= 1.; j += 1.)
-            result += texture(shadowtex, vec4(shadowtexcoord + vec2(i,j) / shadow_res, float(index), d));
+            result += texture(shadowtex, vec4(shadowtexcoord + (vec2(i,j) + 0.5) / shadow_res, float(index), d));
     }
 
     return result / 9.;
```
But this is an ugly hack which IMO doesn't have a sense. This loop is used for blur effect and vec2(i,j)  should be -1.0, 0.0 and 1.0 so that we use neighboring pixels for computations.

**Comment by auriamg** [comment]
@deveee do you understand why this hack works?

**Comment by deveee** [comment]
@auriamg I didn't find the reason and I also think that this line was originally written properly. That's why I didn't commit this modification.

It's better shown when we will write it in this way:
```result += textureOffset(shadowtex, vec4(shadowtexcoord, float(index), d), ivec2(i,j));```
The last parameter is an offset, and we just get 9 neighbouring pixels/fragments and use an average value to get blur effect on the edges of shadows.

It looks that y offset for texture coordinates cannot have nagative values for some reason, which looks very strange for me (some neighbouring pixels are broken??).

Anyway the real reason is unknown atm.

**Comment by SuicSoft** [comment]
@deveee 

> Actually I was experimenting with this shader some time ago and I solved it with this patch:

I tried that patch and it results in the lines being smaller but still quite visible

**Comment by SuicSoft** [comment]
@deveee 

> Actually I was experimenting with this shader some time ago and I solved it with this patch:

Applying this  patch seems to work and doesn't affect performance.

**Comment by deveee** [comment]
@SuicSoft Regarding to performance, how do you want to multiply each element of two dimensional array without a loop inside a loop? :P

You can totally remove the blur effect and just use
```return texture(shadowtex, vec4(shadowtexcoord, float(index), d));```
but it doesn't look good.

**Comment by deveee** [comment]
Ok, I can at least confirm that there is indeed something wrong in code related to shadows effect.

When I move the shadow in X-axis (forwards and backwards) then everything is OK, so neighbouring pixels are also read properly. But when I move the texture in Y-axis (left and right) then it looks that it is more and more above/below ground. So it looks that the texture has slightly different orientation than whole rendered scene. Maybe a rounding error somewhere?

My previous workaround gives better result, because it moves the texture slightly to right and it begins to be slightly below ground, so that these lines are less visible, or in my case non-visible at all.

**Comment by qwertychouskie** [comment]
> @SuicSoft Regarding to performance, how do you want to multiply each element of two dimensional array without a loop inside a loop? :P

I don't know if this is useful or not, but you may want to take a look at http://nadeausoftware.com/articles/2012/06/c_c_tip_how_loop_through_multi_dimensional_arrays_quickly

**Comment by SuicSoft** [comment]
@deveee So if we cache the shadow map will we still need the loop inside loop ?

**Comment by SuicSoft** [comment]
@devee Why not merge that patch ?

**Comment by deveee** [comment]
I added the ugly hack with moving the shadow a little:
https://github.com/supertuxkart/stk-code/commit/5df2531a65529945ff897d0ea6f023e26525cada

The reason of this issue is probably something like this:
http://computergraphics.stackexchange.com/questions/2192/cause-of-shadow-acne
