### ISSUE TITLE
Arguments validation discussion

### ISSUE THREAD

**Issue by amtkhdkr** [supertuxkart/stk-code#2644]
One of the first options on the command line is -N , --no-start-screen
Inherently, I assume this switch has dependencies on --kart,--numkarts, --track, --laps and possibly few more
Not setting these arguments will cause STK to hang up severely, resolvable only by a hard reboot, so we definitely need an argument validation mechanism in place here.

Two approaches:
1. Set some sensible defaults for whatever option is not provided. For example, --numkarts could be 3 or 2 AI karts other than player kart, use the penguin kart by default, use the mathclass track by default -- you get the point
2. Fail immediately by complaining "Usage: This parameter requires setting x, y and z parameters etc" and exit with error code

Thoughts on this? Providing defaults could be nice to get the functionality running, but could also irk some people who don't like "magic" or defaults. Maybe some hybrid approach between approach1 and approach2 like documenting those defaults in the help string

**Comment by auriamg** [comment]
NumKarts could probably have a default (of 1? this would usually be used for testing tracks), I think the track should be required though. Any takers for a pull request?

**Comment by hiker** [comment]
I am reasonable certain that all parameters have a default (they are either stored in the config file, taken from track defaults (#laps), or set in stk). I just tried with my existing config and when doing a complete new start, and it all worked for me. Only thing I could think of is if you last played an addon track, and you removed it after. Could that be the case?

Otherwise, could you perhaps run this in gdb and see what exactly is going wrong for you and where? I would more likely suspect that there is an issue with the opengl code than anything related to -N

**Comment by nado** [comment]
Tested on master (https://github.com/supertuxkart/stk-code/commit/85e0fed9b71c7c5018493663814c05fc67e0518d) and couldnt reproduce.
`stk-code/build % ./bin/supertuxkart -N`

**Comment by amtkhdkr** [comment]
Cannot repro this anymore on current code, closing.
