### ISSUE TITLE
Using appveyor for windows CI

### ISSUE THREAD

**Issue by nado** [supertuxkart/stk-code#2649]
Hi,

I’m playing with appveyor config to build stk on it, it is currently working for x86 VisualStudio compiler.

Would stk-team be interested in using this service to continually test windows compilation and/or provide windows regular builds ?

You can see here the discussion I am having with their twitter CM about cache configuration https://twitter.com/n4d0/status/783707739516203008
The dependencies and the assets should be cached but it doesnt work atm, we can avoid the assets download but it would be nice for providing official builds to still have them : if the caching works, its ~5 minutes the first time and should be far less after.

[My appveyor history](https://ci.appveyor.com/project/nado/stk-code)
[Appveyor.yml](https://github.com/nado/stk-code/blob/test/appveyor/.appveyor.yml)

**Comment by qwertychouskie** [comment]
Now that it is working, will we see a PR soon?

**Comment by nado** [comment]
It’s not working 100%, caching of the assets doesnt work because its size is too high.
I haven’t tested anything much more than appveyor itself, I guess I’ll make a PR within one week or two.

**Comment by hiker** [comment]
TBH, I am not entirely sure that I would even want this. Reason is that because we are such a small team (4 coders) we are using a somewhat 'agile' model - i.e. apply updates to master before they are fully mature (so we are all testing all the time).
As a result of this our master is sometimes unstable, so if we would have many people trying to help us by testing daily builds, we would just get many more bug reports for things that we might be aware of (which means we need time to answer them, ...). And we might give a rather bad impression of the state STK is in.
Yes, if we had a group of people testing branches, another group to do a code review before merging the changes in, ... but we don't.

Being able to trigger a full installer build automatically might be useful (to allow us to easily do alpha releases), though the overhead of a release is more the testing, ticket updates, ... - building is not that much overhead.

**Comment by qwertychouskie** [comment]
But what if, for example, @samuncle wanted to easily get the latest master (with walldriving) to work on the "newton" track?

**Comment by Benau** [comment]
I think everyone who wants to contribute to STK should know how to compile STK themselves

**Comment by nado** [comment]
Alright, and what about Win compilation testing for linux/mac users ? No releasing config, only compile and report errors/warning. Would it be interesting ?

**Comment by Benau** [comment]
We don't even have time/pto maintain a coverity build

**Comment by qwertychouskie** [comment]
Compiling on Windows is a pain though, need VS, etc.  Although it is not necessary to provide Windows builds, it would make testing new features/fixes easier.  And even if builds are not provided, I don't see any harm in having Appveyor checking whether compilation on Windows works or not, since the service is free, and @nado has done most of the work already anyways.

**Comment by hiker** [comment]
@nado I was already told on irc that I sounded a bit too negative, my apologies. Certainly CI would be great to have.

**Comment by nado** [comment]
@hiker none needed, I did not think about the added workload that would bring a daily build :) I’ll make a PR soon then, with the first x86 VS build. (mingw is planned later ;) )

**Comment by auriamg** [comment]
PR merged, Hiker also created an official STK account on appveyor

**Comment by hiker** [comment]
(copied from the pull request)
First build successful - great!!

I wonder if it is possible to get irc notifications? Also it appears that notifications are sent to the email address set for the account (in this case our official stk email address). Is it possible to send the notifications to the committer instead?

**Comment by hiker** [comment]
OK, apparently the committer does get an email if the compile fails, so that's working. Only the IRC notifications would be great to add then.

**Comment by nado** [comment]
OK, I’ll add them during the week, they weren’t added in the beginning to avoid spammy fail results during configuration.

**Comment by nado** [comment]
Closing since everything is merged, thank you.
