### ISSUE TITLE
Add option for "scale_rtts_factor" in GUI

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2662]
The code exists, might as well put it to good use...

**Comment by Benau** [comment]
```
+        case 0:
 +            UserConfigParams::m_scale_rtts_factor = 0.8f;
 +            UserConfigParams::m_trilinear = false;
 +            UserConfigParams::m_anisotropic = 0;
 +            UserConfigParams::m_high_definition_textures = 0x02;
 +            UserConfigParams::m_hq_mipmap = false;
 +            break;
 +        case 1:
 +            UserConfigParams::m_scale_rtts_factor = 1.0f;
 +            UserConfigParams::m_trilinear = true;
 +            UserConfigParams::m_anisotropic = 2;
 +            UserConfigParams::m_high_definition_textures = 0x02;
 +            UserConfigParams::m_hq_mipmap = false;
 +            break;
 +        case 2:
 +            UserConfigParams::m_scale_rtts_factor = 1.0f;
 +            UserConfigParams::m_trilinear = true;
 +            UserConfigParams::m_anisotropic = 4;
 +            UserConfigParams::m_high_definition_textures = 0x03;
 +            UserConfigParams::m_hq_mipmap = false;
 +            break;
 +        case 3:
 +            UserConfigParams::m_scale_rtts_factor = 1.0f;
 +            UserConfigParams::m_trilinear = true;
 +            UserConfigParams::m_anisotropic = 16;
 +            UserConfigParams::m_high_definition_textures = 0x03;
 +            UserConfigParams::m_hq_mipmap = true;
 +            break;
```
@deveee do you like this remix, see https://github.com/supertuxkart/stk-code/commit/02c8c87d5dc889e52af66ce9d731a02ff4ea0199

**Comment by deveee** [comment]
I'm out of home in this week, so I'm not up to date with your recent work.

I'm fine with scale rtts = 0.8. I think that values lower than 0.75 look bad, so 0.8 is okay.

But we probably should remove
```bool force_rtt = UserConfigParams::m_scale_rtts_factor != 1.0f;```
from shader_based_renderer.cpp if we want to have it in options.

I added the force_rtt because I thought that it will be useful on android with disabled advanced lighting. But direct rendering works faster and scale rtts param must be too low to give some performance benefit. It also may be broken with opengl 3.x + disabled advanced lighting (image may be too dark/bright). And I don't remember if it works properly without rtts or if scale_rtts has to be set to 1.0 in this case.

Btw. The non-hd textures (or at least some of them) could be even smaller on low settings (256 works just fine except some skyboxes, track screenshots and maybe stk logo). Maybe add hd-texture=true param to materials.xml or something? Actually it could also depend on resolution. Currently we have the same max texture size on both 800x600 and 1920x1080.

**Comment by Benau** [comment]
@deveee now branch is merged, what do we do about this ticket?

**Comment by deveee** [comment]
I removed the force_rtt and don't set scale when advanced lighting is disabled, so now it should work fine.

Actually it would be nice to allow to set custom rtts scale, so that I could override it on android to lower value or even provide few different values in the place where we have resolutions list. But currently advanced lighting is too slow for android, so I don't really care. If it will be needed, we can add m_scale_rtts_enabled or something similar.
