### ISSUE TITLE
XR591, textures are missing

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2707]
![xr591-2016 12 29_22 11 05](https://cloud.githubusercontent.com/assets/4296971/21559201/cc09f0a4-ce15-11e6-88b0-efdb40511ef4.jpg)

Doesn't seem to happen for everyone. Benau can't reproduce

**Comment by SuicSoft** [comment]
I never saw this . Maybe you STK installation / source got corrupt somehow so trying re downloading / installing

**Comment by Benau** [comment]
Cannot reproduce in windows + linux too

Although I do crash when I fall into the green lava, because the texture of particle is inside track folder, see this: https://github.com/supertuxkart/stk-code/commit/caf9dbab0c0065ca3138878e349b463b5bf0c090

Now the track texture path is kept until track clean up, good for you?

**Comment by auriamg** [comment]
This was broken in b669382b930a8934a1acdccf26dd12358264c685
I suspect it happens because XR591 still has a second UV layer, that was previously used for lightmaps

**Comment by auriamg** [comment]
Fixed in SVN by removing the extra UV layer
