### ISSUE TITLE
Basketball doesn't hit immediately although it catches up

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#2735]
I have experienced a weird bug where the basketball doesn't hit as soon as he catches up with you but takes quite a while to hit you.

I have screencasted it. Relevant time frame: https://youtu.be/Anm0uo9pu3E?t=1m45s

Looks and feels quite weird.

**Comment by qwertychouskie** [comment]
Been meaning to report this... you beat me to it. :)  Also, sometimes I can avoid the ball long enough it gives up.

P.S. You should try SimpleScreenRecorder's OpenGL capture.  FPS similar to normal play.

**Comment by qwertychouskie** [comment]
In that video, the effect of the swatter was also delayed, another bug?

**Comment by deveee** [comment]
Just note that it happens for me quite often

**Comment by deveee** [comment]
One strange basketball behaviour is reproducible in this place:
![zrzut ekranu z 2017-08-17 22-01-28](https://user-images.githubusercontent.com/5108558/29431350-ebcad4e8-8397-11e7-8082-b702dd50c8bf.png)
though the reason may be different.

**Comment by deveee** [comment]
Basketball in hacienda does very strange things. It for example sometimes goes forwards, then backwards for a few seconds, and then forwards again. Or goes somewhere outside of the track (something like on the screenshot).

I noticed that ```ball_distance = getDistanceFromStart()``` sometimes gives wrong values (something around 600 at the beginning of track, so it's probably (total_track_length - real_ball_position). In this case target is lost and this may be the reason that basket ball doesn't hit the kart.

Though I don't know yet why basketball changes direction.

All other values seem to look reasonable...

**Comment by hiker** [comment]
Strange things are indeed happening, I am able to reproduce most of those issues, so I'll have a look.

**Comment by hiker** [comment]
I've seen various problems:
- in sandtrack the ball would sometimes be under the drivelines (which were too high there). Then the find track sector function would find a potentially quite distant different sector (which fulfills the height condition), and the ball would move towards that point - quite possibly backwards or sidewards. After one frame (since the ball is jumping) it would find the original track sector again and then move in the right direction again. Auria fixed the drivelines which solved that problem. 
- The ball was sometimes considered to be tunnel through a surface (which causes the ball to reset to the hit point, i.e. moving backwards). Reason was the maths: to determine the new height, it would subtract the previous height, and then add the new height. In some circumstances subtracting the previous height from the new point would result in the ball being under the track (since the ball was moved since the previous height was computed), and the new height added was not big enough to have a position on top of the track --> raycast would then return a collision, causing the tunnel behaviour. Basing the new height only on the hit point of the raycast down (to determine terrain) solves that problem (b97088c93363218e8dfb014e2359d323e9ed5bae).
- I found another bug in that the track sector detection is not using a somewhat higher ball point (to avoid the first problem in case that the drivelines are too high). Instead of fixing all the tracks (like auria did for sandtrack) a slightly higher position should be used (as is already used for terrain detection). But after the fix for the 2nd issue above I could not reproduce an incorrect track sector detection anymore, even in tracks that have drivelines that are too high (e.g. snowtuxpeak). I'll evaluate this bugfix a bit more before committing it.

**Comment by hiker** [comment]
Still a problem in hacienda ... back to the drawing board ;)

**Comment by hiker** [comment]
Turns out that the track sector detection bug is not actually a bug - if we would use a higher point, the distance to the track sectors can become too large, resulting in incorrect sectors. And that caused the hacienda bug.

At this stage I could not reproduce any serious issues anymore - when I artificially force the ball to be at road height (i.e. like rolling on the ground), there were a few instances where it was considered off road (because drivelines are too high), but that had no serious effects on the ball behaviour.
Please reopen if this should happen again (ideally with a screenshot on where).
