### ISSUE TITLE
Rain falls perpendicular to player, rather than actually falling downward

### ISSUE THREAD

**Issue by OzoneOne** [supertuxkart/stk-code#2779]
The rain effect seems to fall downward in relation to the player's rotation, rather than falling in the direction that is actually down. Thus, when driving on a sideways or upside-down track with rain enabled, the rain falls in unexpected directions.

**Comment by samuncle** [comment]
it would requires to have oriented particles (aka non billboard particle).

**Comment by stkAnon** [comment]
Old rain effect, IIRC, was five transparent cylinders layered around the camera with an animated rain texture on them. Then Google SOC before

**Comment by Benau** [comment]
![Screenshot from 2022-10-30 00-57-41](https://user-images.githubusercontent.com/3252341/198843823-270f9965-28bd-4283-ba03-ebbc4d460d4a.png)
![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)
Only gl3 (soon to be ![](https://cdn.lihkg.com/assets/faces/lm2/abomb.gif)) and ![](https://cdn.lihkg.com/assets/faces/cow/plan.gif) engine are supported, legacy drivers cannot because they are drawn without shaders
