### ISSUE TITLE
How should challenges work if overworld doesn't exist?

### ISSUE THREAD

**Issue by Danfun64** [supertuxkart/stk-code#2805]
Commit d4cecd5 allowed for the option to hide the story mode icon if the overworld levels aren't there. The problem with this is that without the overworld, there's no way to unlock stuff. Unless you propose a different way to unlock stuff without the overworld (like a list of all challenges) than everything should be unlocked by default without the overworld.

**Comment by deveee** [comment]
There is "everything_unlocked" parameter in config.xml, which is set to "true" by default on Android. No matter if overworld exists or not, this param is needed on Android because we can't include all tracks in the apk (google play has 100MB limit for apk and STK with all tracks is ~170MB).

Actually the main problem is what to do to make the apk smaller? We can decrease sounds quality even more, which gives additional 5MB. Some images should be IMO in jpg instead of png format, but it's not trivial to convert it automatically. Removing unused functions and other code optimizations doesn't help much.

**Comment by stkAnon** [comment]
Many games on Google Play provide only the most essential data (binary + ui) in your initial installation, then ask for storage permissions to download levels and other media the first time you run them. Could STK do something like this, similar to how addons are handled on the desktop versions?

**Comment by deveee** [comment]
Ideally we could have apk with 2-3 tracks and then "data small" and "data full" available in our addons manager. In this way we can make the apk smaller, we would provide an easy way to install data and also it would require only little changes in code. But I have no idea if our server is good enough to allow that big download packages (or if it supports packages and not just single karts/tracks).

Other applications that are written particularly for android usually use obb files. Single obb file can be up to 2 GB, so it's certainly enough. But it seems to be a solution only for play store. What if we'd like to share it on amazon, f-droid, our sourceforge website, manually compile etc? I also prefer to make the android port as close to the desktop version as possible, so that it will be easier to maintain. So that less android-specific code is better :)

Btw. are you okay with removing overworld from default apk? I think that it's better to remove overworld rather than other tracks to fit the 100MB limit.

**Comment by deveee** [comment]
After recent tweaks in generate_assets script it's not that big problem with the apk size anymore. Currently it's ~90MB and it will be even better when Benau will finish his space partitioning branch.

Also the original issue is IMO not a problem. If someone wants to remove overworld (which shouldn't happen in typical case), it's possible to set "everything_unlocked" parameter in config.xml. It's also possible to set it from command line:
https://github.com/supertuxkart/stk-code/commit/3dee6ce5dde7204d0a0fbfd17e1283d11438f68c
