### ISSUE TITLE
Palm tree branches are moving too fast cocoa temple/shifting sands/gran paradiso island

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2814]
Hi,  
     Palm trees branches are moving now but they move too fast. It seems that there is a thunderstorm :)
It can be seen in cocoa temple/shifting sands/gran paradiso island

Nice week end

**Comment by Benau** [comment]
Personally if asked me 
```
vec3 LightFactor = color.xyz * (scattering * 0.1) + getLightFactor(color.xyz, vec3(1.), specmap, emitmap);
```
That scattering is multiplied by 0.1 so basically it was doing some stupid and useless calculation, just do a * 0.05 or 0.1 and we can get rid of the above calculation and bind one less texture with almost the same color effect, @deveee good idea?

(I think the old calculation was done by old work, but newer fix to grass shader overrides it without knowing)

And you can try vec3 test = sin(windDir * (Position.x* 0.5)) * 0.5; instead of .y in vertex shader

**Comment by auriamg** [comment]
If someone wants to issue a pull request that slows down trees a little, I think that would be a good fix

**Comment by deveee** [comment]
It seems that the idea is that the wind strength depends on object height and that's why there is the Position.y? But it should move with higher strength and not faster, so maybe something like this?
```vec3 test = sin(windDir * (Position.y* 0.1)) * 1.;```
can be adjusted, just the idea...

The ```vec3 test = sin(windDir * (Position.x* 0.5)) * 0.5; ``` doesn't look good for grass in cocoa temple.

And when I set scattering = 0.5 I see no difference, so if we can bind one less texture, then I 100% agree.

**Comment by Benau** [comment]
@samuncle ok?

**Comment by Benau** [comment]
Assume yes
