### ISSUE TITLE
OpenGL 3 Not Working on Intel HD 3000 with Windows

### ISSUE THREAD

**Issue by MarkkusBoi** [supertuxkart/stk-code#2829]
OS: Windows 7 Professional (64 Bit)
GPU: Intel HD 3000

I have the latest graphics drivers and all of that jazz.

The game crashes upon loading a track when using the default OpenGL version. I've tried fiddling around with different configurations in the graphical settings, but the only way I've gotten the game to work was with forcing OpenGL 2 with `force_legacy_device="true"`in the config file.
Everything works in Ubuntu 16.10 with the latest mesa, built from source.

With OpenGL 2, there is actually lighting without using the Advanced Graphics Pipeline also.

**Comment by Benau** [comment]
0.9.2 or git?

**Comment by MarkkusBoi** [comment]
0.9.2

**Comment by deveee** [comment]
I suggest to test current git version, because a lot of things have been changed. If you can't compile it yourself, someone shared the windows build recently:
https://forum.freegamedev.net/viewtopic.php?f=17&t=7408&sid=786c1c5dac4b1f0f4b86487a4c46f51b

You can also post your stdout.log file. It can be found in ```%appdata%\supertuxkart\0.8.2```. Maybe it will say something...

**Comment by MarkkusBoi** [comment]
Thanks. I'll try it and get back to you with the results.

**Comment by MarkkusBoi** [comment]
STK failed to build, so I just used the version linked above. It worked fine with OpenGL 3.

**Comment by Benau** [comment]
good
