### ISSUE TITLE
Bomb going off in cannon problem

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2846]
If you have a bomb which goes off while you're travelling in a cannon you will fall down where it happened. So if it happens in Cornfield Crossing you won't be able to get up without backing all the way out (or rescuing multiple times).

**Comment by auriamg** [comment]
in debug builds it actually crashes due to an assert failure, as there are two animations at the same time

**Comment by hiker** [comment]
A few ideas:

1. - We stop the timer of the bomb during a cannon.
2. - You explode if you enter a cannon while having a bomb.
3. - When the bomb explodes, you are set back to the beginning of the cannon (previous track sector or so) - but how do we do this visually?
4. - You 'explode' during the cannon, but are still animated forward ... so no real punishment of bomb (unless you are still exploding when you arrive )
5. - we drop the bomb to the ground and it explodes there later??
I like 3), if someone comes up with a good visual idea ... explode up and move backwards on cannon??
None of the solutions is that ideal :(

**Comment by nado** [comment]
1. doesnt seem too hard and doesnt break current mechanics
2. seems too punitive and blocks any way to counter a bomb (item, touching another kart)
3. seems also really punitive but easier to understand and deal with, not a bad thing to spice things up
4. I would suggest to add some invincibility when in the cannon, giving a real possibility to use that mechanic to counter an explosion instead of a diminished punishment
5. would be like a bubble gum but with instant explosion ?

**Comment by qwertychouskie** [comment]
I like option 4 best.  Similar to how MarioKart does it: https://youtu.be/UUplEk4Qgok?t=2m8s

**Comment by Arthur-D** [comment]
I like option 1 since the cannon takes away other possibilities of getting rid of it, and we don't need to handle the explosion and reset.

**Comment by auriamg** [comment]
I implemented option 1 because it's by far the easiest in our current system.
