### ISSUE TITLE
GUI engine refactoring

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2887]
In messing with the GUI engine, I have found a lot of things that just don't make since.  Here are some suggestions to make it more logical and more maintainable:

General:
- [ ] SVGs should be a supported image type, it should render the SVGs to a texture the size need for the element then use that texture for the element.  This will help things like diagonal lines look sharp on all screen resolutions, and also reduce space used (thus reducing the size of the APK)

STKGUIs:
- [ ] Elements (`div`s, etc) should have a `background-image` property
- [ ] Buttons should have `image`, `image-focused`, and `image-deactivated` properties, as some buttons may want to look different than others
- [ ] Buttons should have a `focused` property that when set to true focuses that button when the screen is loaded (currently this is hardcoded in the various screens)
- [ ] Buttonbars should support `layout="vertical-row"`

Theming:
- [ ] Whenever an image is loaded, STK should check for that image in the skin folder, and if not there load the default.  Example: `<div background-image="online/menu_create_server.png" >` should first check `[current-theme-folder]/online/menu_create_server.png`, and if it does not exist, load `data/gui/online/menu_create_server.png`.  This will make themes much more powerful, and more logical (the background `background.jpg` is part of the theme but the bottom bar `bar.png` is hard coded?)  Optional: Using the same logic, let themes define their own STKGUI files.

These would greatly help a GUI redesign (of which multiple have been proposed: https://forum.freegamedev.net/download/file.php?id=10534&mode=view, https://jacobspctuneup.tk/gui.png)

**Comment by auriamg** [comment]
SVG cannot be rendered directly in a 3D engine, we'd need to rasterize it which is quite a bit of work and possibly slow, so not likely.

background-image: for what? we have a skin system that does what we want, we're not trying to make a complete HTML engine here.
Image buttons are already supported. Focused and deactivated images are automatic and we never had a need for a manual one. Again, the current system does what we want, we're not trying to build a complete html engine, we're just doing what we need. So far I have seen no sign that this is something we need.

A default-focus property : maybe. That's not a big deal since it basically saves us one like of code, but as a minor feature I guess why not.

Vertical button bars : maybe, we can already do that pretty easily by putting a bunch of buttons in a vertical div.

Putting background.jpg in common between themes : not a bad idea, not a big deal either though (the gain would be small, not sure the added code complexity is worth it)

**Comment by qwertychouskie** [comment]
Closing, if a completely new GUI is used the necessary code will inevitably be written anyways.
