### ISSUE TITLE
Nearing the OpenAL sources maximum count

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2921]
OpenAL, or some implementations of it, have a limitation of 256 sound sources. When playing with 20 karts, we're getting around 200-225 sound sources, so we're pretty close to the limit. We should probably investigate how to increate that limit, or reduce our usage, to avoid sound errors when lots is happening

Suggestion : we don't need one source per type of sound, per kart. A kart can play a collision sound, or a horn sound, or a goo sound, or a nitro sound, or many others.... Atm we create a source for _each_ type of sound. We could probably only create 2-3 sources per kart and attribute/switch them as needed, since we are unlikely to have more than 2-3 sounds per kart playing simultaneously

**Comment by hiker** [comment]
Auria suggested to share some of the sfx. E.g. instead of each kart having its own crash sound, have only (say) three crash sounds and share them. If really more than three crash sounds need to be played at the same time, only the three closest to the player (or a player) would be played. Karts would then only have engine sound, skid and nitro (and even some of them could be skipped).
Difficulty in implementation: keeping track of which kart is using which shared sfx (to allow the sfx to be updated with new location etc).

**Comment by qwertychouskie** [comment]
Turns out there is a way to increase the limit: https://github.com/kcat/openal-soft/issues/144#issuecomment-326712057

**Comment by auriamg** [comment]
@hiker See branch OpenAL_Sources for an implementation of my idea (which is a bit different from what you understood ;) ) It appears to work well, I just need to make it fully thread-safe. Does this approach seem ok to you?

**Comment by auriamg** [comment]
It should now be fully thread-safe. I removed 7 sound sources per kart, so when playing wit 20 karts that should be 140 fewer sources, taking us far below the limit. I think that's a good solution

**Comment by hiker** [comment]
Sounds all good - just one request: can we change the m_emitter/m_emitter1/m_emitter2 into a proper array? And maybe (not really related to this branch ... but kind of similar code ;)  ) the same for m_crash_sound* - together with renaming the crash*ogg to crash{0,1,2}.ogg would make the code more compact.

**Comment by auriamg** [comment]
Fix merged
