### ISSUE TITLE
render graphic on to the game

### ISSUE THREAD

**Issue by JasonJKi** [supertuxkart/stk-code#2936]
Hello, 

I'm trying to render white flash on to the screen during game. Is there a graphics animation function that does that?

Best,
Jason

**Comment by qwertychouskie** [comment]
You might look at the lightning code (mansion track).

**Comment by Arthur-D** [comment]
Please, use the mailing list, forum or IRC to ask questions. Github tickets
are mainly for bugs.

15. sep. 2017 12.20 a.m. skrev "QwertyChouskie" <notifications@github.com>:

You might look at the lightning code (mansion track).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/supertuxkart/stk-code/issues/2936#issuecomment-329624849>,
or mute the thread

**Comment by auriamg** [comment]
As Arthur said, github is not the right place to ask questions
