### ISSUE TITLE
Default nitro key + go left combination not working properly

### ISSUE THREAD

**Issue by Icemole** [supertuxkart/stk-code#2942]
The kart will not _nitro_ + _go left_ (together pressed) properly with the default _nitro_ binding (N). I tried both pressing _nitro_ and then _go left_, and _go left_ and then _nitro_. However, I changed the _nitro_ binding to (M) and (P) (tests), and the combination seemed to work fine.
I also tried binding, only to test if the (N) key worked properly, the _go left_ command to the (N) key, and it worked, so I think it's a specific problem of the combination of _nitro_ being bound to the (N) key and _go left_.

**Comment by auriamg** [comment]
Hi, check "Why don't some keyboard keys work when pressed simultaneously?" on https://supertuxkart.net/FAQ . This is most likely a physical limitation of your keyboard, most office keyboards do not support having many keys pressed at the same times. There is nothing we can do about that since this is a hardware limitation, alternatives are to try to find a different key binding that your keyboard reacts better to, get a gaming keyboard that doesn't have this limitation, or use a gamepad
