### ISSUE TITLE
Feature Request - Reverse Mode For Cornfield and Cocoa

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3010]
Are reverse modes planned to be implemented for Cocoa Temple and Cornfield Crossing?

**Comment by Benau** [comment]
You need 3 simple commits (backported)
69c86930e881efa78063be9995e657b6c85405fd
(to avoid zipper boost being ray-casted if not visible)
8ba0fd35691c29596be98c0c0e361756e02f3cca
(because cocoa use cobble stone texture (normal map))
628bc7ce50b9f90588195e35c8e1039204086d9e
(remove the light by reversing track)

Now update both media repo and stk-assets + export script, you can export the chocolate_reversable.blend with latest export script and see hows it works when reverse,
it use a cannon-height tricks for it, so it shoot a little higher when reverse, and the cannon won't be triggered when normal direction(jump pad is used instead), samuncle is fine for it

wanna finish the remaining pads in cocoa for 0.9.3 auria?

**Comment by Benau** [comment]
done

I suggest next time you use our forum for feature request

https://forum.freegamedev.net/viewforum.php?f=16

**Comment by psypherium** [comment]
I'm sorry you feel that way, i'll consider that next time. The way i phrased it was an attempt at being polite. It wouldn't have been merely a feature request if I had have said "selecting (reverse = all) in gp options plays some tracks forwards", that would have been a bug.
