### ISSUE TITLE
Make separate repository on Github for Blender add-on

### ISSUE THREAD

**Issue by Symbian9** [supertuxkart/stk-code#3025]
Please, make separate repository that will include code only of Blender addon
* [ ] https://github.com/supertuxkart/stk-blender

Here is current location of this addon
* https://sourceforge.net/p/supertuxkart/code/HEAD/tree/media/trunk/blender_26/

**Comment by Benau** [comment]
any good reason?

**Comment by Symbian9** [comment]
@Benau, it's impossible download latest code of addon separatly as single ZIP from SourceForge

If try `Download Snapshot` button on SourceForge it give me only full snapshot of `media` tree, where size of this `.tar.gz` is ~ 1.5 Gbytes (sic!)

If create separate repo for Blender add-on only, than there is easy way for get latest code from `master` as single ZIP.

Also, near all Blender add-ons' developers, that could help with development of this add-on, hosted on Github, and not use SourceForge anymore.

**Comment by auriamg** [comment]
@hiker Any opinion?

**Comment by MTres19** [comment]
My limited experience with 3D art for STK is that sooner or later you'll want the whole media repo anyway. If not to link library objects into your track, then at least for examples of how to do things in Blender, which is often too complex to describe clearly in documentation.

**Comment by Symbian9** [comment]
> sooner or later you'll want the whole media repo anyway

I want download Blender add-on & whole media pack separatly.

I won't download 1.5 Gbyte each time if I only need snapshot of latest Blender add-on code.

Current sitiation is abnormal for normal user/modder.

**Comment by MTres19** [comment]
@Symbian9 Just use `svn update`. It will only fetch the newly changed things. No need to download the entire repo again just to update the scripts.

RE the SourceForge scandal, I'm well aware of that. It happened 2.5 years ago and since then I haven't heard of anything bad from them. Also SF has reliably hosted STK's code and downloads for over a decade without anything serious happening that I know of.

**Comment by hiker** [comment]
First of all, if you frequently want to update the blender tools, I'd recommend to just use svn - you then have the options to just checkout the blender directory (or checkout all, and only update the blender directory). Afaik sourceforge does not offer a directory-only download (it's all or nothing).

Having said that, I don't object to using git for the blender part - but it means that there are then more instructions/repos people need to clone. Atm we can just say: download this repo, and you have everything. Then it will be: you need to download the media repo using svn from here, and the github version from here. Artists might need to install two different tools, there are two places to update (sometimes the media repo needs to be in synch with assets, e.g. when we switched the file format), which atm we get automatically, then we need to handle this case.

@Symbian9 What is the problem of just using svn? TBH, while I certainly favour git of subversion, for the media repo the setup we use seems to work pretty good.

**Comment by auriamg** [comment]
One thought I just had is that we are more and more moving towards the use of an object library, which is in the media repo, so if you want to make tracks according to our best practices, you will need the media repo anyway to have access to the library

**Comment by Symbian9** [comment]
For the record, @leyyin made repo that look similar to what I mean
* https://github.com/leyyin/stk-blender

But this repo not updated for a while.

Current `stk-blender` add-on look not good, and should be designed according next sheme
* `./blender/scripts/addons/stk-blender/` - main folder for add-on:
  * `../stk-blender/__init__.py` - main script of add-on;
  * `../stk-blender/spm_export.py`, `../stk-blender/stk_kart.py`, `../stk-blender/stk_material_export.py`, `../stk-blender/stk_panel.py`, `../stk-blender/stk_track.py` - submodule scripts of `../stk-blender/__init__.py`;
  * `../stk-blender/stkdata/` - directory with parameters as XML-files (configs) of each submodule script.

Also, need update it to Blender 2.78c (current LTS tree).

**Comment by qwertychouskie** [comment]
@Symbian9 Also, SF got new owners since the scandal that promptly removed the adware and stuff, see https://sourceforge.net/blog/sourceforge-acquisition-and-future-plans/ and https://www.pcworld.com/article/3032490/internet/new-sourceforge-owners-kill-contentious-devshare-bloatware-program.html and https://sourceforge.net/blog/sourceforge-now-scans-all-projects-for-malware-and-displays-warnings-on-downloads/

**Comment by hiker** [comment]
We just discussed this issue on irc. I can't see any advantage of splitting the blender tool into a separate repository:
- there is no need to download 1.5GB of data, if you are interested in latest development version, use svn.
- you need a media repo in synch anyway in order to use our objects
- if a blender developer wants to contribute, it's easy to download the svn version, put it in local git, and send us a patch.
Yes, I do acknowledge that git is the superior version control system, but the additional work for us (updating all instructions, finding a way to make sure that the exporter version and .blender files are in synch) is just not worth, since I don't see any clear benefit. If you are an artist and want to use our latest (and sometimes experimental/work-in-progress) versions, you need to use svn anyway, if you are a blender developer, feel free to use git and just send us a patch.
I am therefore closing this issue. If you should have a use case that we did not think of, please reopen!

Cheers,
   Joerg

**Comment by Symbian9** [comment]
Anyway, @leyyin just updated his repo `stk-blender`
* https://github.com/leyyin/stk-blender/commit/1b530b2e6030205402734a0194c9bdb3904088b6

Thank, you, @leyyin! Please, eep it fresh!

**Comment by leyyin** [comment]
Btw @Symbian9 my repo will most diverge in the near future and break things, as I am trying to clean things up there, so do not rely on it ;)

**Comment by konstin** [comment]
There's also [git-svn](https://git-scm.com/book/en/v1/Git-and-Other-Systems-Git-and-Subversion), so you can use git with a svn repo.

**Comment by Symbian9** [comment]
> There's also git-svn , so you can use git with a svn repo.

@konstin, this is not what asked and not related to what I mean.

This is what I mean
* https://github.com/leyyin/stk-blender
