### ISSUE TITLE
Improvements to 64-bit installer

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3045]
- [x] Ideally we should only maintain one installer file. Not sure if this is possible (since I don't see an option to select any options for nsis), so perhaps we can use some kind of #include system to maintain parts of the script, and then have two top level scripts that include common parts/
- [x] The 64-bit windows installer should first search for paths like bld-64 etc (or probably only look for those paths, to avoid that a 32 bit binary is picked up).
- [x] The library names in dependencies should be identical to avoid that we have to maintain two list of files to remove on uninstall.
- [x] 64 bit installer should first search for dependencies-64bit (or so), not dependencies (again to avoid that we include 32 bit libs with a 64 bit binary).

**Comment by Benau** [comment]
Now we ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) installers on GitHub Actions server, ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif) sed the nsis file so that it only include files from ls ../../build-$arch, and we only need 1 nsis file from now on ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

see https://github.com/supertuxkart/stk-code/commit/0d84350ab73a46ccd329d1bd97898a39e8c14110

It will only ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) installers if you add any tag in stk-code
