### ISSUE TITLE
Gamepad configuration issue

### ISSUE THREAD

**Issue by MailBoxSNES** [supertuxkart/stk-code#3061]
when i try mapping a button to an action it quickly inputs axis12

**Comment by Benau** [comment]
gamepad model / operating system?

**Comment by Malcolm002** [comment]
Rock Candy Xbox 360 Controller
and The  operating system is windows 8.1 pro 64-bit

**Comment by tobyplowy** [comment]
@Benau I also get this but I get axis22 :/

I use Windows 10 64-bit and an Xbox one controller

**Comment by hiker** [comment]
I will retry this. I was using an original xbox 360 controller during development, and it obviously worked for me, but perhaps I broke something.

**Comment by hiker** [comment]
Could you post your input.xml file (%AppData%/supertuxkart/0.8.2/input.xml) here? And also try to temporarily rename this file, then start stk again and see if this makes a difference?

**Comment by Malcolm002** [comment]
I could try but I’ll have to do it tomorrow and I probably can’t post a input.xml

**Comment by Malcolm002** [comment]
Also forgot to mention that I tried to copy and paste one of my 0.9.2 configurations to the 0.9.3 configurations and it worked but I wasn’t able to drift :/

**Comment by Malcolm002** [comment]
By the way, what name do you recommend for me to rename input.xml or I can just name it anything I want?

**Comment by tobyplowy** [comment]
@hiker this is my input file
[input.zip](https://github.com/supertuxkart/stk-code/files/1500116/input.zip)

**Comment by hiker** [comment]
I just tried with a wireless Xbox 360 controller, and a wired Rock Candy Gamepad for Xbox 360 - and both work fine for me.
Then I took @tobyplowy input file, renamed the xbox one controller to xbox 360, and it worked also fine for me.
So since axis 12 and 22 should actually not exist (only 6 are used iirc, maybe two more, but certainly not 12), something is wrong. Either the controller delivers incorrect signals, or something else does.

Can you try to start supertuxkart from the command line and add the paramater --gamepad-visualisation. E.g. use the run command and specify the path to the executable, e.g.: 
```
c:\Program Files (x86)\SuperTuxKart 0.9.3-32bit\supertuxkart.exe --gamepad-visualisation
```
with the controller connected at that time.

You should see the STK windows showing 4x2 graphs. Now try all buttons and sticks on the controller, and you should see the corresponding bar (or checkbox) light up. The two sticks should have two axis (one left/right; one up down), and 2 axis for the triggers (only positive). Oh, the d-pad might not show up in that display, that's normal (i.e. known bug ;) ). That's the top 6 axis (and all buttons at the very top).

Now you might see some other values being displayed, but they should not move. We get 32 (iirc) axis reported, but since they don't exist, they don't change.

Can you confirm if this is the case so far? Or do you see any bar's (esp. the 22nd/32nd) move?

**Comment by Malcolm002** [comment]
Ok I will try that

**Comment by Malcolm002** [comment]
I typed in the command line into command prompt and it says Ian not recognized as internal or external command

**Comment by auriamg** [comment]
Could you please post the exact error message (a screenshot)? That error message doesn't make much sense to me so maybe there is something more that we could notice if we had the full information

**Comment by Malcolm002** [comment]
Oops :S

**Comment by Malcolm002** [comment]
![error](https://user-images.githubusercontent.com/33904535/34121243-5cbc0b40-e3f6-11e7-8bf8-46c67dd6594d.png)

**Comment by deveee** [comment]
It doesn't like space in "Program Files". When you are in STK-32bit directory, then use Shift + right click and choose open in cmd. And then you can run STK with additional parameters.

**Comment by Malcolm002** [comment]
oops i meant to use this image instead
![error](https://user-images.githubusercontent.com/33904535/34124611-8d6d6efe-e401-11e7-8a22-914310ff5566.png)

hows this

**Comment by Malcolm002** [comment]
it's not showing open in cmd

**Comment by Malcolm002** [comment]
instead it showed run as different user

**Comment by auriamg** [comment]
ok, try with quotes instead :

```
"c:\Program Files (x86)\SuperTuxKart 0.9.3-32bit\supertuxkart.exe" --gamepad-visualisation
```

**Comment by Malcolm002** [comment]
i did what you said and a new problem popped up.
![new problem](https://user-images.githubusercontent.com/33904535/34171112-34a7fd2e-e4bb-11e7-8b42-2e37e138d890.png)

**Comment by auriamg** [comment]
This is the screen hiker was previously talking about:

> You should see the STK windows showing 4x2 graphs. Now try all buttons and sticks on the controller, and you should see the corresponding bar (or checkbox) light up. The two sticks should have two axis (one left/right; one up down), and 2 axis for the triggers (only positive). Oh, the d-pad might not show up in that display, that's normal (i.e. known bug ;) ). That's the top 6 axis (and all buttons at the very top).

> Now you might see some other values being displayed, but they should not move. We get 32 (iirc) axis reported, but since they don't exist, they don't change.

> Can you confirm if this is the case so far? Or do you see any bar's (esp. the 22nd/32nd) move?

**Comment by Malcolm002** [comment]
What do you mean?

**Comment by auriamg** [comment]
Well I can't say it much clearer than hiker did; once this screen pops up, press buttons and axes on your gamepad and watch what happens, this screen will show red bars when STK detects gamepad input. The main goal is to see if anything unusual happens, for instance the 12th axis lighting up when it should not

**Comment by Malcolm002** [comment]
Hmm

**Comment by Malcolm002** [comment]
I played with another Controller and no axas12, I think i found the solution

**Comment by Malcolm002** [comment]
heres my input file
[input.zip](https://github.com/supertuxkart/stk-code/files/1613337/input.zip)

**Comment by mynthon** [comment]
Same problem here with 0.9.3. 
0.9.2 works without any problems. I have old a4tech x7-t6 driving wheel which is recognized as xbox360 controller. For some strange reasons in 0.9.3 acceleration and breaking are defined under same button. But when i try to change it in options after doubleclick an option popup shows and closes itself binding axis12 (which may be mouse move because sometimes when i move mouse kart accelerates - cant test now as I am not at home).

In 0.9.2 when I change option popup shows and asks for new binding. I have options to cancel or accept etc. In 0.9.3 it shows for milisecond and then autocloses. It looks like there is event send twice or there are some events send in background.

**Comment by danielnelson** [comment]
I have a similar issue with 0.10.0-beta1 on Windows 7 64-bit, happens with both an X-Box 360 controller and a 8-bitdo SN30.  In game it shows Axis 10.

What I found as a workaround is that if I select the action I want to bind with the mouse, but then use the gamepad to open the bind dialog (A on the X-Box controller) then it doesn't close immediately.  On the other hand If I doubleclick with the mouse to open the binding dialog then it will immediately close and be set to Axis 10.  I thought the mouse might be sending the Axis 10 event, but if I open the binding dialog with the gamepad and wiggle the mouse, the dialog still stays open.

**Comment by MailBoxSNES** [comment]
i found out whats wrong, it inputs axis 12 when configuring with a mouse but with a controller it works fine albeit it inputs axis 8 if i wait to configure it for too long

**Comment by qwertychouskie** [comment]
Still present in 1.0. see https://github.com/supertuxkart/stk-code/issues/3723 and https://github.com/supertuxkart/stk-code/issues/3955.  Help debugging would be appreciated.

**Comment by BramKaandorp** [comment]
I've tried changing the keybindings with the gamepad plugged in but the mouse and keyboard unplugged, still got this problem. I don't get it with the controller unplugged and mouse/keyboard plugged in.

**Comment by gsbhasin123** [comment]
Still present in git master (1.1)

**Comment by Sonickyle27** [comment]
I'm also seeing this in 1.0 on Windows 10 version 1903. Here is how the graph appears for me.

![image](https://user-images.githubusercontent.com/4775038/69467716-30451f00-0d81-11ea-88b2-b19df462d77f.png)

I'm using a Dualshock 4 controller through DS4Windows (so it's being emulated as a Xbox 360 controller.

**Comment by Benau** [comment]
can you try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200321/SuperTuxKart-git20200321-win.zip/download and see if it works better? ![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)

**Comment by danielnelson** [comment]
@Benau The issue is fixed for me with this build, Win7 with 8BitDo SN30 gamepad.

**Comment by BramKaandorp** [comment]
> can you try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200321/SuperTuxKart-git20200321-win.zip/download and see if it works better? ![](https://camo.githubusercontent.com/b99e151fb963e60417e3fbc75f39cd924ed10cba/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f7069672f64616e6365322e676966)

Yup, that does seem to solve it.

**Comment by MailBoxSNES** [comment]
I tried to configure my controller in 1.0.0 (haven’t tried it with the latest version yet) but using the mouse to map the buttons causes the axis 12 but using the controller itself doesn’t cause this

**Comment by gsbhasin123** [comment]
Works with the latest version and ps4 controler btw
