### ISSUE TITLE
Adjust the agressiveness of LoD depending on current track

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#3088]
Currently we share many library objects like palm trees and grass that have LoD and are shared between various tracks.

Now if you compare two tracks like an oasis and the dense vegetation of Cocoa Temple we have an issue.

If we tune the LoD of the palmtree to be aggressive, we will improve performances in cocoa temple but will produce a quite noticeable popping effect in the Egyptian oasis. One of my solution was to duplicate and make the palmtree local in egypt so I could disable the LoD for this specific model.

I think it's not a good solution since we want to avoid as much as possible manual tuning. My proposal is to make it dependent of the track. In a map like cocoa temple we can increase the aggressiveness of the LoD, the vegetation is quite dense and we safely cull a lot of the models. While in the oasis, it's probably fine if the LoD is completely disabled.

Here is my proposal.
We count roughly how many LoD models we have and depending on some threshold we add or remove 20% in the distance of culling of each model.

In a track like shifting sand we have ~90 library models, while in cocoa temple we have ~700 library nodes. For comparison Candela City has roughly 400 objects.

We could try something like: 

- if amount of LoD objects is between 0 and 300 we can safely add a 30% margin to all LoD.
- If we are between 300 and 600 we let everything like it is
- And if it's over 600 we can remove ~30% to all LoD.

Of course the final values depends a lot on what we see what value would work the best. We can also add safety margin (like we can't go below ~20 m for the highest model).
This could improve performances in most demanding tracks and lower popping issues in desert/almost empty tracks).

**Comment by onetrev** [comment]
Just wondering if this effort will help to normalize framerate / FPS between different tracks? It's a bit of a bummer that my FPS differs so much between the majority of tracks and the few object heavy tracks like Cocoa Temple. I go from 80-90FPS on most tracks down to about 40-45FPS on a few of them. 

As such, it's probable that most users end up going with the lower graphics setting because of only a few tracks. In my case, where I can play most tracks at Graphics Level 6 and get the super smooth beautiful 80+FPS, I end up at Level 5 because of a few tracks, and even then it's still ~40FPS so I should almost be Level 4 for those few tracks, which is a huge quality level setup down.

CPU:  i7-8650U
GPU: GTX 1050 2GB

**Comment by samuncle** [comment]
And it's done in a branch. Will be soon merged https://github.com/supertuxkart/stk-code/pull/3789

**Comment by samuncle** [comment]
Done and merged. The full explanation is here: https://forum.freegamedev.net/viewtopic.php?f=17&t=11458&p=83681#p83681
