### ISSUE TITLE
Internet access is disabled, enable it in options

### ISSUE THREAD

**Issue by gordonfreeman424** [supertuxkart/stk-code#3100]
## Description
I get the message "internet access disabled, enable it in options"

I'm in the options, and i'm clicking the enable internet access box

essentially, the software tells you to do what you are currently doing, which doesn't work

## Steps to reproduce
1) Install STK
2) don't configure internet (don't enable it)
3) go into options
4) go to online profiles
5) click enable internet
## Configuration

STK release version:
0.9.3
STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:

System: 
Windows 10 64 bit, 32 gigabytes of ram
Graphics card: 
gtx 960 4GB
CPU: 
 i7 6700
Gamepads/keyboards models if related to the issue:

## Additional information

Please provide stdout.log, it is located in

* %appdata%\supertuxkart\0.8.2 (windows)
* ~/Library/Application Support/supertuxkart/0.8.2 (mac)
* $XDG_CONFIG_HOME/supertuxkart/0.8.2 or ~/.config/supertuxkart/0.8.2 (linux, and other unix based systems)

stdout.log
```

```

If your issue is related to the input config (gamepads, keyboards), please provide your file input.xml located in the same directory as stdout.log.

input.xml
```xml

```

If an error message was shown, please copy paste the complete error message or a screenshot of it.

error
```

```

**Comment by Alayan-stk-2** [comment]
The button triggering the message is the "online" button in the players tab.
The "Connect to internet" button the player is supposed to press is located in the UI tab.

So the buttons work as intended, but the resulting behavior is confusing.

Fix : display the error message in a dialog instead of the current way, and give in the dialog options to enable the internet connection or to cancel.
