### ISSUE TITLE
Supertuxkart 0.9.3 on Android (big lagging)

### ISSUE THREAD

**Issue by jacobsatan** [supertuxkart/stk-code#3113]
I have a problem with super tux kart on android. After switching on the advanced graphics options the game is lagging horribly. It looks like when Im choosing to have permision to advanced options they are implemented into game even if I do not switch on any of this options (like blur, god rays).

**Comment by Benau** [comment]
so what do you except?

**Comment by jacobsatan** [comment]
Better optimization ;3 And bug fix on situation that I described.

**Comment by Mrxx99** [comment]
An soultion would be to don't change any settings in graphics settings when the users turns advanced pipeline on (with all options under it turned off), except enabling those options.

**Comment by deveee** [comment]
I don't really understand what would you like to do with graphics settings.

Anyway STK is playable with highest settings on some android devices:
https://www.youtube.com/watch?v=6hE1zInssPA

And advanced lighting is disabled by default. If you don't have powerful enough device, then don't turn it on.

I will build an android package based on current git soon, so that you will be able to see if it's better for you. For me some tracks are much faster when advanced lighting is disabled.

And "Better optimization" is very generic and known issue.

**Comment by Mrxx99** [comment]
I think he means the point advanced pipeline looka like it would only enable other settings and does not change anything. But it seems it does change things. That does not need to be bad but because it looks like it does not change things it can be confusing when performace drops and you think I did not change one of these advanced settings

**Comment by Mrxx99** [comment]
Btw I don't have a problem with this "issue".
And you could argue if someone changes graphics settings and then notices a performance drop, he could just turn these settings back to normal

**Comment by deveee** [comment]
@jacobsatan I see nothing wrong with our graphics settings and it's IMO clear enough, so that I'm closing it as invalid.

And you can check if current git STK is better for you. I just uploaded it on google play as beta version for testing. For me on android there is ~50% more fps on some tracks.
