### ISSUE TITLE
Android: (Ready,Set,Go)-Lights stay red

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3117]
## Description
On my Android devices the traffic light for the start stays red, and does not change to orange and green.
![screenshot_20180208-175414](https://user-images.githubusercontent.com/33566379/35987114-2fc7df0a-0cfb-11e8-804b-5164a872bd8a.png)

## Steps to reproduce
Start SuperTuxKart on an Android device and start a race

## Configuration

STK release version:
both google play versions: normal 0.9.3 and the beta one.

System: 
Samsung Galaxy A5 2017 and NVIDIA Shield TV 2017 (Android TV)

**Comment by Benau** [comment]
try adb push thunderbird.spm and traffic_light.png to /sdcard/stk/data/models

...probably deve needs to make an execption for traffic_light.png

**Comment by deveee** [comment]
Sure, we can add exception for traffic_light.png.

@Mrxx99 Did you already try STK on Android TV? Because I have only an emulator and a gamepad connected to tablet, so I can't really test it.

For current beta google rejected it as application with Android TV support, probably because of missing gamepad support. In this case is it possible to install the apk or google play doesn't allow it? And I wonder if it's possible to use real dpad on IR remote to play STK (it's possible under emulator).

In current git I can play with gamepad on a tablet with skidding/nitro/looking backwards etc without any issues. Atm. it works only with single gamepad and it just simulates keyboard keys, but it's better than nothing. I will upgrade the beta package tomorrow, so that you will be able to test it too.

**Comment by Mrxx99** [comment]
ok, copying these files also works for the beta (didn't realise the beta has an extra folder)

@deveee Yes, I tested both versions (I sideoloaded the apk for the normal version and could install the beta version through the Google Play Store Website onto my Android TV. Couldn't find it in the Google Play Store on the TV, propably the reasons you mentioned)

Suprisingly the  normal 0.9.3 version is fully playable with an dpad bluetooth remote (as good as you can play a racing game with an 5 button remote)
But the beta version just keeps crashing on my Android TV. See issue #3119.

Will test again if the updated beta goes live on the Play Store. If you wante me to test anything let me know ;)

**Comment by Mrxx99** [comment]
Maybe we could move this discussion over to the forum, as it has nothing to do with my posted issue?
Maybe this android topic: https://forum.freegamedev.net/viewtopic.php?f=17&t=6118&start=25

**Comment by deveee** [comment]
Fixed in https://github.com/supertuxkart/stk-code/commit/34f0f8c2395a7a23b8812e73403f54ae5137b597
