### ISSUE TITLE
Driveline (additional) ignored by AIs - doesn't work in reverse

### ISSUE THREAD

**Issue by SvenAndreasBelting** [supertuxkart/stk-code#3124]
## Description

Working on my forest track, I have this problem:
I have marked one driveline (additional) as „invisible“ and „ignore by AIs“. Driving forward it works, driving reverse it doesn‘t work: the AI karts use the driveline nevertheless.

## Configuration

STK release version:
0.9.3

STK Source:
download from the official website

System: 
Linux Mint 18.3

[forest_track.zip](https://github.com/supertuxkart/stk-code/files/1732294/forest_track.zip)

[forest_7.blend.zip](https://github.com/supertuxkart/stk-code/files/1733602/forest_7.blend.zip)

**Comment by auriamg** [comment]
Hi, do you think you could attach the blend and exported track to this ticket? It would help us to have a test case to work with

**Comment by SvenAndreasBelting** [comment]
The blend is 55 MB big (compressed as zip) and github attach doesn't take it. How can I send it to you?

**Comment by auriamg** [comment]
I assume the blend is large because of the textures? You could just upload the blender without textures, then it should be much smaller

**Comment by SvenAndreasBelting** [comment]
The blend I have uploaded now, is without textures and without trees.

**Comment by auriamg** [comment]
I believe I have fixed the issue, can you try downloading the latest stk_track.py exporter file from https://sourceforge.net/p/supertuxkart/code/HEAD/tree/media/trunk/blender_26/stk_track.py and installing it into your blender?

@hiker This is caused because only the first <quad> in the XML file receives the AI-ignore flag, so in reverse it wouldn't work. The easy fix I did was to output the flag for the first AND last quad of a shortcut, but since you know the quad system best, does that sound good to you?

**Comment by hiker** [comment]
@auriamg sound good to me. We could fix this in stk as well, if it would require too many tracks to be re-exported. But I guess at this stage only one track is affected, so that should be fine.

**Comment by SvenAndreasBelting** [comment]
I have installed it and it works well.
