### ISSUE TITLE
UI scaling issues

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3146]
Some places in the GUI are not correctly scaled in big resolutions.

Here it is too small (small icons and a lot of blank space) : 
![scalingissue1](https://user-images.githubusercontent.com/25536748/37546805-eef37f1c-296e-11e8-8fca-403be4d5c722.png)

Here (in egg mode) it is too big (4 tracks are displayed when 6 are available) : 

![scalingissues2](https://user-images.githubusercontent.com/25536748/37546806-ef1a1a6e-296e-11e8-819e-dff0c9d4279f.png)

**Comment by ssspacez** [comment]
For comparison, 1366 x 768:

![scale1](https://user-images.githubusercontent.com/34775187/37547869-ee0ec2e4-2952-11e8-9eae-5341a22f5028.png)

![scale2](https://user-images.githubusercontent.com/34775187/37547870-ee2e3bb0-2952-11e8-9b86-d56fbc06ff70.png)

**Comment by ssspacez** [comment]
By the way, IMO _**difficulty**_ and _**game mode**_ should be **two separate screens** instead of one, it's easier and have an additional advantage: 

This way, game mode would have **more space to add more information and some media**(screenshot, gif or video) of the the game mode. The 7 little boxes(game modes) could be vertical on the left and on the right side of the screen put a more detailed description of the game mode and some media related to each one. Or leave it horizontal and put the media below it.

**Comment by auriamg** [comment]
Should be good enough now in git.

@ssspacez Your idea is not bad, but our current efforts are currently on implementing networking, not on major UI overhauls, so that's unlikely to happen in the short term
