### ISSUE TITLE
Story Mode is a bug, not a feature, it should be 2D

### ISSUE THREAD

**Issue by ssspacez** [supertuxkart/stk-code#3165]
In my opinion the Story Mode is not the best idea, I consider it a bug not a feature... it's not intuitive and honestly it makes no sense driving a kart into a bubble and pressing space.

**Workaround**: make it **2D** like the game **Super Tux 2**.

Look at the screenshot below:
![superttux2](https://user-images.githubusercontent.com/34775187/37996425-fa1c4810-31ed-11e8-8dac-518c7a6a0c6b.png)

It's so much more intuitive, easy to understand, it makes the game progress more pleasant and accessible to eveyone.

**Comment by auriamg** [comment]
Hi, the github bug tracker is best suited to submit bugs, or tasks that have been scheduled for development by the core team. Such feature requests or general discussions are better suited for the forum

**Comment by ssspacez** [comment]
The whole Story Mode is a bug, I've suggested an easy and efficient way to fix it... and GitHub can be used for **enhancements** too, don't throw away ideas just because they are not posted on the forums, this is not the first time someone answered with "use the forum"... You guys are doing it wrong, I won't help the project anymore, good luck.

**Comment by auriamg** [comment]
Enhancement suggestions are welcome, we have simply decided that github is not the place where we want them to happen. If you post on the forum, usually we will reply.

In this case, I think you may not be realizing the effort required to do that, as you state your solution is "easy", but it is anything but : we do not have a 2D engine, we do not have 2D graphics nor a 2D graphics artist, we do not have a 2D map editor, whereas we already have all these issues figured out for 3D. Sure, these tools exist elsewhere, but given our limited manpower, implementing that would likely take several months of work, and the team is already busy on higher priority tasks such as the network.

That being said, we are fully aware that story more is far from idea and an overhaul is planned for the future. When and how exactly this occurs is unknown, most likely after networking since that is our current priority.
Also, we like having a 3D map overworld since this provides a safe place for players to test driving around and get used to the controls.
