### ISSUE TITLE
Too high speedometer/nitrometer texture resolution, other small bugs

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3193]
The sppedometer/nitrometer look like they were exported at a higher resolution than they were made at, resulting in a bit of a fuzzy effect when viewed at full resolution.  Also, do they really need to be at 768x768?  That seems unnecessarily high to me.  Also the 3D effect on the nitrometer looks a bit weird to me personally (the speedometer looks good though).

Additionally, `gauge_goal.png` renders over `gauge_full.png`, which looks a bit weird (it should be the other way).

I'm a bit of a perfectionist ;)

**Comment by Alayan-stk-2** [comment]
They have been made exactly at the resolution at which they have been exported.

It maybe doesn't need to be at that resolution, but I figured out that the file size difference is small and that it's always easier to downscale a picture than to upscale it if too small (also better if/when very high resolution screen becomes more common).

If you look at them in full size, of course you'll see blur. The blur create semi-transparent borders. I had to blur them before export (I also have the original gimp files so I can create non-blurred versions) ; because otherwise in-game (which is what matters) there are aliased borders.

For gauge_goal rendering over gauge_full, that's intentional. The upside of doing it like this is that : 1)when the nitro bar goes over the goal, there is a difference in color making it more obvious ; 2)If gauge_full rendered over gauge_goal, as it is larger than the semi-transparent zone of gauge_goal, it would draw over the border, which would look very bad. Of course, it would also be possible to change gauge_goal to have its borders separated by a higher distance. I found it less practical.

**Comment by auriamg** [comment]
Actually, these images are really huge so I'd like to scale them down a bit.

@Alayan-stk-2 I tried scaling them down, but that gave really weird results. Did you assume a specific image size in your code? In general, it's preferred to code this kind of code in relatve coords (0-1 range) and not in absolute, so that the code keeps working no matter the image size

**Comment by auriamg** [comment]
@Alayan-stk-2 Okay nevermind my previous comment actually, my STK build was all messed up. After a rebuild, it's all working fine. I've scaled them down a little, no need to use so much VRAM
