### ISSUE TITLE
Story Mode: Unlock Notification will end the current GP

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3226]
Story Mode: Unlock Notification will end the current GP, the treasure chest will appear, and hitting continue will return you to the overworld.

STK release version: git

An unintended side effect of #3209 / #3207

**Comment by Alayan-stk-2** [comment]
While this need fixing ; how does an unlock notification appears mid-GP ? You're not supposed to get points or a finished challenge mid-GP, currently at least, afair.

**Comment by psypherium** [comment]
It occurs when re-using a profile from a previous version. I had completed 0.9.3 any% and then moved to 0.9.4 to finish the rest.

It checks "Has x points" and "has completed track" but not "has received points" maybe? The profile had never seen an unlock notification before so it started showing all the ones it missed?

II had assumed this happens by default but I've tested on a clean profile/user and it doesn't reproduce it. I will follow those same steps in the morning and make sure the error is reproducible, but since a fresh profile works fine it would seem to be a issue with re-using profiles.

**Comment by Alayan-stk-2** [comment]
After some testing, this happens after finishing any race (it can be a single player lone race)

**Comment by auriamg** [comment]
If the changes are too incompatible, incrementing the version number is one possibility (to be discussed)

```
m_user_config_dir +="0.8.2/";
```

in file_manager.cpp

**Comment by Alayan-stk-2** [comment]
Switching from one version to another apparently "forgets" the challenges which exist only in one of them. This means that if you launch 0.9.3, and then come back to git version (as I do a lot), the challenges which are in one but not the other are reset to "not completed".

Considering this, considering that there will probably be additional challenges (reverse, probably) once sam's new overworld is done, considering various balance changes, incrementing the config file version number seems necessary.

If networking work fine enough, it would maybe even make sense to release the next version as 1.0 rather than 0.9.4. For such a version bump, extra care would have to be taken to polish things before release, but honestly the greatest obstacle seems to be the minimum quality of tracks the team would like to ship in such a version.  As for the delay between 0.8.2 first RC and 0.9.0 release ; some longer beta-testing phase would also probably be needed ; particularly to catch and fix networking issues.

**Comment by deveee** [comment]
For your own use, you can use ```export HOME=./.config``` before running STK, so that it will have its own config directory.

**Comment by Alayan-stk-2** [comment]
This issue now happens every time on the first race after having started STK (if I restart it multiple time, I'll get the issue on each first race), because the data is not saved properly.

Must be related to the patches for #3274.

**Comment by Alayan-stk-2** [comment]
The git version now uses a different profile folder, as will the next release, so this bug shouldn't trigger anymore when switching between 0.9.3 and git.

If it still happens in some other situation, please comment with the relevant info to reproduce the issue.
