### ISSUE TITLE
Additional infos in the help menu

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3233]
The help menu is not supposed to be a full internal wiki, but rather a quick overview. And of course, STK parts and options should strive to be clear enough that looking at the help is not required.

Still, it should work as a first place to check before an internet search/forum question, and there are numerous important part of STK which are currently not covered.

Things to consider adding/changing : 
- [x] Mention slipstreaming somewhere. This can be short.
- [x] Mention the ghost race mode
- [x] Some explanation about the kart classes (the statistics shown in the kart selection menu give a simple understanding, but they cover only a part of what the kart classes do).
- [x] A story mode help tab, explaining the basics. (Status : may be improved but should do for now)
- ~~Something about difficulties. Difficulties mix kart speed/acceleration AND the level of the AI.~~
- [x] Proper skidding help. This is an important part of STK, and the few words about it in the general tab are not enough to explain it properly. A dedicated tab, with some illustrating picture, would help a lot. It's also included in the tutorial, but if someone don't get it there, another round of explanation can help. [I went with simply expanding the text in the general tab]
- [x] The "weapons" list should probably renamed "powerups" or something like that (the word "weapon" should also be changed to "powerup" in the text of the normal race mode) ; and the zipper should be added to the list.
- ~~Something about GPs ?~~ The short text at the bottom of the game mode tab should suffice.
- Something about achievements ? (Not really useful given the current achievements)
- [x] Multiplayer help updated to factor in networking. The existing explanations for local multiplayer have been shortened.
- [ ] Something about handicap
- [x] Improve the explanations for powerups (swapper inverts nitro/gum, swatter removes bomb, cake has an area of effect)

It would also be nice to mention the help in the tutorial.

(Updated to reflect the state of my WIP changes)

**Comment by qwertychouskie** [comment]
Also, probably give a short explanation of the Handicap function.

**Comment by auriamg** [comment]
I agree with _some_ of them, but in many cases IMO making things clear contextually is much better than info dumps on the help screen,

For instance, difficulties. Not once has anyone ever told us they don't understand what difficulties mean and wanted a help screen about it. For some features, I think we just have to trust in people's intelligence and that our screens contain enough inline information, without needing to spell everything out in the help menu. Same thing about GPs, the vast majority of player seem to understand just fine without explanations.

Same thing about story mode, instead of a help page, maybe the first time you open story mode, you get a little more in-game guidance (integrated to gameplay, not on a separate screen)

**Comment by Alayan-stk-2** [comment]
I went and did most of it. I abandoned a few ideas which didn't seem worth it.

Here is a video demonstrating the result, using vertical tabs on the side to allow the addition of a "Story Mode" tab and of a "Kart classes" tab : https://youtu.be/5U88fwDZJR8
