### ISSUE TITLE
android version does not uninstall properly

### ISSUE THREAD

**Issue by Elmapul** [supertuxkart/stk-code#3266]
i instaled the game on a phonem tested it, deleted it , but the free'd memory was inferior to the used memory in order to install it, it took me a while to figure out why.
today i was browsing the phone directorys on my computer and found it:
mtp://[usb:003,095]/Armazenamento%20interno
translating it...
(mtp://(current usb device)/internal storage/stk)

uninstalling the game don not remove all the files

**Comment by deveee** [comment]
Data may be extracted in one of following paths:
/storage/sdcard0/stk
/storage/sdcard1/stk
/storage/sdcard0/Android/data/org.supertuxkart.stk/
/storage/sdcard1/Android/data/org.supertuxkart.stk/
/data/data/org.supertuxkart.stk

or other similar paths depending on your device.

From my point of view it's better to extract data in first two paths, because:
- you can easily add more tracks, modify config file, remove whole directory if you need etc
- config files are remembered when you uninstall/reinstall the game
- it's better for testing, because it doesn't need to extract whole data every time that I install it using adb

And other games extract files directly on sdcard too (for example Minecraft is in /sdcard/games on my phone). So that for me it's not really a bug.

I'm not sure how to improve it... We can add "move to sdcard" and "move to internal storage" etc. in STK settings. But anyway it won't work if you already uninstalled the game.

**Comment by Elmapul** [comment]
make sure to inform the user that he might need to delete aditional data after uninstalling the game, and add this:
"We can add "move to sdcard" and "move to internal storage" etc"
definitely that would help

"config files are remembered when you uninstall/reinstall the game"
this is a must have
