### ISSUE TITLE
Closes unexpectedly on initial launch

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [supertuxkart/stk-code#3281]
Hey everyone,
On installing the google play version on a Moto G5 Plus, running android 7.0, the app, on initial launch shows the white progress bar with black background, and then just closes on its own before the progress bar finishes loading. It doesn't show any error, neither does android system says that the app crashed.

**Comment by deveee** [comment]
If it closes _before_ progress bar finished loading, then extracting data failed. Make sure that you have enough free space (~150MB).

One some phones people also reported some weird behavior. For example it reports that data is successfully extracted, but there are no files extracted on sdcard, so that the game can't launch. Maybe it's a kind of safety mechanism. It should be better in next beta version, because now I check if the path is writable.

You can try to reject "write to sdcard" privilege for supertuxkart apk if it's possible on your phone. In this case the game will choose different location for data and maybe it will extract everything successfully. Someone reported that it helped.

And unfortunately STK doesn't write log to file before files manager is actually initialized, so that we don't have information what actually happened. 

Maybe I will add a message box or toast message when error happens, but it's not trivial, because STK is not a java app...

And btw. the Moto G5 Plus is kinda known non-working device (I saw multiple crashes on google play for this device), but the reason is unknown. For example it crashes in ```drawBgImage()```, so that it suggests the case that I wrote (maybe it reported that data was extracted successfully, but the file is missing).

**Comment by deveee** [comment]
Actually I can prepare a build with current git version for you, so that you will be able to check if it works. Because maybe checking if the path is writable is enough.

**Comment by LakshyAAAgrawal** [comment]
Hey, it works on denying permission for sd card. However, it would be much better if it informs during startup, and also gives an option to switch to phone storage.

**Comment by deveee** [comment]
It should be fixed in https://github.com/supertuxkart/stk-code/commit/ffee5d266d8275391476925da8b894a0ec2a87a2

Now it will extract data in /sdcard/Android/data/org.supertuxkart.stk by default and it should work without any permissions.

**Comment by Mrxx99** [comment]
That will also solve the remaining files issue after uninstalling
