### ISSUE TITLE
Completing Story Mission Defaults to Restart on Supertux Difficulty

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3351]
Completing Story Mission Defaults to Restart on Supertux Difficulty

It's the same thing as was happening previously with expert difficulty

**Comment by auriamg** [comment]
I'm not sure I understand what you mean, and I haven't been able to reproduce any issue when completing a story mode mission. Could you elaborate by providing more information on the exact steps?

**Comment by Alayan-stk-2** [comment]
The issue description is confusing, I don't get it either.

There is one known limitation : if you finish at a good enough place in a GP to get a cup (like, 2nd in expert difficulty yields a silver cup), the game difficulty is changed so that the correct cup is awarded. But that's a corner case and doesn't seem to match the described issue which reference "the same thing happening previously".

**Comment by psypherium** [comment]
Come first on a story mode mission, default selection is "restart"
pressing enter restarts the track instead of returning to overworld.

**Comment by Alayan-stk-2** [comment]
Ok, so the issue is not that the difficulty is changed after completing a story mode mission, but that after completing for the second time the same challenge, the default option becomes restart. I'll have a look.
