### ISSUE TITLE
Too little space in ghost replay table

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3430]
Both "reverse" and "difficulty" need two words for translation and there is too little space for it. I suppose that other languages will have similar issues.

![zrzut ekranu z 2018-09-14 23-50-28](https://user-images.githubusercontent.com/5108558/45576939-ca563100-b879-11e8-944b-e08abc051fb8.png)

**Comment by Alayan-stk-2** [comment]
That kind of issue exists in many more places in the UI ; list headers are just a particularly egregious case for it.

This dialog has already been enlarged compared to before to allow more room for the new list, but with the current UI system, there are limits to what can be done. It's necessary for translators to sometimes use a slightly less appropriate word, or to use a condensed form, to make sure it fits (translators ought to always test the in-game result). For example, "Trudnosc" would convey 99% of the information of "Poziom trudnosc", wouldn't it ?

The only change which may succeed to improve the situation significantly in this dialog is to move the track picture down. There is room for it ever since I increased the vertical height of the dialog when adding the kart icon column. However, different languages have different lengths for different words, so this is not bullet proof.

A dynamic system where the xml would specify a min and max proportions, and the layout engine would get info on what is supposed to get in the columns to dynamically adjust the width sounds like something too complicated for a small team to do.

**Comment by Alayan-stk-2** [comment]
This should be much better now, but your words don't entirely fit yet.

I could increase the proportion for the reverse & difficulty columns (with 4/5 instead of 3/4, your polish translation fit) ; however it makes things really weird in any language using a single word, and reduce space for long usernames.

The only way of improvement not involving complex dynamic layout I see would be to do #2800 and to allow the two words to be on two lines. This is a change which would also help in other places (addons menu comes to mind). It'd be great if it was done, but it isn't trivial.

**Comment by deveee** [comment]
I was thinking about very similar layout, thanks!

And for translations in theory I can use "trudność" instead of "poziom trudności". But it sounds a bit strange and it affects such translations in all places. Actually maybe we can add context for translations in that table (IIRC something like ```_C("Difficulty", "ghost_info"```) and then I can even use some short form, eg. "Poz. Trud.". 

And real solution is probably write it in two lines...

**Comment by Alayan-stk-2** [comment]
Translation context would certainly give more flexibility for translators when a word is used in many place I don't really know that part of the code, but if that syntax is used elsewhere that sounds sensible.

If you can make word wrap work with list cells/header, it would be great.

**Comment by deveee** [comment]
Now there is more space and translation context has been added, so I think that it can be closed.

**Comment by Alayan-stk-2** [comment]
@deveee I've added the ability to break text in lists on multiple lines. The downside is that currently, all list items must have the same height, so to accommodate a double-sized "header" ; you'd need double-size for others lines, which is bad.

So, editing CGUISTKListBox to allow per-item height would still be required to make it work nicely here.
