### ISSUE TITLE
Give clickable links to the latest STK blog post

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3453]
The main menu has an horizontal scrolling bar which display a few news, like the latest addon and blog post.

It's nice to write the website address and the post title ; it would be better to allow one-click access through LinkHelper.

**Comment by GuillaumeBft** [comment]
![Main_menu](https://user-images.githubusercontent.com/54895740/73252771-9011d900-41bb-11ea-87cb-c54c09aaa349.png)

I add these labels below the scrolling news and I know how open web pages with LinkHelper, but I'm stuck because the click on the labels don't run the MainMenuScreen eventCallBack function.
Does someone know why ?

**Comment by Benau** [comment]
do you have your wip-code somewhere?

**Comment by GuillaumeBft** [comment]
Here is the commit : 1127126ff9f1e5d072a10b33a2df6d297eda8c5c
The line 184, 185, 186 in main_menu_screen.cpp don't change anything to the result, I was just trying to see if it made any difference.
The thing is that printf() display when I click on the news label but not when I click on the blog or the addons label I added.

**Comment by Benau** [comment]
maybe label widget is not subjected to eventcallback (or auria!)

**Comment by GuillaumeBft** [comment]
To reduce the difference between the label "info_addons" which calls the eventCallback function and the labels I add, I set scrollSpeed to them (in main_menu_screen.cpp) :
![setScrollLabels](https://user-images.githubusercontent.com/54895740/74644902-53604e80-5177-11ea-9816-41f8c7ca8df5.png)
And that works, do a click on the blog_link and addons_link in the main menu calls the eventCallback function. Well, except that the widget parameter given to eventCallback is always info_addons, so I can't differentiate the labels on click event.
I think the guilty lines are in label_widget.cpp :
![labelWidget _add](https://user-images.githubusercontent.com/54895740/74646434-23ff1100-517a-11ea-9c8a-e5676682c6db.png)

**Comment by Benau** [comment]
actaully the easier change is to allow the text to be clickable by itself... i have some wip-code here:https://github.com/supertuxkart/stk-code/compare/master...Benau:wrong

and you don't need to bother widget anymore

**Comment by GuillaumeBft** [comment]
Ok, thanks, I'll take a look

**Comment by GuillaumeBft** [comment]
I'm trying to fix the commit "wrong" (18906ba84107684c6f530079796d80adf65c8975) :
A bad_alloc() / Seg Fault error occurs when I type in a tchat (like in a server lobby) "http://".

I found what causes the error at line 856-857 :
cur_url_rect = Online::addClickableURLRect(r, all_urls[idx].first);

The variable idx contains 1 but the vector all_urls contains only 1 object. That works correctly if I replace idx directly by 0. 
So this is my question : what is the purpose of the if test at line 852 : "if (i > p.second)"
Because this test should be true and should lead directly to the break, not increments idx.

**Comment by Benau** [comment]
It is a while since i wrote this....

I think probably if there is a linkbreaking in between the link something is complex...

**Comment by Benau** [comment]
![Screenshot from 2021-09-06 01-58-12](https://user-images.githubusercontent.com/3252341/132136771-5f59bca0-93ac-4488-b00d-b8486ec75c5b.png)
In order for auto highlighting work (without adding specific rule for this message) we can try rearrange the message so when click on https://blog.supertuxkart.net it opens firefox

not sure if ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) or auria has better english / arrangement........

ATM xxx https://blog.supertuxkart.net: context will make the ":" highlighted too.... ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

**Comment by Benau** [comment]
but markdown in github seem to autohighlight smarter, not sure where can we find markdown highlight url source code...

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-addons/commit/0e3b664c466f563d63c52c27c2e672b0bc14e9b9 it's now using ```https://blog.supertuxkart.net```, and stk can highlight only ```https://blog.supertuxkart.net``` out of the news now ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
