### ISSUE TITLE
Display lap number (and any other relevant info) in the select challenge dialog

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3459]
The select challenge dialog indicates the track/GP name, the race mode type, but doesn't indicate the number of laps of the race.

It also doesn't indicate the reverse status if any, because reverse challenges are currently unsupported.

The number of laps of a challenge is actually indicated in the overworld UI itself, when getting close to the challenge, but before pressing fire to open the select challenge dialog however ; but it is very easy to miss.

**Comment by Wuzzy2** [comment]
I like to add something:
When you get close to the bubble (before the screen opens), I think it is more useful to display the challenge type instead of the number of laps (oddly, this is the case for Grand Prix challenges but not for other challenges). And the number of laps shall be moved into the screen, as written in the first ost.

I also suggest to display the specific type of Grand Prix as well, i.e. whether it's a normal race grand prix, time-trial grand prix or follow-the-leader grand prix. Could be displayed as “Type: Grand Prix (Normal Race)”.

**Comment by Alayan-stk-2** [comment]
@Wuzzy2 Tell me what you think of the text labels I used when adding info before opening the select difficulty dialog
