### ISSUE TITLE
Disable GUI doesn't hide the minimap

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#3478]
When enabling artist debug mode we can hide the GUI to take screenshot for debug purpose without the GUI (HUD, speedometer, etc). However now when I click on hide the GUI everything is hidden except the minimap of the track.

![metro](https://user-images.githubusercontent.com/6406045/46255041-af4e0880-c498-11e8-9ef6-eb362686f3b2.jpg)

**Comment by Benau** [comment]
devee have time for another apk and server update?

and lol not sure if you like android player only servers!

**Comment by deveee** [comment]
Update apk maybe tomorrorw. And I wouldn't restrict servers to android/non-android only... You can use server name or motd with some suggestions, eg "only for advanced players" and users will decide theirself.

And btw. is it possible that httprequest is not thread safe and that's why I have these crashes/errors on startup? For me it's easily reproducible when I run STK with --no-sound and I get
```[error  ] HTTPRequest: Can't open './.config/.local/share/supertuxkart/addons/news.xml.part' for writing, ignored.```
