### ISSUE TITLE
The on-track items (banana, nitro, gift boxes...) ignore LoD settings

### ISSUE THREAD

**Issue by v1993** [supertuxkart/stk-code#3510]
Actually render distance seems constant, at least not manually configurable. It affect large arenas a lot.

I suggest to add option to settings to either increace/decreace it (like geometry detail, e.g. 0.5/1/2) or even let user enter number.

**Comment by auriamg** [comment]
Before any work starts to make it configurable, the first important step is to measure whether it actually helps or not, and by how much. When trying to optimise things, often the first impression is wrong. Modern GPUs are more than able of rendering tons of geometry super fast, and it's very possible encountered performance issues come from elsewhere

**Comment by Alayan-stk-2** [comment]
The alternative would be to the render distance would be an unlimited render distance (though this doesn't preclude culling things obstructed by others).

A good place to test if the limited render distance helps noticeably would probably be a big track with many item boxes/banana/nitro cans. The two towers addons is probably a good place for this, as it has a ton of gift boxes.

Even if the perf differential is of 2-3% ; it would make sense to have a toggle between unlimited render distance and the current limited render distance ; because the small things add up when using an underpowered graphics card like some intel iGPU which barely reaches playable framerates.

**Comment by qwertychouskie** [comment]
My guess is that the problem is that STK is supposed to be showing the defined `lowmodel`, e.g. `gift-box-low.spm` but instead is just not showing the item at all.  This would need further research by someone familiar with the meshes. (@Benau?)

**Comment by Alayan-stk-2** [comment]
The current geometry detail setting, as of #3789, somewhat does this, but we have two issues : 
- Even the highest option has currently a lot of popping in some tracks. I'm not sure about item specifically, but I'd assume they are affected too. It's not possible to set the setting high enough.
- As Qwerty pointed out, a low-res model is supposed to be shown at long distance but doesn't seem to be.

**Comment by Alayan-stk-2** [comment]
Upon further investigation, **the low resolution models are used** contrarily to what qwerty said, but you need to be quite close for the difference to be apparent, as the low-res models are actually quite well done and don't really trigger popping upon transition.

But on-track items are limited by the code to a distance of 100, beyond which they disappear.
