### ISSUE TITLE
Las Dunas Stadium is unplayable

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3525]
## Description

Normal Race on Las Dunas stadium starts always at second lap. AI karts teleport all over the map sometimes finish the race several laps earlier.   

## Steps to reproduce

Start a normal race in Las Dunas Stadium with a number of laps above 2.

## Configuration

STK release version: git 2ef3980

System: Gentoo

[warn   ] SFX: Position called on non-positional SFX

**Comment by Alayan-stk-2** [comment]
You're talking about the addon track, correct ?

**Comment by Mensious** [comment]
Yes. Is it a Problem of the addon track?

**Comment by qwertychouskie** [comment]
I can confirm this issue, seems to be a regression.  This track always had weird/exploitable check/lap lines though.

**Comment by auriamg** [comment]
Ideally we should identify what causes the issue... If it's a modelling issue (or blender issue in general) then this should be fixed by the creator of the addon, we're not responsible for that. If it's a regression in STK's physics/AI/etc. then it would be nice to know

**Comment by Alayan-stk-2** [comment]
The bug is real, but it is not in STK's code, it's in the addons. I'm closing the issue, you may contact the addon's author through the forum.

The issue is that this track has no checkline at all. Going backward and forward over the lap line allows to validate laps.

This is also true in 0.9.3 ; but code changes to lap line validation make the issue much more obvious in git, because you don't need to go backward for an incorrect validation to happen the first time.

Tracks with correct checklines are not affected.
