### ISSUE TITLE
Auto-rescue sometimes not triggered when expected

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3540]
Turns out the issue is bigger than i told earlier. On the arena Temple and the Cocoa Temple as far as I know there may be more,  when you falling out of a playable area to somewhere where you aren't killed immediately the automatic rescue doesn't work Because it doesn't understand to save you. The video link shows the issue: https://peertube.mastodon.host/videos/watch/22474438-d471-4901-b04f-ecac4403c158
Sorry about the quality. :/
 
## Configuration

STK release version: Git, Commit: c724585
System: Gentoo

**Comment by Mensious** [comment]
Another video for the problem in Arena Temple
My video: https://streamable.com/r3c95

**Comment by auriamg** [comment]
It is known that auto-rescue is imperfect, that is why there is a manual rescue button

This may improve in the future, though it will be hard to detect all possibilities

**Comment by qwertychouskie** [comment]
The lava should also rescue on collision, not just on drive (is this possible?)

**Comment by theTomasPat** [comment]
I would like to help out here. I'm having trouble exporting the temple track though.

It seems as though each kart (I tried with several AI karts), including the player kart were being spawned beneath the track. Each of the start position objects in the blend file are above the track and I've tried modifying the start position's upwards distance in the STK Scene Properties but it doesn't seem to make much of a difference.

I'm using the blend file from the media repo rev. 17958. Is anyone else able to export it properly?

**Comment by BugZappr** [comment]
Right now, the auto-rescue is coming on at all sorts of inappropriate times   When I try to play e.g. Ravenbridge Mansion on Intermediate, it typically triggers 3X per lap, and nearly all are unnecessary.  In the Zen garden, if I try to veer to the left to get the first nitrous from the right side of the track, I usually get "rescued" and lose time.  On both, I often can be on one side  of a track, and veer suddenly toward the middle, and get "rescued", even though I would have been nowhere near driving off the side of a track.  If I try to drive over to the left to catch the first three nitrouses on Ravenbridge from the right side of the track, I'll get "rescued"; even though I would have almost certainly stayed on the road.

I noticed that in the "Troubleshooting" section of the main site, it says that any time a cart comes off the track, it gets "rescued", so the workaround is to add plygons under a zipper: [Making Tracks: Appendix A: Troubleshooting](https://supertuxkart.net/Making_Tracks:_Appendix_A:_Troubleshooting).

I submit that this is a completely incorrect theory of operation.  Catching some air time is a fun part of racing games: Are you faster if you start over a hill so fast and catch air, or slower?  I feel that the current AI for "rescue" needs to be scrapped, and something based perhaps on "Is the car off the drivable area of the track or the shoulder, to the left and the right?" instead of "Has the car caught any air at all."  It should also be over the drivable area on the part of the track it was recently on (or else cheats to jump from one section of a track to another will become a thing).

Right now, it is the #1 thing that sucks the enjoyability right out of this game.  I submit that it is entirely broken.  I suppose those expert at this game have learned elaborate routes to avoid catching any air at all.

Telling us there is a rescue button does nothing to help solve this problem.  **I suggest that until this is completely reworked, there be a Setting in the General section: "Disable Auto-rescue".**  That way, the 3X-4X per lap in Ravenbridge that are false positives are not a problem, will elicit no "rescue" for the vast majority of cases where it is not needed.  Then, the rescue button will come into its own, since for the time being, the player is much better at avoiding false positives than the AI; vs. knowing when it is truly needed.  I suggest that the AI is so bad right now, serious thought might be given to either disabling it by default, or for Intermediate + races, with a warning on the screen when choosing to start a race, that it has been disabled.

**Comment by BugZappr** [comment]
I have been testing 1.20-rc1, and the improvement is like night and day, as far as false positives.  I'm still having trouble with some of the levels on expert; but now it is not due to my keeping getting rescued.  After playing with it for several days, and completing all levels on beginner and intermediate, I've only had one false positive in all that time, once on Zen Garden, on all those curves leading to the bridge.  That's _WAAAYYY_ better than 2-4X per lap.    For all practical purposes, the problem of false positives is solved.  While I never mapped the rescue button on my controller to anything previously, I found myself needing it occasionally; instead of hating that rescue bird.  You know, this is really an awesome game; even if I'm not expert.  To judge by the graphics, the original Mario Cart looks pretty feeble by comparison.

There were some cases where I thought it should rescue me, but it didn't.  One that's easy to describe is on the Shifting Sands solo race.  If you pass the first pyramid, and go for the second one to get more nitro, I can drive to the right, off of the ramp, and drive outside the pyramid, nearly its full length before I'm rescued.  On the XR591 stage, I wish I could tell you where, I got off the track too much, and was trying to drive over a hump to get back on the track, but I couldn't get over it, even with nitro, and the rescue refused to respond.  There was another track where I could fall down somewhere, not XR591, a Gran Prix, or Fort Magma, and it didn't rescue me.  It can be improved, but whereas with these occasional rescues that don't happen, I can just restart the race, with the false positives that kept happening in 1.1, they were an every race, every lap source of huge frustration.  The RC is so much better in that regard, it's like night and day.  While it still misses some true positives, and this could be improved, with one single exception over several days, the false positives have been eliminated.  Great job!

**Comment by Alayan-stk-2** [comment]
I never experienced any particular issue with auto-rescue in 1.1, but I'm glad 1.2 RC1 is working better for you.

Some potential auto-rescue enhancements are about adding in-track rescue planes, others would be in angle/speed/movement detection, but overall what we have is working rather well.

I'm closing this issue as resolved.

**Comment by BugZappr** [comment]
A few more details: The level I could fall down and not get anto-rescued on is Antediluvian Abyss.  There's an area in the last big curve just before you get to the finish line where you can go around and around in a circle, but there's no way out without triggering rescue.  It seems it should auto-trigger there.  I've gotten maybe three false positives in Oliver's math class still, at least one making the turn just after the start - although that is still WAY better than it was.  The only other false positive I've gotten is maybe two in Zen garden, in the curves approaching the bridge.

Another curious phenomenon is that e.g. in Oliver's math class, after the start, and you make the left turn, but you then take the right turn too wide, you can end up traveling on your side along the wall for a long distance: not able to get very fast, and not being able to get out without triggering rescue.  I've had it on another level, too.  It seems if your car is running on its side, in real life, it would soon skid to a stop.  Auto-rescue seems appropriate if it happens for more than say, two seconds or so.
