### ISSUE TITLE
Issues with GP winner's podium with 3 or less racers

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3578]
## Description
The end screen of a GP has some minor issues if there were only a few racers.

* With 2 or 3 players, the last place still gets to stand on the winner's podium
* The last place also always shows the “happy” animation, not the “sad” one
* The “loser garage” is not used if you ranked last against 1 or 2 players

## Steps to reproduce
1. Play and finish a GP with 2 or less AI opponents

## How it should be (IMHO)

* If you rank last against 1 or 2 opponents, show the “loser” screen, otherwise the winner's podium
* If there are 2 or 3 players, make the last place on the winner's podium empty or sad
* If you raced alone, show the garage animation and set the caption to “You have finished the GP”

## Configuration

STK release version: 0.9.2

**Comment by Alayan-stk-2** [comment]
I don't think it make much sense to do a GP with 1, 2 or 3 karts in any case. This is possible, because why forbid the player to do this ? But when using somewhat weird configurations, there will be some suboptimal results.

Having only 1 or 2 karts out of 3 on the podium would be somewhat weird in its own way, I think. I asked for opinions on the IRC.

> hiker: Alayan: Mixed: podium might be ok, but it should show the sad animation imho 

So, probably we should change the used animation for the last place in those cases.
