### ISSUE TITLE
"Red" skidding particles don't stand out from "yellow" skidding particles

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3590]
On many backgrounds, the color difference between level 1 skidding ("yellow") and level 2 skidding ("red", now rather "orange") is not stark enough. If one is not closely paying attention (instead looking ahead, for example) the moment the kart switch from one to the other can easily be missed.

This isn't a simple visual issue, as it also affect gameplay : the very obvious difference which existed and should exist between those particles is an important cue to know when one can release the skid key and get the level 2 boost.

This issue dates back to Qwerty's PR which otherwise improved these particles look.

**Comment by Wuzzy2** [comment]
I agree, the color difference is a bit too subtle in -dev, 0.9.3 was better.

**Comment by qwertychouskie** [comment]
I like the look of the orange particles (they look like fire :), but agree that the difference is too small.  Maybe we should use two completely different colors? (MK uses blue-orange-[pink].)

**Comment by deveee** [comment]
I could make it more red, but tbh. currently it looks better. And it really depends on a kind of scene, not on the color. Also the smallest difference is when advanced lighting is disabled, because it is too bright. Maybe it could be better when using more dark and less transparent textures. Anyway I was experimenting a bit with different settings and I couldn't make it better for both enabled and disabled advanced lighting. So I would keep it as it is.

Or it's possible to make red/orange particle size slightly bigger, so it will be more different.

**Comment by Wuzzy2** [comment]
Can't you just revert to the 0.9.3 colors? Because those were just fine.

**Comment by deveee** [comment]
https://github.com/supertuxkart/stk-code/commit/0355922116c752173133d73e05ffbed0a69f4d4c together with https://sourceforge.net/p/supertuxkart/code/17943/ should make it slightly more visible.

And btw. I checked STK 0.9.3 and on some tracks skidding particles were almost not visible.

So can we close it or you need something more?

**Comment by Alayan-stk-2** [comment]
Looks better, thanks.
