### ISSUE TITLE
Crash sounds alter SFX volume for other effects (collection, horn, banana, etc.)

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3596]
See vid: https://jacobspctuneup.tk/STK/addon_stk-mercury_2018.10.22_17.21.57.webm

**Comment by Alayan-stk-2** [comment]
I can't reproduce this issue.

**Comment by qwertychouskie** [comment]
The ability to reproduce seems intermittent, but has been an issue for a while.  See https://github.com/supertuxkart/stk-code/issues/3086 which was mistakenly closed.

**Comment by qwertychouskie** [comment]
Still able to reproduce on recent master, with the pattern normal->partial volume->very low volume.  Happy to help debug if someone knows what value to add prints to, since I can often reproduce on my system.

Also, reasonably sure this wasn't present in 0.9.3.

**Comment by Alayan-stk-2** [comment]
This is a regression introduced through #2921 (which made the same sources used by a bunch of effect, creating the possibility for the bug to happen) and #2964 which sets the volume of the emitter after a crash.

This means that this issue is not restricted to situations where taking a few items quickly in a row, or anything similar. Rather, as soon as one crash happens, the associated sound emitter will be altered. If the crash was strong enough, the change won't be obvious, however if it was mild, all the sounds played later on with this emitter will have a wrong volume, until the next crash sound using the emitter change it to another volume.

It's actually a shame that this regression stayed for so long and made it into the 1.0 release, with a serious investigation I fixed it in about 2 hours, and I searched for "volume" alteration of the emitters quite late in the process.
