### ISSUE TITLE
Make mingw 32-bit compilation work without a hack or remove support for it

### ISSUE THREAD

**Issue by cddepppp256** [supertuxkart/stk-code#3608]
MinGW compilation on Linux for 32 bit should work without any hacks or off-the-road documentation, otherwise this should be removed.

**Comment by deveee** [comment]
It's not possible to fix it, because the fix breaks compilation for non-affected version. You can use debug build, angelscript with as_max_portability or 64bit build.

And remove support doesn't have a sense because it will work with newer compiler versions.

Btw. some 32bit linux gcc are affected too
