### ISSUE TITLE
Better integration for donator package tracks in networking

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3635]
For a track to be playable in a networked race, the server and all the connected players need to have the track.

Currently, the only reliable way to have a race using an addon or donation package server is to host a server yourself and only accept in other people who also have those tracks.

Servers open to anybody can have available addon/donator tracks, but it takes only one person not having them joining to disable them for everybody.

This is highly impractical, and makes the donator package tracks less attractive.

**Comment by v1993** [comment]
Here's my suggestion:

Add

    <addon-karts-threshold value="1" />
    <addon-tracks-threshold value="1" />
They are calculated this way: `number of addons installed on both client and server / number of addons on server`. Player should be able to see reqired/recommended tracks, especially if server rejects him because of this.

Another great option (with or without previous one) is to use

    <must-have-addons>
        <kart id="f-droid"/>
    </must-have-addons>
This list should be checked by server on startup to halt if it can't find one added here.

What do you think about it? Any critics will be appreciated!

**Comment by qwertychouskie** [comment]
Honestly I think the client should stream karts and tracks from the server on-demand.  Example: Server has a track called `MyCoolCustomTrack` and a kart called `MyCoolCustomKart`.  When the clients go to the kart selection screen, `MyCoolCustomKart` is there as an option, because the client downloaded the kart from the server while sitting in the lobby.  `MyCoolCustomTrack` is an option in the kart selection screen, and if that track is chosen, the clients download the track from the server during the "Loading" phase.  This will work for addon, donation, and custom server-specific tracks.  For reference, this is how Trackmania Nations Forever works.

@Benau and @Alayan-stk-2 Thoughts?  Would be great to have this for 0.10, but that may require a beta 2 (which might not be so bad IMO, gives a bit more testing time and should allow the new tracks (Black Forest and Ravenbridge Mansion) to get good real-world testing.  Maybe only implement this for tracks at first, since there's already a loading period to add the download into?

**Comment by v1993** [comment]
@qwertychouskie Was talikng with Benau before posting. He don't think that entire idea is really important.

IMO, auto-download is nice option, but have some sharp edges: first, user should be warned about addons which will be installed. At this point, if he refuse to, server rejects connection. If he agrees, he proceeds to lobby and download begins. Good idea is to download in this order:

1. Kart icons
2. Track icons
3. Kart models
4. Tracks

However, fourth part have some quirks: tracks are large, not sure if donloading all of them is good idea, but ok. At second, STK client will need only tracks for current game mode: only race/soccer/ffa/ctf arenas/tracks.

Another case is when kart/track is requested, but not downloaded yet. Kart just may don't appear when selecting. When tracks starts, selected kart/track should be downloaded immedeately if they aren't yet.

**Comment by BlueCatYellowCat** [comment]
I've been in a server of 6 where half of us are trying to figure out which player has 0 add-ons installed. I can certainly see the value in having optional add-on requirements for servers, but at the same time the userbase is so small that this could just further fragment the online experience, especially for new players who want to try online play immediately.

**Comment by Alayan-stk-2** [comment]
Not relevant anymore as we don't have a donator package anymore.

Furthermore, servers can be configured to require some tracks to be installed.
