### ISSUE TITLE
Handle special characters in passwords

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3670]
You cannot login in-game when your password contains special chars like `<`.
This was actually working some while ago and it still works on the addon-website.

**Comment by hiker** [comment]
I suspect this is triggered by c5cf87071ce3b58d94cd3253deb02452d21f4547 ("Use xmlEncode for proper unicode handling") - the last commit that changed decoding, which did:
```
-            std::string s = StringUtils::wideToUtf8(value);
+            std::string s = StringUtils::xmlEncode(value);
```
_So a '<' is first replaced by "&#x3C;", which is then curl_easy_escape()'d to "%26%23x3C%3B"

@leyyin: I assume the last one is decoded by the web site, but not the XMLEncode? I am not sure exactly which problem was fixed by the above patch. Suggestions?

I don't know

**Comment by Benau** [comment]
That commit was for unicoded server name, now i realized there is a better way to store server name in db instead of xml characters:

1. Revert this commit

2. Change to     request->addParameter("name", m_game_setup->getServerNameUtf8()); in server_lobby.cpp

3. And then in api/server.php remove utf8_encode for the name of create server request (because it's already utf8 encoded anyway)

This way you select * from v3_servers; it show chinese characters in my terminal, and make it possible to create a web server browsers (with stats) in the future, and the xmlwriter in stk-addons will write the unicode characters from database to xml when u get-all request

Or you can revert this commit now, because i don't rely on wide-char server name anymore on the request currently anyway

**Comment by Benau** [comment]
And yes revert this commit will allow special characters in password
