### ISSUE TITLE
Cocoa temple challenges are difficult

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3673]
So this is mostly a personal feeling, I’m having a tough time with the ghost race challenge for cocoa temple. While I got it now on hard difficulty, I am still struggling with SuperTux. Congrats to the ghost driver.

I feel that this challenge is a lot harder than all the others. On hard I needed 15-20 tries to win on cocoa temple while I always finished first at all other races (with less than 10 ai karts :P, the mass challenges like Around the Lighthouse and Northern Resort depend a lot on your luck). Especially on the harder difficulties it feels like you stand no chance to win if you pick a light or heavy kart against the ghost Suzanne (medium).

On easy, the goal which needs to be beaten is 3:52. I tested the track with Hexley – a light kart – without using nitro or drifting and just driving the main road flawlessly (no rescues, no crashes).
- Without using the 3 zipper items: 4:06
- Using the 3 zipper items: 3:59

For me it feels like the cocoa temple challenges should be shifted by one difficulty (i.e. easy becomes medium, medium becomes hard, …) so they are more on par with the rest of the challenges. Other opinions on this are welcome :-).

**Comment by Alayan-stk-2** [comment]
Challenges which put you against AI karts are usually somewhat easier because on expert you just have to beat the AI (no time limit makes difficulty more uniform and avoid a cake or basket ball from being too frustrating, nitro/replay challenges don't have this random element).

I'm not completely against tuning things, but this challenge also requires you to think and use the good road. Failing because you're using the wrong path is expected on higher difficulties. If you have difficulties because of the kart type, use a kart type more suited for the challenge. All karts type can complete the challenge, but of course some make it easier than others.

https://www.youtube.com/watch?v=sjjWWtihdac

The easy challenge has a ton of errors and use no skidding. Using a light kart, no nitro, no skidding, with the zippers, hitting one banana, and using mostly slow roads (the left path with the zipper is faster in easy and was used), I just got 3:48.

**Comment by Alayan-stk-2** [comment]
I made the expert challenge 1.6 seconds slower with https://github.com/supertuxkart/stk-code/commit/7dba81ec3d28d8a314c96c06d3a3b50888cb233a ; this should make it more in line with other challenges. Using the right path is important here, you can get away driving worse than the ghost if you use the good path, so I don't plan on making it even easier. Thinking what path to use is part of the challenge, and the expert ghost gives pointers in the first lap.
