### ISSUE TITLE
Some texts,bars,buttons and icons are too big or too small in 4k

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3682]
STK release version: git20190102
STK Source (PPA, distribution package, official binary, etc.): openSUSE OBS
System: openSUSE tumbleweed 20181224
Graphics card: RX Vega 64
CPU: Ryzen 7   ##2700x
![image](https://user-images.githubusercontent.com/35170687/50735469-961ccc80-11ea-11e9-8ea7-a5dd6efdb33b.png)
![image](https://user-images.githubusercontent.com/35170687/50735476-a5037f00-11ea-11e9-8ade-5b5bc8630090.png)
![image](https://user-images.githubusercontent.com/35170687/50735481-ccf2e280-11ea-11e9-875f-64e6b710d96c.png)
![image](https://user-images.githubusercontent.com/35170687/50735484-dc722b80-11ea-11e9-9a35-6b0a1228694d.png)
![image](https://user-images.githubusercontent.com/35170687/50735489-ee53ce80-11ea-11e9-922b-a2394a541815.png)
![image](https://user-images.githubusercontent.com/35170687/50735511-278c3e80-11eb-11e9-831a-316e4eed1885.png)
![image](https://user-images.githubusercontent.com/35170687/50735513-35da5a80-11eb-11e9-9750-13f6a8bd2f8d.png)
![image](https://user-images.githubusercontent.com/35170687/50735520-530f2900-11eb-11e9-9380-6301863ea558.png)
![image](https://user-images.githubusercontent.com/35170687/50735526-76d26f00-11eb-11e9-907c-7cc9ba4c88db.png)
And many many others...

**Comment by Alayan-stk-2** [comment]
None of the developers in STK's team uses a 4K screen (or an ultra-wide for that matter), so indeed there are many scaling issues for the UI at such resolutions.

**Comment by dumaosen** [comment]
Emm...Hidpi doesn't really work.
![image](https://user-images.githubusercontent.com/35170687/50767551-43114b00-12b8-11e9-931e-ca4446e4f025.png)

**Comment by dumaosen** [comment]
Thank you. I have seen those great improvements in version 20190109. But there are few problems remain.
![default](https://user-images.githubusercontent.com/35170687/51023542-216ad900-15c2-11e9-842d-7f9229272b88.png)
The bars here are too large.
![_005](https://user-images.githubusercontent.com/35170687/51024645-0e0d3d00-15c5-11e9-9634-461a6a216778.png)
The texts in loading page is too big.
![_006](https://user-images.githubusercontent.com/35170687/51024739-4f055180-15c5-11e9-92a3-06ac280878e7.png)
The titles are too big,too.
![_007](https://user-images.githubusercontent.com/35170687/51024798-78be7880-15c5-11e9-90a7-757f27944fcf.png)
The number here is too big.

**Comment by deveee** [comment]
With this patch it works fine with both 3840x2160 and 2560x1440:
```
diff --git a/src/font/font_with_face.cpp b/src/font/font_with_face.cpp
index 2af164d36..d1f6502a2 100644
--- a/src/font/font_with_face.cpp
+++ b/src/font/font_with_face.cpp
@@ -358,6 +358,11 @@ void FontWithFace::setDPI()
         float scale = screen_height / 480.0f;
         m_face_dpi = int(getScalingFactorTwo() * getScalingFactorOne() * scale);
     }
+    else if (screen_height > 1300)
+    {
+        float scale = screen_height / 480.0f * 0.75f;
+        m_face_dpi = int(getScalingFactorTwo() * getScalingFactorOne() * scale);
+    }
     else
     {
         float scale = std::max(0, screen_width - 640) / 564.0f;
```
Basically it's the same as hidpi on android, just smaller factor is used.

And here is how it works with 3840x2160:
![zrzut ekranu z 2019-01-11 20-55-25](https://user-images.githubusercontent.com/5108558/51056790-1628a500-15e4-11e9-9653-1096a6c57f4c.png)
![zrzut ekranu z 2019-01-11 20-55-36](https://user-images.githubusercontent.com/5108558/51056794-19239580-15e4-11e9-93ad-b8f9472f0c60.png)
![zrzut ekranu z 2019-01-11 20-55-42](https://user-images.githubusercontent.com/5108558/51056804-1d4fb300-15e4-11e9-9638-f383eefcb2d8.png)
![zrzut ekranu z 2019-01-11 20-55-50](https://user-images.githubusercontent.com/5108558/51056808-1fb20d00-15e4-11e9-9a67-98f48a711d57.png)
![zrzut ekranu z 2019-01-11 20-56-26](https://user-images.githubusercontent.com/5108558/51056811-217bd080-15e4-11e9-8fab-3d1c85cdf0f1.png)
![zrzut ekranu z 2019-01-11 20-56-51](https://user-images.githubusercontent.com/5108558/51056824-293b7500-15e4-11e9-8300-5f0dcdf590f4.png)

IMO for STK 0.11 real font size shouldn't depend on resolution. Why should I get different results depending on resolution on the same monitor? So that font size should be fixed % of screen height and ideally we should read DPI from system and adjust the font size in reasonable range.

**Comment by Alayan-stk-2** [comment]
> IMO for STK 0.11 real font size shouldn't depend on resolution. Why should I get different results depending on resolution on the same monitor?

If using a small resolution in windowed mode, we still want text and data to fit. But what's optimal to have things fitting in 1280x720 is not in 1920x1080, not to say on a 2560x1440 one.

But I'd agree that pure direct scaling isn't ideal either, with a bigger resolution you'd like to pack some more information too.

I'd like to make resolution and font size less tightly coupled, but we need to think about consequences before going ahead with changes.

**Comment by deveee** [comment]
I suppose that most people play in fullscreen or maximized window. But in windowed mode you know your desktop resolution, so you can compute font size. And 800x600 in windowed mode on full-hd monitor will be different than 800x600 on 4k monitor.

**Comment by dumaosen** [comment]
The text problem has been fixed by myself.
See https://github.com/supertuxkart/stk-code/pull/3791

**Comment by dumaosen** [comment]
Since deveee committed his patch, 2k and 3440x1440 are totally fixed, and 4k does better. But 4k has such a big text that makes small space between texts and button edges and they looks ugly (see the screenshot). So IMO those buttons and bars should be bigger.
The ultra big-text speedometer and musicinfo should also be smaller.

**Comment by dumaosen** [comment]
See https://github.com/supertuxkart/stk-code/pull/3881

**Comment by dumaosen** [comment]
Ok close it.
See https://github.com/supertuxkart/stk-code/issues/3792 for problems which haven't solved.
