### ISSUE TITLE
Wiiuse is build as shared library

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3696]
Probably should be changed to static with BUILD_WIIUSE_SHARED_LIB=0 to restore previous behavior.

**Comment by hiker** [comment]
Yes, I stumbled over that last night, and had to repeat everything ... build, installer, install test, uninstall test *sigh*, since it broke the 'uninstall' feature :(

We should probably do both: improve uninstaller to remove the wiiuse files if they are there, but also restore the previous behaviour.

**Comment by hiker** [comment]
Fixed in 2d219f29cc24f09fd67698498503f2ecd8edde64. Besides changing the default, it also fixed uninstall issues that existed before.
