### ISSUE TITLE
Farther objects display badly when the graphic level is five or six

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#3709]
STK release version: 0.10beta2
STK Source (PPA, distribution package, official binary, etc.): sourceforge
System: Android
Graphics card: Mali-G72
CPU: kirin970

**Comment by deveee** [comment]
Depends on your phone, but typically it may be /sdcard/Android/data/org.supertuxkart.stk_beta or the same path on internal storage.

@Benau Yes it's possible to check if extension exists. But in this case I would drop android 4.4 support, because it's buggy. Even on my tablet with android 5.0 simple extension with bgra format doesn't work correctly. 

And on nvidia probably even texture compression would work. And there are more devices that support GLES 3.2.

**Comment by Benau** [comment]
It should be fixed in #4533 ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance3.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance4.gif)
