### ISSUE TITLE
Nitro cans disappearing after restarting a race

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3750]
Steps I followed when the issue happened : 
- Go in the Fort Magma final challenge at expert
- Let Nolok take a lap over me
- Proceed to race and lose
- Retry the challenge

At this point, nitro cans are now missing. The steps above may be coincidental (I couldn't reproduce on a second try where I raced normally however), but there is definitely some conditions under which nitro cans are despawned from the track.

Exists in 0.9.3 (see https://www.youtube.com/watch?v=V7P5adiOar4 ) and current master.

**Comment by Benau** [comment]
https://www.youtube.com/watch?v=hklz1ibqCU4

If u switch 2 times quick then the switched bubble will never come back, and then u restart the race all bubblegum is gone because if((*i)->canBeUsedUp() || (*i)->getType()==ItemState::ITEM_BUBBLEGUM) deleteItem( *i );
```
        if ( (*i)->getType() == ItemState::ITEM_BUBBLEGUM ||
             (*i)->getType() == ItemState::ITEM_BUBBLEGUM_NOLOK)
        {
            if (race_manager->getAISuperPower() == RaceManager::SUPERPOWER_NOLOK_BOSS)
            {
                continue;
            }
        }
```
7 year ago!

easy fix is to remove the above
