### ISSUE TITLE
Wrong scale for many widgets in rotated screen.

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#3754]
And they ALL have scaling issue.
![_ _20190215172930](https://user-images.githubusercontent.com/35170687/52847533-719c0480-3147-11e9-890d-d5c5789d5a2a.png)
![_ _20190215172946](https://user-images.githubusercontent.com/35170687/52847536-72cd3180-3147-11e9-91a2-81e6d43e59ab.png)
![_ _20190215173006](https://user-images.githubusercontent.com/35170687/52847626-aad47480-3147-11e9-9fc0-025a30c8be03.png)

**Comment by deveee** [comment]
Sure these resolutions have scaling issues and are not really supported. But what's weird there? Do you suggest eg. 1920x1200 rather than 1200x1920?

**Comment by dumaosen** [comment]
They are just a bit abnormal for me... BTW should I change the title?

**Comment by deveee** [comment]
Actually there are at least two different cases... You may want to use these resolutions in fullscreen or in windowed mode.

I think for fullscreen it has a sense, because it's real dimension of a window.

For windowed mode indeed in theory you can open 1920x1080 window on a 2160x3840 screen and play with horizontal window. But for smaller full-hd monitors, you would be able to open only 1024x768 window, so other resolutions would be useless...

And anyway GUI should be much more flexible and font/buttons size should depend on DPI.

**Comment by CodingJellyfish** [comment]
And this issue also appears on foldable phone.
