### ISSUE TITLE
Add a quitted races count to ranked server stats

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3774]
An additional field to keep track of how many times a player disconnected from a ranked race before its end would be useful to adapt the ranking points penalty.

If the proportion of disconnects compared to total races done is below some threshold, like 3%, the ranking points loss could be smaller (as if the player had finished last with the time of the slowest person to finish the race), and if over this threshold scale up to the maximum ranking punishment for disconnects which would be the current one.

This way, an accidental disconnect for an honest player would be less punitive, while still fighting rage quits effectively enough.

**Comment by Fouks0** [comment]
I would suggest to cap the changes to like max +/- 20-30 points as well... Losing like 50-100 points because of disconnects or technical problems like laps that are not counted is pretty harsh...

**Comment by eltomito** [comment]
I suggest everyone is allowed to disconnect mid-race once a day without any consequences to their points, i.e., the ranking system pretends the player never entered that race. These disconnect passes don't accumulate over time, meaning you start every day with exactly one quit pass and you end the day with either 1 or 0 quit passes left.

Because why do you disconnect from a race? Because of
1) lag
2) rage
3) intrigue
4) the real world: your cat jumping on the computer or clawing your ass, the delivery man ringing the doorbell, stuff burning on the cooker...

IMO people shoudln't be penalized for 1 and 4. So, let's say things like that can happen once a day. Then you already know you have to fix your wifi before playing again, put the spaghetti off the cooker, etc.

2 and 4 should be penalized but come on, we can allow for one fit of rage a day!

Also, I think a disadvantage of the proposed 3% mechanism is that the way your quitting the race affects you changes over time. If you quit five times in your first 50 races, you get penalized for those incidents but as you keep racing without quitting, these past incidents are re-evaluated and your score magically improves. While this maybe a minor point, I still prefer the situation when the result of a race is decided for good when the race finishes.

**Comment by Alayan-stk-2** [comment]
If you give a free disconnect to people, then there is an incentive to use it when you're doing badly, to avoid losing rating points. This would also deny your rivals of rating points for that race.

Issue 4 is really on the player. Don't play ranked if you're likely to be disturbed. Random disturbances can still happen but are very unlikely (<1%) if you take some care.

Issue 1 can never be fully addressed.

**Comment by Benau** [comment]
it's now implemented... ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
not sure fouks wanna use her in ranked....: ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)
![rtt](https://user-images.githubusercontent.com/3252341/91211683-c14a8b80-e741-11ea-97c3-3568d21ad70b.png)
or...
![rtt](https://user-images.githubusercontent.com/3252341/91211844-fb1b9200-e741-11ea-837f-1ea436917ba6.png)

not sure ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) can ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) duda tonight ![](https://cdn.lihkg.com/assets/faces/mouse/please.gif)
