### ISSUE TITLE
Auto-update for SuperTuxKart on PC (Windows, MacOS, and Linux Variants)

### ISSUE THREAD

**Issue by jebeld17** [supertuxkart/stk-code#3785]
With programs such as SuperTuxCart being constantly updated in GitHub
----- 
… as code improves and security and performance issues are patched, it's crucial to get these updates rolled out to the general public as quickly and seamlessly as possible to ensure a quality program experience.

From the best of my knowledge, I do not see an auto-update feature Implemented in STK (I could be wrong, as I haven't looked in the code itself). If there isn't one set in-place at the moment, I'd love to see an auto-update feature added into STK - one that can be turned on/off and edited within the program settings.

TL;DR:
-----
Please add an auto-update feature to SuperTuxKart for PC.*
*PC: Windows (Win32 STK binaries), MacOS, and Linux variants, minus Android and Android forks due to app update policy restrictions.

**Comment by Arthur-D** [comment]
So you're afraid of security vulnerabilities but think it's a good idea to download code updates from within the game?

**Comment by qwertychouskie** [comment]
I am a firm believer in having some sort of update notification, but I don't think security really is applicable to a video game.

**Comment by BlueCatYellowCat** [comment]
An update notification rather than an auto-update would be a great option.
Security is certainly applicable to video games, especially now that STK is receiving data over the internet (ie. online mulitplayer and add-ons).
Xonotic had a confirmed virus that messed with people's games (https://forums.xonotic.org/showthread.php?tid=6261). STK has a few advantages (userbase is likely small enough not to attract professional attackers, less Windows users [they are a more accessible target], we don't use powerful anti-cheat programs with dangerous privileges [popular ones on Windows run as root and install a kernel module]), but nonetheless we still should be somewhat careful when dealing with server interaction and potential of malformed add-ons.

**Comment by qwertychouskie** [comment]
Good points.  Maybe it's time to resurrect https://github.com/supertuxkart/stk-code/pull/2924...

This time let's get it right. :)

@Alayan-stk-2 I opened https://github.com/STK-helper/stk-code/projects/3, I'll try to at least re-base the old code today.

**Comment by Arthur-D** [comment]
I think aggressive update notifiers like that should only happen when people go to play online. Let people have their offline stuff in peace, with a discreet notice at the bottom (like we have now).

**Comment by hiker** [comment]
We already have the option to publish a message that it shown in the scroll bar (which we can control on the stk server). We can also push a message that will pop up a window if required.

**Comment by qwertychouskie** [comment]
I agree that update notifiers shouldn't be aggressive unless absolutely necessary.  The first time I didn't implement silent auto-updates as an option because Steam was "coming soon", won't make that mistake again :P

**Comment by Arthur-D** [comment]
We don't even want that, and as for the rest, see hiker's reply: it's already in place if we want to use it.

**Comment by jebeld17** [comment]
Why not use it?
It's already there. It can't hurt.
