### ISSUE TITLE
UWP-ify SuperTuxKart as a Microsoft Store app

### ISSUE THREAD

**Issue by jebeld17** [supertuxkart/stk-code#3786]
**Before reading please note that I *did* search for "UWP"-related bug reports or suggestions in the threads, but I could not find anything.**

With Microsoft making Universal Windows Programs a big importance for newer iterations of Windows 10, it is about time SuperTuxKart steps up and joins the likes of Inkscape and Krita who have already converted over to UWP/Windows Store Apps.

UWP is the way to go - for Windows at least - because it offers developers a really good bridge between app functionality and what the developers want with guaranteed acceptance by the OS (once the UWP port passes through Microsoft's stricter QC departments.) Not only that, but using UWP apps guarantees users to get the latest up-to-date variants of their software for his or her device as soon as it is released without the risk of requesting tons of permissions or the user ignoring the upgrade.

Microsoft has their entire Win32 to UWP process well-documented and available for everyone to see here: https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by Alayan-stk-2** [comment]
I'm personally against this.

I'm happy with SuperTuxKart being multiplatform and available on Windows as well as on Linux and other OSes, but UWP is not about multiplatform support.

The microsoft store is an attempt to lock down the windows application ecosystem (which is why there is this stripped down windows lite version supporting only UWP applications that Microsoft is trying to push), something which I am strongly against.

STK being free, concerns like Microsoft wanting to take its money cut for UWP programs are irrelevant, but I see no reason to devote developer time and energy for this.

Microsoft not nagging the user when the software wants to update is not relevant either because STK doesn't do many small incremental public updates and has no auto-updater.

And yes, similar concerns could be raised about the google app store (which is why having STK on F-Droid is nice), but while the smartphone ecosystem is already quite locked down, this is not the case for the desktop/laptop one, and I see no reason to want it to become so.

The "guaranteed acceptance by the OS" is the kind of argument which irks me, because if an OS ever blocks STK, it's that OS which has a big problem, not STK (and I laugh at Microsoft QC. Didn't they fire their QA for Windows leading to the "update deleting files" disaster a few months back ?).

**Comment by qwertychouskie** [comment]
Agreed.  The only case where UWP could be useful is a theoretical port to the Xbox, but then you need to use ANGLE to translate GLES to D3D, which introduces performance penalties.

**Comment by BlueCatYellowCat** [comment]
>and what the developers want
Let's ask our developers if that is what they want instead of making unfounded assumptions.

I don't think "other open source projects are doing it" is a valid argument. Also, I agree with Alayan-stk-2's post.

**Comment by BlueCatYellowCat** [comment]
>and what the developers want

Let's ask our developers if that is what they want instead of making unfounded assumptions.

I don't think "other open source projects are doing it" is a valid argument. Also, I agree with Alayan-stk-2's post.
