### ISSUE TITLE
For some addon tracks laps are not counted at all

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3787]
## Description
For some addon tracks (for example "The Ring of Sand" or "The Rock") in git version no laps are counted but it works on 0.9.3. I guess this came with the changes to lap line validating. But those changes should not break existing tracks.

## Steps to reproduce
Start a race on "The Ring Of Sand" or "The Rock"
There isn't even a lap counter when you start a race.
When you finish a lap nothing changes.
You can't finish the race

## Configuration
STK release version:  current git and 0.10 beta

**Comment by Alayan-stk-2** [comment]
It's on the addon to provide properly working lap validation. All sensibly designed tracks kept working.

The issue in "The Ring of Sand" and I guess in "The Rock" is that the kart is _never considered to be on the road_ (not the same as "on the ground"), likely because the drive graphs are way below the road itself, and the kart is associated with a track sector by interpolation.

Feel free to try and improve the code determining whether a kart can directly be associated with a track sector or if it must go through interpolation (this could also slightly improve things for e.g. replay timer in the cornfield crossing cannon), but a code change exposing an addon track design flaw is not ground  for an issue here.
