### ISSUE TITLE
Finishing Cocoa Temple on Expert, then on SuperTux does not give you the treasure chest screen

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3823]
## Description

Story Mode. If you have won the gold cup in Cocoa Temple and then play the challenge again, but this time on SuperTux and you win again, then there will be no extra screen showing that you have won a new challenge.

## Steps to reproduce

1. Reset progress of Cocoa Temple (Story Mode)
2. Win this challenge on Expert level
3. Win it on SuperTux level

EXPECTED:
You first get a win screen for gold, then you get a win screen for platinum.

ACTUAL:
You get a win screen for gold, but nothing for platinum. After you complete the SuperTux challenge, you just get the normal race result screen but the only options are restart and quit to Overworld. There is no treasure chest screen.

## Configuration

STK release version: 0.10-rc1
STK Source (PPA, distribution package, official binary, etc.): Git

**Comment by Alayan-stk-2** [comment]
I can reproduce this issue : 
- The unlock screen doesn't appear when doing the steps to reproduce
- When doing similar steps for another challenge (I tested math class), the SuperTux win correctly trigger a new unlock screen showing the platinum cup.

**Comment by Wuzzy2** [comment]
Note that Cocoa Temple is a ghost race, so maybe the bug is related to the race type.

**Comment by Benau** [comment]
That's because the challenge has suzanne unlocked and it can only be unlocked once,

if (p == m_locked_features.end()) return will "void" the chest screen in story_mode_status.cpp:269

math class challenge works because it has nothing to unlock, and (unsigned int)c->getData()->getFeatures().size() is 0 for it.

you don't have the chest screen reshown for any challenge that has something to unlock if you re-play it in other difficulty

may not be so easy to fix... 
we can have something like
```
            if (m_current_challenge && m_current_challenge->isActive(d) &&
                !c->isSolved(d))
                m_unlocked_features.push_back(c->getData());
```
in if (p == m_locked_features.end()) but it will keep re-show suzanne as unlocked kart, alayan what do u prefer / just postpone?
