### ISSUE TITLE
Extreme shortcut in Nessie's Pond

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3826]
In Nessie's Pond there's an extreme shortcut. After the 2nd turbo in that tunnel, just leave the road to the right and drive on the grass, over the river and to the finish line. To get over the river, you have to be rather fast, however.

(Ab)using this shortcut is a dominant strategy in online games, sadly.

## Configuration
STK release version: 0.10-rc1

STK Source (PPA, distribution package, official binary, etc.): Git

**Comment by deveee** [comment]
+1

**Comment by auriamg** [comment]
I have modified the track in SVN to prevent this shortcut. The river is now much wider and should be impossible to cross

**Comment by Alayan-stk-2** [comment]
The track is very dull now that this shortcut has been removed. In ranked races, I'd definitely quit the server rather than play it.

This is a core issue we have with track voting, unbalanced skills and a wide spectrum of track difficulty, the rankings which would result from playing the 10 hardest tracks is noticeably different than from the 10 easiest. Being too attached to virtual points isn't healthy, but it would be nice to find a method to remove incentives of picking a lot some tracks over others... The only method I'm seeing is in the realm of "overkill/too complicated", making use of per-track data.

**Comment by deveee** [comment]
I think that Wuzzy's comment for other shortcut has a sense:

> I am in generally against such shortcuts, they make the game too cheaty and unpredictable. They move the dominant strategy away from the real track, forcing players to always take the shortcut, making the proper track useless in actual gameplay.

For me it's bad when you must use shortcuts to win. It's also competition between people and using shortcuts is unfair.

**Comment by deveee** [comment]
I agree with Snow Peak though. It's now too easy to miss checkline and you even won't be notified about it.

**Comment by Alayan-stk-2** [comment]
> For me it's bad when you must use shortcuts to win. It's also competition between people and using shortcuts is unfair.

You might be surprised by the shortcut the first time you see it used, but after a few times you know about it and can learn to use it (which in my book makes it fair), and unlike e.g. the "rescue" shortcuts, it didn't break the gameplay.

It certainly was wacky, but it added an element of difficulty in a track which otherwise is too easy. I don't miss that shortcut because of offline play against AI, i miss it because in online races it _enhanced_ competition. Without it, there is no spot where a decent player has a significant likelihood of doing a costly mistake, and it gets mostly about nitro/items, as the differences in trajectories and skidding are less significant.

**Comment by Wuzzy2** [comment]
Note the shortcut was very, very crappy, it is obvious it was NOT intended by the track designer. Please keep this in mind before jumping in to defend it.
The shortcut path is very ugly, low-poly and also buggy as you just into the river and through the map if you were too slow. That's not difficult, just random and annoying. IMO this is the worst shortcut in the entire game.

If you seriously argue in favor of the shortcut, keep in mind the difference is EXTREME, to the point it makes it a dominant strategy. If you drive on the normal road, you lose. So you are forced to take the shortcut and always ignore the normal road. Then why having the road around the lake if it's pointless?
So, if you still are defending the shortcut, it seems it would make sense to make it “official” and no longer a shortcut, but official part of the track. Seems like you are actually proposing a major track redesign here.

Personally, I still like the track in general, with or without the shortcut, but you notice how old it is; it needs a complete overhaul.

**Comment by Wuzzy2** [comment]
IMO shortcuts that skip basically a quarter of the track should not exist at all.

**Comment by Wuzzy2** [comment]
I can verify the bugfix. Thank you.

Now this issue has gone off-topic. I suggest you post your concerns in new issues.
