### ISSUE TITLE
Excesive graphics resources: cpu overheat

### ISSUE THREAD

**Issue by AlmuHS** [supertuxkart/stk-code#3892]
## Description

In the latest version of STK, the graphics produce overheating in my PC. 
Playing a online game with STK 1.0, my cpu reach 100 degrees after a few minutes.

I reduced the graphics quality to lowest, but the problem continues.

## Steps to reproduce

- Download STK for Linux [here](https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.0/supertuxkart-1.0-linux.tar.xz/download)
- Extract in your personal directory
- Execute `run_game.sh` to run the game
- In the game, open a online server, and start a standard race with other players.

## Configuration

STK release version: 1.0
STK Source (PPA, distribution package, official binary, etc.): GitHub release

System: Debian GNU/Linux 10
Graphics card: Intel graphics
PC: Lenovo Thinkpad x230
CPU: Intel i7-3520M (4) @ 3.600GHz

**Comment by qwertychouskie** [comment]
This sounds like an issue with your hardware, not STK.  Use compressed air/canned air to blow any and all vents on the laptop.  If that doesn't work, make sure all your fans still work and consider replacing the thermal compound on your CPU.

**Comment by AlmuHS** [comment]
In previous version (0.9.3), I can play without this problem, reducing
graphics level. But in this version (1.0), reduce graphics level don't
solve my problem.

**Comment by Alayan-stk-2** [comment]
Online multiplayer races are significantly more CPU-intensive than local races, so a 1.0 online race will make your CPU work harder than a 0.9.3 local race. I would guess that's why things seem worse with 1.0 (your steps to reproduce mention doing online races).

Laptop CPUs are notorious for having issues with proper cooling (and as qwerty said, accumulated dust often make things worse), especially with this being a "35W" part (high power for a laptop).

Of course STK could be optimized to improve performance (which would reduce how much the CPU is used). And we'd like to optimize it of course, though this will take time. But that high CPU usage result in overheating isn't an issue in STK itself.
