### ISSUE TITLE
Players can spam the chat with very long messages, making lobby and gameplay unusable

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3893]
## Description
Players can spam/flood the chat with very long messages. This has the following effects:

- In lobby, chat becomes unreadable. Others are basically deprived of their speech
- In game, the chat overlay becomes very large and covers half of the screen. The game becomes very difficult, it's like having a plunger in your face, but for the entire race.

## Steps to reproduce
- Play online
- Write very long messages
- Congratulations! You are now a master troll and hated by everyone

## Workaround

Immediately kick players that abuse the chat.

## Configuration

STK release version: 1.0.0

## Possible fixes

1. Limit effective chat message length, both on server and client side.
2. Limit the size of the chat overlay in the GUI. Make sure it only covers a small part of the screen and that GUI does not break down, no matter the input. Maximum size be two lines. Cut off any text beyond that.
3. ???

**Comment by UnMe0w** [comment]
Yes, the layout is completly broken when it mess up with this: 
`testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest`
![Capture du 2019-05-01 18-35-32](https://user-images.githubusercontent.com/30691126/57028692-07700780-6c40-11e9-8a33-ca2b6865c18d.png)

**Comment by BlueCatYellowCat** [comment]
Maybe instead of trying to autoban users for long messages or frequent messages, the chat feature could have a character limit and a frequency limit (the server could enforce the same, in case some troll wants to replay chat packets to circumvent client-side limiting)

**Comment by BlueCatYellowCat** [comment]
It might also be worth (if not done already) limiting characters so newlines can't be spammed, etc..

**Comment by sgreene570** [comment]
Would it be possible to word wrap text without spaces, say if you were sending a url or other string in chat?

**Comment by dumaosen** [comment]
See https://github.com/supertuxkart/stk-code/issues/3781

**Comment by UnMe0w** [comment]
Or allow scrolling to previous messages

**Comment by Wuzzy2** [comment]
This issue is !!!NOT!!! just about word wrapping! Word wrapping is just a part of it.
It is also about that players can send very loooong messages that cover the entire screen. Just try repeating the same word over and over again.

**Comment by god286** [comment]
I think there could be a system that detects if the text is touching the edge of the chat. Then,  if so, open a new line.

**Comment by BlueCatYellowCat** [comment]
> I think there could be a system that detects if the text is touching the edge of the chat. Then, if so, open a new line.

As Wuzzy2 said, that is not the issue. Word wrapping (the name for what you suggested) has already been discussed.

The issue is that I can send messages to you while you are driving and they will show up on your screen. If I make long messages that cover multiple lines, it will cover the screen and block your view of the road.

**Comment by laikokseong** [comment]
###

**Comment by dumaosen** [comment]
Benau recently added something to avoid long message in game. Have a try!
Also i think we should add a max chatting frequency per player in serverconf

**Comment by Alayan-stk-2** [comment]
This should be much less of an issue now.

The height of the in-race chat is limited to 3 lines (5 earlier on, and unlimited at the time this issue was opened), and one can chose to keep the lobby chat on but the in-race chat off.

Keeping open because some frequency-limiting on message sending would be useful.

**Comment by dumaosen** [comment]
Hey there is an another possible way to spam, because the freq-limiting system isn't completed.
I have 2 accounts, and I can have doubled chat frequency. Also a lot of  individual spammers can create such thing too.
IMO there should be a general frequency and individual frequency. If all players' chat is more frequent than general frequency kick all players.
