### ISSUE TITLE
best_while_slower: Make visible in GUI?

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3897]
STK 1.0.0.

`best_while_slower` is a secret and hidden award (in `players.xml`) and is given if you complete a Story Mode challenge in a non-SuperTux difficulty but beat all the requirements in SuperTux level. It does not work for GPs.

It is completely secret and invisible to the player. The only moment the player sees any effect when the SuperTux difficulty unlocks early. Yet the whole Story Mode has been secretly designed around the idea of `best_while_slower` and has apparently been even balanced towards it.

So STK has a fully balanced, tested set of challenges that the player is completely left in the dark of. Maybe a missed opportunity?

Since `best_while_slower` is an unique challenge, what do you think in actually exposing it in the GUI and making it an actual award the player can get? Visibly, not secret anymore.

Ideas for exposure in GUI:

As icon, use a golden star.
In the minimap, overlay a small golden star above the cup.
In the challenge screen, display the golden star at the top right corner. If you move the cursor above this symbol, show a tooltip that explains what it means.
If the player gets this award the first time, also spawn the “unlock treasure chest screen”. A golden star is in the chest (if modelling the star is not feasible, skip this step).

**Comment by BlueCatYellowCat** [comment]
I think exposing it the first time a player gets (via the treasure chest) it is certainly a good idea, because that means they are the type of player who would benefit from this feature.

**Comment by Alayan-stk-2** [comment]
This was added in only to allow the early SuperTux unlock, so that good players aren't forced to do all challenges twice to get the platinum cups.

> Yet the whole Story Mode has been secretly designed around the idea of best_while_slower and has apparently been even balanced towards it.

I wouldn't say it like that. I chose the SuperTux time requirements so that it is possible to beat them in Expert with some reliability, but this was also a convenient proxy to get a similar level of difficulty across the challenges (except the Cocoa Temple one it seems). If I had put the SuperTux challenges at a level which is as difficult for me as getting a best_while_slower right now, it would have been too difficult for many decent players.

I see some issues with making this more visible : 
- If you want to get all "best_while_slower" and all platinum cups, you need to do all the challenges twice. Which rather go against the initial goal...
- While SuperTux challenges are doable for a player who doesn't crash a lot and use skidding reasonably, getting a best_while_slower usually requires a more advanced control level. I anticipate complaints already about it being too hard (though only showing it if this has been done in at least one challenge would partially offset this concern).
- I think it's nice to have some "secrets" elements in the game, things which can be discovered but only if you search (or read about them).

**Comment by BlueCatYellowCat** [comment]
> I think it's nice to have some "secrets" elements in the game, things which can be discovered but only if you search (or read about them).
I can appreciate that. I remember a game which gave bonus secrets in the instruction manual which couldn't be found in the game's tutorial. It's a nice easter egg. Also, it could be disheartening to expose it to the player immediately as a part of the story mode.

> I anticipate complaints already about it being too hard
I personally feel that if the challenge is insignificant and optional (clearly not required for a '100% completion') and is not revealed to novice or intermediate players, then saying it is too hard is the player's own problem (and I say that as someone who most likely could not complete such challenges yet).

CoD MW2 had a feature in Spec Ops mode where once you beat a level on Veteran (equivalent to Expert) difficulty, it reveals a line of text showing "IW best time" for that level, the record time of completion achieved by the game's developers before release. (in one extreme case, the est. completion time is 1:30.00s, the [IW best time is 14.10s](https://www.youtube.com/watch?v=_tzQfmXYR5Y)).
This makes it effectively a bonus challenge that is entirely optional. You never need to beat one of these times, but once you have shown that you might be capable, the game lets you know about it. However it leaves you with something challenging even when you have completed the game, without having to go online and compete with the speedrunning gods who have been perfecting their skills for years.

I am indifferent about this feature being exposed to the user, either way is fine. It's nice to have secret features and it leaves a cleaner GUI. It is also nice to have extra in-built challenges to keep experts interested.

**Comment by Wuzzy2** [comment]
I agree this should be exposed very late in the game. It should be kind of a secret, still. New players should not be told that this is a thing for obvious reasons.

I'd say just say the player got the `best_while_slower` award as soon the player got it but otherwise give absolutely zero indication that such a thing exists in the game. As a kind of “easter egg” / “secret”. Or maybe maybe reveal that this challenge exists after having gotten all SuperTux cups. I like the idea of CoD MW2.

Another reason why I think this should be exposed is because of the SuperTux unlock. You don't really know how many “best_while_slower”s you have already (and for which challenges). But if you aim for a fast SuperTux unlock, this information is crucial.

**Comment by Alayan-stk-2** [comment]
This was done in commit b23246f

Further exposure in GUI could be considered, but for now notifying the user when he achieves the goal is sufficient.
