### ISSUE TITLE
STK might force-end short online races too fast 

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3908]
## Description
If you play online a race with short laps (for example, Oliver's Math Class) and the first player finishes the race, STK will force-end the race very fast, only a few seconds.

The other players have not much time to reach the finish line, so they will be ranked quite arbitrarily. It can happen that half of the players are not able to finish because of this.

This can be quite frustrating for new players.

## Steps to reproduce
- Play Oliver's Math Class online
- Be last
- Fail to finish because STK force-ends the race

## Suggestions to improvement
Give other players more time to finish. There are multiple ways to achieve this (discuss).

The easiest idea I have is to simply wait at least for a hard minium time after the first player finished. Maybe 30s-60s.

Another idea is to start the final countdown not after the first player is done, but maybe after the 2nd or 3rd (rank can be changed according to number of players).

Optional: What would be interesting is to additionally display that final countdown timer somewhere, as soon it starts (or only if there is less than 1 minute left).

## Configuration
STK release version: 1.0.0

**Comment by Alayan-stk-2** [comment]
The default auto-end is at 15 seconds + 25% of the first's finish time. 1 minute for the first : 1m30s to finish before the auto-end. 2 minutes : 2m45. 3 minutes : 4 minutes.

**Comment by qwertychouskie** [comment]
Not sure why this is closed...  It's not crazy to expect that a not-so-experienced player might finish more than 30 seconds behind an experienced one, especially if they got a few cupcakes/bolling balls.

Maybe a better solution would be "45 seconds or 35%, whichever is greater".  This would ensure short races have the time they need, without having it too long or too short for longer races.

As a stop-gap, current ranked servers should try 30sec+25% instead of the default 15sec+25%.

**Comment by Alayan-stk-2** [comment]
Auto-end has two purposes : 
- Making sure that malicious abuse can not prevent the race from finishing
- Making sure that those arriving early do not spend an unreasonable amount of time waiting instead of racing.

With 20-30s of kart and track selection, up to 1 minute of lobby waiting, and some seconds (if someone doesn't click, it's up to 15-20s I think ?) with the result screen, if you make the wait after the race longer, it can get quite annoying because the proportion of time spent playing gets too low.

The auto-end time is composed of a fixed duration and a relative one because it is more adapted than having entirely one or the other : in short races, the relative impact of a crash, or a cake, etc. is bigger. And when people are very close at the start, there will always be events making the differences bigger because it's impossible for close karts to not hinder each other. There is a minimum of time difference that happens naturally, and the % difference between 1st and last will usually be bigger in very short race. But of course a fixed duration is either way too big for a short race, or unsuited for a long race. A common example is 3 laps of Black Forest. It takes usually upwards of 4 minutes to complete for the 1st, and anything less than a minute of delay (with the current formula it's 1m15s) would be too short. The relative part can address this.

Is 15s+25% the ideal formula ? Maybe not, but it does its job quite well.

> STK will force-end the race very fast, only a few seconds.

Should not happen unless the server-owner has changed the formula (iirc it's a configurable server option with default values, not something hardcoded). If a server owner put 0 for the fixed duration part, I could see it being quite annoying for short races.

If the auto-end time was generous enough that a newbie crashing repeatedly would have the time to finish even on technical tracks while good players were in the race, it wouldn't serve its purpose correctly.

Also, auto-end is fair when it comes to players relative position (if you know that the auto-end will trigger, you might use some nitro sooner, but otherwise the person having raced better will usually be ahead). The estimated time formula at the end is harsh in 1.0 in that someone having almost finished may get a significantly higher time because of a laggard (and in ranked races, the points lost/won depend on the finish time) but I've already patched this issue in the current master.

**Comment by Wuzzy2** [comment]
OK. I totally get why this was added in the first place. I agree that long waiting times are not good. So I am not at all against the early ending of races as such. My point was just that STK is sometimes way too agressive.

Seriously, have you ever played OMC online? Especially with many laps? The game ends ridiculously fast. Especially if it's played with many laps and the distance between karts increases (way more than 15s).
Sadly, you didn't address my concern that the early race end could mean that HALF (!) of the players might get kicked out. That seems like a problem. It's OK if the race ends early if the slowest players can't finish anymore, but not for half of the players at medium speed.

So it seems it's only a problem for very short tracks.

I also disagree that the estimated time is always fair. For tracks that split, the times can differ at ridiculous levels. For tracks that split or with shortcuts, your rank may go all over the place. Extreme example: Cocoa Temple: You rank can go down to last place (temporarily) if you decide to take the secret shortcut before the temple. Therefore, I think its better for STK to be less agressive in force-ending the race.

Also, note that Alayan is probably biased here because Alayan almost always wins. ;-)
