### ISSUE TITLE
Save story progress permanenty

### ISSUE THREAD

**Issue by FinixFighter** [supertuxkart/stk-code#4086]
Description: When a registered user starts the story mode, the progress is saved so that when you reopen STK you can resume the game where you left it. But this doesn't happen if you uninstall and reinstall STK, nor if you log in from another computer. I think that if a user has an account, story progresses should be saved permanently, so that you won't have to replay all the story battles in order to unlock tracks for playing with friends.

Steps to reproduce:
Log in the game, start story mode and win a race (one is enough). Reinstall STK or log in on another computer. You'll see that progress aren't saved and you have to repeat the races that you've already won.

**Comment by Alayan-stk-2** [comment]
SuperTuxKart doesn't store your local Story Mode data on our servers.

First, because this would need user-agreement, and second because we don't have the infrastructure to handle this properly. This would require to store much more data per player than we do right now.

I'm not very interested in building a "cloud sync" for STK, it feels niche and a potential source of issues (what if some bug with the cloud sync overwrite/corrupt a player's profile ? This would have to be done very carefully).

If you want to keep your user profile on another computer, copying the players.xml from the first installation to the second one will work.
