### ISSUE TITLE
Improvements for "follow the leader" mode

### ISSUE THREAD

**Issue by Anard** [supertuxkart/stk-code#4166]
Hi.
I like "follow the leader" mode 'cause it add some hazard in races...
But it would need some improvements :

- About gamplay, I find that it lacks indications on the next elimination. It'd be interesting to see a 5 sec. count-down before the elimination of a player.
- Also, when we are the last player, a red halo could indicate us we have to speed up...
- In online mode, why isn't this mode available ? It could be interesting, even more since robots are available in servers...

**Comment by kimden** [comment]
I'd also suggest showing the position with respect to last player (e.g. "you are 5th worst riding driver as of now"). When there are many players, it's hard to tell which position is last and how much time it's left until one is eliminated in his current position.

**Comment by Alayan-stk-2** [comment]
>     * About gamplay, I find that it lacks indications on the next elimination. It'd be interesting to see a 5 sec. count-down before the elimination of a player.

The timer is showing how much time is left until the next elimination in FTL.

**Comment by Wuzzy2** [comment]
But the timer could be made more visible in FTL, however. The fact that the player did not realize the timer exists speaks volumes. So this is evidence there is an usability problem.

For the timer, I suggest (for FTL only):
Make it bigger and move it to about the center, like in many old-school arcade racers.
Make it red and flashing when time is running out and you're in last place.

> Also, when we are the last player, a red halo could indicate us we have to speed up...

I like this idea a lot! This gives the poor player a sense of urgency. This should also happen when you have accidentally overtaken the leader as it can kill you as well.

> In online mode, why isn't this mode available ? It could be interesting, even more since robots are available in servers...

Because of balancing reasons, I guess. FTL as a game mode is not much loved (notice that it does not appear in Story Mode) as when you have bad luck and the leader crashes (or even worse: resets), it's easy to get eliminated for bullshit reasons. If the leader crashes, many karts will form a cluster, driving back and forth, trying to avoid being first OR last. It's pretty hilarious.

I have suggested to remove the leader from FTL and turn FTL into a knockout race instead.
https://forum.freegamedev.net/viewtopic.php?f=17&t=8179
(and I invite you to talk to me in the forums as well)

> I'd also suggest showing the position with respect to last player (e.g. "you are 5th worst riding driver as of now"). When there are many players, it's hard to tell which position is last and how much time it's left until one is eliminated in his current position.

I agree that it would be useful to have the information. The number of total karts still in the game is critically important in FTL, so it's critical to make this information more visible, and more *directly* visible.

With any UI-related suggestions it's IMO very important to be specific about what you want. That having said, I think the particular sentence you suggest is not a good idea. A full sentence is too long, remember its a racing game so you don't have time to read. Brevity is key.

Maybe the rank display number in the bottom right could display the max rank as well. So instead of a number like “4” for “rank 4”, show “4/12” for “rank 4 out of 12 karts in the game”. Color-coding the rank could also help (e.g. red when last, orange when in last 75%, yellow when in last 50%).
Maybe the max. rank could also be displayed in other game modes as well, not sure.

**Comment by Wuzzy2** [comment]
I suggest to also play some disturbing alert noises when you're in last place and <10s are left on the clock.

**Comment by Anard** [comment]
OK for the timer, but as said Wuzzy, it's not very visible. I think a simple red blink on the 5 or 10 sec could be sufficient to note this countdown timer on the screen for new players ;)
Also, the number of current players on track could effectively be a important information to see. As said Wuzzy, with color coding, it should be the best way.

I agree that if leader crashes, the result can be very imprevisible. But it's why FTL is better for me than races. It's not always the faster who wins. When leader crashes, it's the equivalent to the entry of safety car in real races. It's like a second start as all racers are tightened.

Also, you suggested to ban tracks with short branches on freegamedev but I don't agree :
- first personnally, I always play with the maximum of AI karts (19). When you are last, or if there is a little distance between you and the next AI, you can't know what way did they take (except by looking to the map, but it's difficult to read the map while racing...)
- also, these short ways could help you to join last runners if you was shot by a bowling ball for example. Here too, there is a part of luck (or nice estimate) as you still have to stay behind the leader.

**Comment by Alayan-stk-2** [comment]
I have no intention to make this mode work online or to have a special indicator to tell a player he is last.

FTL is likely going to be replaced entirely for 2.0, so I'm not going to sink resources into it.

But the patch closing this issue adds color to the time indicator and sound when an elimination is about to happen, so people who want to play this mode can enjoy it better in 1.5.

**Comment by Anard** [comment]
OK I understand.
> FTL is likely going to be replaced entirely for 2.0, so I'm not going to sink resources into it.
It will be replaced ? By what ? I loved this mode ... :(
