### ISSUE TITLE
How does it prevent cheating?

### ISSUE THREAD

**Issue by srpatel19590** [supertuxkart/stk-code#4321]
## Description
While playing this game with global networking option, I realise that the other remoter participants can modify the source code to cheat the game and win all the time. Is it already taken care? If so, How does it function?

## Steps to reproduce
I know it is hard to cheat via changing source. However It can be possible.

**Comment by luffah** [comment]
Example ?

(On network the kart position on server is the reference; same for items.)
I don't see how you can cheat if you don't own yourself the server.
(If it is your own server you add code or config that advantage you, but it will be seen by other participants because there will be some constant laggy effects due to difference of behaviour.)

You can add helpers, or make a really sophisticated IA that sends controls to the game. But this is more aimbot that real cheat.

Another thing that you can think is cheating (but not), is using bugs and shortcuts in a map.
