### ISSUE TITLE
Have an option to disable turbo items in Time Trial

### ISSUE THREAD

**Issue by anonymous7002** [supertuxkart/stk-code#4370]
## Description

In Time Trials, we get as many turbo items as there are laps. It would be good to have an option to disable these items for example, for fair fastest laps.

## Configuration

STK release version: 1.1

STK Source (PPA, distribution package, official binary, etc.): official binary

System: Windows 10 64-bit

Graphics card: Intel HD Graphics 4600

CPU: Intel Core i5-4570S

**Comment by Benau** [comment]
I think they are part of track design or alayan!![](https://cdn.lihkg.com/assets/faces/pig/whip_special.gif)

**Comment by Benau** [comment]
Btw 1.2 stk is released https://github.com/supertuxkart/stk-code/releases/tag/1.2 ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif)

**Comment by Fouks0** [comment]
If everyone can use them then in Time Trials then it is fair...
You can choose to not use them if you want...

**Comment by Alayan-stk-2** [comment]
The only rationale provided for this idea is that without zippers, it's impossible to concentrate turbo boosts in one lap to get a better fastest lap that someone using only one. But the fastest lap achieved doesn't matter much. If people are racing, then finishing 1st is much more important. If people are trying to do the best possible time with only one kart on the road, getting the better overall time matters more and if a "best possible lap" competition is chosen, then everybody gets the same tools.

The zippers also make time-trial more interesting, because using them at the best possible moment make trajectory optimization more complex and handling well the very high resulting top speed can be difficult.

The use case of disabling the zippers in time-trial is a niche of a niche, not worth complicating the code with another option.

**Comment by anonymous7002** [comment]
I mean allowing to disable it for all players, including CPUs.

**Comment by Alayan-stk-2** [comment]
Opening a new issue that's the exact same one as the one that was closed is not acceptable.
