### ISSUE TITLE
MangoHUD Does not work anymore with the new STK version 1.2, was working fine with 1.1

### ISSUE THREAD

**Issue by baby-sheep** [supertuxkart/stk-code#4391]
## Description
SuperTuxKart version 1.2 no longer works with MangoHud.
However, if you use version 1.1, mangohud works.

Steps to reproduce:
Compile mangohud from https://github.com/flightlessmango/MangoHud
Run mangohud by typing in terminal:
mangohud supertuxkart
OR
mangohud /path/to/app (here /path/to/app is the executable)

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Snap package (v1.2)

System: Asus vivobook 15 laptop, 4GB DDR4-2666 RAM, 256GB NVME storage, 1920x1080 display
Graphics card: Intel UHD Graphics 10th gen

CPU: Intel Core i3 10110U 2 core 4 thread 2.1ghz (4.2 Ghz turbo)

**Comment by Benau** [comment]
try MANGOHUD_DLSYM=1?

**Comment by oyvindsaether** [comment]
I can confirm that with current git I have no HUD with:

mangohud supertuxkart

and I do get the MangoHUD with:

MANGOHUD_DLSYM=1 mangohud supertuxkart 

So that solution works. Perhaps SuperTuxKart could make MANGOHUD_DLSYM=1 some magic default for users who want to use mangohud so "mangohud supertuxkart" would work?

Somewhat related, setting GALLIUM_HUD= works as it always has, no need for anything special there.

**Comment by Benau** [comment]
Maybe sdl2 does something different with gl loading or ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) !

**Comment by baby-sheep** [comment]
Issue closed as it seems the rabbit hole goes deeper, if you build STK from source or download the binaries and run it from the directory, MangoHud works(assuming you use mangohud --dlsym). HOWEVER, the snap packages do not allow for this to happen. I'll open another issue for the snap.
