### ISSUE TITLE
cup points don't reflect ties

### ISSUE THREAD

**Issue by Flexmaen** [supertuxkart/stk-code#4571]
## Description
If two (or more) players pass the finish line at the same time, the won't get the same points for the cup.

## Steps to reproduce
1. Start a cup
2. Have at least 2 players finishing the track with exact the same time. (ok, that's difficult to reproduce ;))

## Configuration
Super Tux Karts 1.2 (on various systems).

## Expected Behaviour
If more players have the same time, they should get the same points. Next position(s) should be skipped then.

##Screeshots
![supertux_gleichzeitig_01](https://user-images.githubusercontent.com/6330276/128421755-528f9c04-6fee-4bc4-b6e9-8742a91c31b2.png)
![supertux_gleichzeitig_02](https://user-images.githubusercontent.com/6330276/128421788-c7270a11-8dda-4243-8680-8fae16c35a77.png)
Note: Since the ranking was skipped quickly I have the screenshot from the moment before, during the text animation. Martinland should get 4 points instead of 2.

**Comment by Benau** [comment]
to fix the gp bug may too easy to break something, stk-code doesn't have the concept of same position (ties)

**Comment by Flexmaen** [comment]
I can understand that this might be tricky, otherwise I wonder if this still can be so much rocket science nowadays when even Summer Games on the C64 had the concept of ties.

**Comment by anonymous7002** [comment]
The game could show the exact times down to the point where the last decimal is different, e.g. 3:15.3001 and 3:15.3003

**Comment by Flexmaen** [comment]
Can they be equal?

**Comment by Alayan-stk-2** [comment]
I see where you're coming from, but ties are not really meaningful in STK.

A tie is the reflection of either a truly exact performance or of a limitation of the measurement systems that allow to say who was first.

Even if both karts finish in the same frame (which is rare but happens), the game uses position interpolation and can determine the finish line crossing time on a sub-frame level. I think the time displayed on the top-left doesn't match that of the end race screen because of this (which needs fixing). Even in the case of an apparent tie down to the millisecond, one kart will have a faster time internally than the other. Of course, when things are so close, there is luck on who is actually first, but that's not a real fairness issue. In sports

Furthermore, to have ties in the end-race screen and in the GP point handling would require additional code and logic complexity.

Therefore, I'm closing this suggestion. I don't think it would be beneficial.
