### ISSUE TITLE
Shadow renders above kart if track is above

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4608]
If a kart drives below a track, the kart's shadow can be seen on the upper track as well.

How to reproduce:

* Play on the Alien Signal map
* Go to the top level (dish)
* Wait for karts to drive on the bottom layer (below the dish) and watch for shadows to appear on your layer

Tested in 7aeb0b0edf741be04f4561fe01081863a3cb0939 on GNU/Linux.

**Comment by Alayan-stk-2** [comment]
Kart hardly drive on the bottom part. This arena is rather terrible for FFA. So, I can't reproduce your issue because I can't get enough kart driving below to properly observe, but it might well be happening.

**Comment by Benau** [comment]
I cannot reproduce too and I don't think this issue is valid in the first place, kart shadow is determined by 4 wheel ray cast and if it can be casted upwards then there should be more visible bugs that a simple kart shadow

maybe it's an illusion for you due to the transparent ground and overlapping

**Comment by Wuzzy2** [comment]
OK, after a few repeated tests in splitscreen, I was also no longer able to reproduce it. Maybe what I've seen was something else, idk.
It's OK.
