### ISSUE TITLE
Requirements of SuperTux is invisible when the difficulty is locked

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#4900]
Although this sounds OK, it makes speedrunners inconvenient to complete best_while_slower so that they need to get the requirements from other sources.

**Comment by Alayan-stk-2** [comment]
This is supposed to be a little bit of a secret, to allow experimented players to get SuperTux without having to complete the full story mode. The UI Changes to display that is has been achieved are acceptable, because it is only shown once you have done it.

For 2.X, I'm thinking the platinum cup could be directly awarded when achieving best_while_slower, and there could be a small star next to the cup on the minimap to symbolize this.

But displaying the SuperTux times beforehand, I don't like this idea. I think the value of having this as a small secret outweighs the convenience it could offer a couple players. When actually speedrunning, you're not going to look around in the UI to find the time anyway, you don't want to waste time like it, so it's probably even not that useful for this. The confirmation at the end of the race that the condition has been met is by far the most important.
