### ISSUE TITLE
Keyboard arrows don't navigate in the ingame pause menu

### ISSUE THREAD

**Issue by kimden** [supertuxkart/stk-code#5085]
## Description
Usually when you use keyboard arrows (or other keys assigned for that purpose), each (or most) of them moves the selection to another GUI item, and do it consistently. Now in some menus some keys do nothing.

Considering the way to reproduce below, I found that commit af1238d688e is the first with this bug. But there can be other ways it can be broken (and probably different causing commits too), I had my doubts even about other ways in the same menu, and I don't know how to check all possible key presses in all menus.

## Steps to reproduce
1. Start the local game (seemingly doesn't matter which, let's say, on any track against 19 bots)
2. After the start click Pause to invoke the menu, press Up or Down a few times until you select the Exit game red button (the leftmost in the second row; sometimes it took me more than one press thus I thought it might be also broken)
3. Try to press Left and Right arrows, usually they select the elements of second row in a cycle, but when the bug happens, they do nothing. Strangely, it happens only for the first few seconds after step 2  (or the first few presses? Not sure)

## Configuration

STK release version: latest git 37e024f1e134a70

STK Source (PPA, distribution package, official binary, etc.): github

Gamepads/keyboards models if related to the issue: I tried at least three different ones, and they all failed.

**Comment by Alayan-stk-2** [comment]
To navigate with keyboard, the game has some logic behind the scene to determine what elements should be counted as "right", "down", etc. from another. In some situations, there is no such element.

If I go from "Back to race" to the other options with the down, up or even left key, it works fine. If I press the right key, it doesn't do anything the first time, and upon the second press it goes to the "Exit race" button. Left/right navigation is then broken. Using up or down fixes things.

I think the bug is caused by a mismatch between what's actually selected and where the game thinks the selection is located, leading to left/right inputs not returning any valid options to move to.

@kimden I think my description of the issue corresponds exactly to what you have encountered?

**Comment by kimden** [comment]
Yes, it does correspond exactly, except when the focus is on "Back to race", up/down keys also can take two presses to move to something else.

Currently only happens now if the right arrow is pressed at "Back to race", unlike what I initially described (where pressing something else also resulted in that)
