### ISSUE TITLE
Soccer+battle addons are not shown in 'Add-Ons' tab but shown in 'All'

### ISSUE THREAD

**Issue by kimden** [supertuxkart/stk-code#5086]
## Description

Maps supporting soccer and FFA downloaded from addons store that have "Add-Ons" only as category, do not appear in Add-Ons tab while in singleplayer soccer mode. They are displayed properly in All tab, and while selecting the map in any of singleplayer battle modes, and while selecting the map in online battle or soccer.

## Steps to reproduce
Open local singleplayer map selection menu, search for example for Bizarre Darkness or Emerald Arena or Ottoscuro in Add-Ons tab and in All tab.

## Configuration

STK release version: latest git 37e024f1e134a7054

STK Source (PPA, distribution package, official binary, etc.): github

Log doesn't say anything related.

**Comment by Alayan-stk-2** [comment]
@kimden The issue was down to the "All" tab going through all installed "tracks" and then checking for soccer/arena status, while other groups are checking if a track is within a predefined list, such as the "standard" group of arenas, the "standard" group of racing tracks, and a specific track could only be present in the groups of one category (battle arena, soccer arena or racing track).

A map is now allowed to be both in "soccer arena" and in "battle arena" groups. I think it all works correctly but additional testing is welcome.

**Comment by kimden** [comment]
@Alayan-stk-2 Seems like now the maps which have both FFA and soccer enabled are shown twice in network selection, while selecting one instance selects another too:

![Screenshot from 2024-09-02 09-58-27](https://github.com/user-attachments/assets/467859a9-b539-4827-a863-993f364c868b)

I think I encountered no other issues during this time.

**Comment by Alayan-stk-2** [comment]
> Seems like now the maps which have both FFA and soccer enabled are shown twice in network selection

I can't reproduce this.

**Comment by kimden** [comment]
That probably was fixed in 3c3fbb8.

**Comment by Alayan-stk-2** [comment]
Ah, yes that must be it. One less issue to worry about.
