### ISSUE TITLE
Random choice of kart / track doesn't seem to be uniformly random

### ISSUE THREAD

**Issue by joyofdata** [supertuxkart/stk-code#5098]
I'm usually too lazy to choose a kart or track so I always use the random option. But I noticed that certain karts and tracks are rarely if ever chosen. It's very obvious if you use that feature regularly.

**Comment by Alayan-stk-2** [comment]
I think that's just down to naive expectations of randomness not matching what real randomness looks like. Real randomness can have long stretches of some option being picked more than another even if on paper they have the same probability.

Here are the results of picking 6 times 243 karts with a set of 19 possible karts and looking at how many times each of the karts was picked in each series of 243.

There is some noise because, while based on 1458 kart picks, the number of data points is 114 (6*19). But despite that, and despite the disturbance from the data points not being all independent from each other, it follows quite closely what you'd expect from true randomness.

![Random_kart_pick](https://github.com/supertuxkart/stk-code/assets/25536748/e031d5a1-dfcf-41f4-8577-e4b17e6e45cd)

**Comment by joyofdata** [comment]
sorry, but this is not just nonsense it is downright embarrassing ... what you computed is a binomial distribution reflecting the sum of items evenly chosen from a set of N.

**Comment by qwertychouskie** [comment]
> I think that's just down to naive expectations of randomness not matching what real randomness looks like. Real randomness can have long stretches of some option being picked more than another even if on paper they have the same probability.
> 
> Here are the results of picking 6 times 243 karts with a set of 19 possible karts and looking at how many times each of the karts was picked in each series of 243.
> 
> There is some noise because, while based on 1458 kart picks, the number of data points is 114 (6*19). But despite that, and despite the disturbance from the data points not being all independent from each other, it follows quite closely what you'd expect from true randomness.
> 
> ![Random_kart_pick](https://private-user-images.githubusercontent.com/25536748/346111241-e031d5a1-dfcf-41f4-8577-e4b17e6e45cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDMwMzcsIm5iZiI6MTcyMDIwMjczNywicGF0aCI6Ii8yNTUzNjc0OC8zNDYxMTEyNDEtZTAzMWQ1YTEtZGZjZi00MWY0LTg1NzctZTRiMTdlNmU0NWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE4MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYmQwYjI2YTczODEzYjU2OTA2YTc1ZTRlY2IwMDgzNGViODcyODcwZjZmMTZmNDJkZmY1Zjg1ZDNjMGY1NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V_wbvRB__lJs3TeLfunOjc8tBo7OA61kD5XwygwEP7s)

I think the issue is that players are expecting "shuffle", while they get "random".  While implementing a proper shuffle algorithm is more complex than just giving a mathematical random, in this case it's going to be the only way to provide a proper user experience.  (iTunes learned this lesson like 20 years ago, it's practically became a case study at this point.)

IMHO this issue should be reopened (or a new one opened, either way is fine).

**Comment by Alayan-stk-2** [comment]
@qwertychouskie Having weighted pseudo-randomness is quite different from the randomness being used being deeply off. The user experience from biasing odds to reduce repetitions can be argued for, but you need to keep track of state in some way, which mean increased complication in the code. I'm not sold on it here, especially if the option advertises itself as random. Random kart and random track usage feels also rather marginal to me and in most situations easily corrected by manually picking what you think wasn't picked enough, and the UX listening to tunes is also quite different. I'd rather have an additional shuffle option than completely replace the random option.

While you are around, could you have a look at making a "display" options icon for the "cartoon" theme?
