### ISSUE TITLE
Remove time penalty when I drive alone

### ISSUE THREAD

**Issue by NormanTUD** [supertuxkart/stk-code#5219]
Hi, I love the game. Its really fun. 

Sometimes I just drive around, discovering the world. For these cases, I disable other players, ie. I set the number of total cars in the track to 1. But when I start early, it still gives me a Time Punishment (Zeitstrafe in German, not sure if correctly translated), even when there are no other players. 

Would it be possible to change that? If there's only one kart in total, let me start directly. 

I think this would improve playability for people like me who don't really care about racing so much, but more exploring the areas.

**Comment by Alayan-stk-2** [comment]
The time penalty is not very neat in the way it is displayed compared to how some other games do it, it could likely benefit from some changes in future versions.

But regarding this specific suggestion, while I sympathize with the annoyance of getting a penalty in casual track exploration:
- Introducing special-case code for this scenario is not very complicated, but it's still additional complexity for a very niche scenario.
- If you are not trying to get the start bonus, it's extremely easy to get the timing right to not get the penalty, as long as you remember to not mash keys randomly before the start.
- This would also affect some Story Mode challenges, where the penalty should be kept, unless adding more special code.
- An inconsistent behavior would inevitably confuse some players in the future, who will then ask if there is a bug because sometimes they don't get the penalty. Consistency and predictability in game mechanics are important.

Other issues I see with the current system are the penalty being applied for having pressed even before the countdown started, and perhaps to some degree too that the penalty is applied for even a very brief press instead of punishing a long continuous press that starts too early. However changes addressing those would affect 1.5's compatibility.
