### ISSUE TITLE
Allow to sort lists with keyboard

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#740]
**Author: kroartem**

Stk r[11445]
If you want to sort addons in addons menu, you need to use mouse. Probably its behaviour is a bit different with joysticks.
Setting this to minor.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/684

**Comment by nado** [comment]
If by sorting you meant filtering, I believe this is achieved now, may this be closed ?

**Comment by auriamg** [comment]
No, "sorting" means "sorting" :) this is still only possible with the mouse, by clicking on a column name. Remains also fairly unimportant

**Comment by Alayan-stk-2** [comment]
A potential solution would be to have the header selectable in the key order navigation. Thus, if you access to the list from the top, instead of selecting the first item of the list, it would select the first column. You could navigate left/right, and on pressing the "ok" button it would trigger the sorting sequence.

Thoughts ?

**Comment by auriamg** [comment]
@Alayan-stk-2 Sounds good
