### ISSUE TITLE
Norwegian 'Ø' in headline font doesn't have right gradient

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#89]
**Author: hikerstk**

See description. My fault, and I will fix it some day. ;)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/33

**Comment by Arthur-D** [comment]
It's almost fine actually but you can still see some difference, not sure if any time is worth spending on fixing it.
![menu_norwegian_letter_gradient](https://cloud.githubusercontent.com/assets/5515261/10353872/bfe91736-6d5a-11e5-9090-b4adfb792d57.jpg)

**Comment by Flakebi** [comment]
The coloring of the title font letters (e.g. the Ø) is done in `data/fonts/title_font_2.png`: ![data/fonts/title_font_2.png](https://raw.githubusercontent.com/supertuxkart/stk-code/master/data/fonts/title_font_2.png)

The colors of fallback characters is set here: https://github.com/supertuxkart/stk-code/blob/master/src/guiengine/scalable_font.cpp#L672

To fix the Ø, someone should edit the `.png` file. Probably that will be fixed by using freetype too (and not using hardcoded images anymore).

**Comment by auriamg** [comment]
Since we will probably soon switch to TTF font rendering, this issue will probably become obsolete so no need to invest a lot of work on that right now

**Comment by Benau** [comment]
Should be better
![](https://cloud.githubusercontent.com/assets/3252341/10421845/46fb3b88-70e3-11e5-8893-e2bf335e74c1.png)

**Comment by auriamg** [comment]
Should be fixed now that the freetype branch has been merged
