### ISSUE TITLE
Provide 64-bit Windows Binary

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#900]
**Author: stephenjust**

I have been hesitant to report this because it's more work for no apparent gain... until now?

I just installed the official 0.8 windows package, and it's absolutely unplayable. I reverted back to 0.7.3, and same problem. I suspect my 64-bit graphics driver has a buggy 32-bit implementation. I am using a "Mobile Intel 4 Series Express" type graphics card. I can't upgrade to Intel's latest driver if there is a newer one because stock drivers break my laptop's switchable graphics feature.

On the other hand, my 64-bit windows build of STK works almost flawlessly. It's very smooth, even with the integrated graphics. (Running in Linux is smoother still, but I've got bleeding-edge drivers there.)

I've attached some comparisons of the output between the 32-bit 0.8 build, and the debug SVN build that I've got in 64-bits.

The VS10 project is already set up for building 64-bit binary, and I have a compiled set of 64-bit dependencies. The only problem is that I have a student license for Visual Studio, so technically you can't use any binaries it made commercially, which is in violation of GPL.

I also have a huge set of changes to fix almost every compiler warning that appeared when compiling in 64-bits (size_t = 64 bits, but int is still 32-bits? Odd design choice.)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/844 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/844 )

**Comment by deveee** [comment]
It's already possible to compile 64-bit binaries using mingw. Dependencies are available here:
https://github.com/supertuxkart/dependencies/tree/master/windows-mingw_64bit

**Comment by hiker** [comment]
64-bit is provided, though we should have a standard installer for it.

**Comment by ranyyy** [comment]
Are there any unofficial x64 installers?

**Comment by Benau** [comment]
Anyone can try? (only work with advanced_recording branch, as such modification is done only to that branch) 

https://github.com/supertuxkart/dependencies/tree/adv_recording_64/windows_64bit/dependencies

**Comment by deveee** [comment]
I didn't try to compile it yet, just looked at "ldd" output under cygwin.

The freetype library has a bit strange dependency:
```
api-ms-win-core-synch-l1-2-0.DLL => /cygdrive/c/Windows/system32/api-ms-win-core-synch-l1-2-0.DLL (0x7fef6c00000)
```

And also ogg/vorbis libraries depend on MSVCR100.dll.

Though I can't really check our 32-bit dependencies, because it gives me: ```??? => ??? (0x6b400000)``` :(

All other libraries depend on msvcrt.dll, so I assume that it should be the same for ogg/vorbis. Or in worst case we should depend on VS2015, because we don't want to install two different VS runtimes.

Also you may want to use ```strip -s``` on .dll files to make it smaller. Or if you prefer to keep some basic symbols in dll, I'm fine with it.

**Comment by hiker** [comment]
I still see many many warnings, which needs to be taken care of. One issue is size_t vs int. In most cases we can just cast the result of a std::vector...size() to (unsigned), I don't think this should be a problem. But in some cases we assign size_t types to opengl related variables, e.g.:
1>C:\supertuxkart\master\src\graphics/command_buffer.hpp(93): warning C4267: '=': conversion from 'size_t' to 'GLuint', possible loss of data.
So probably some types in GLMesh should be changed from size_t to int(??)
While the 64-bit version runs fine, someone should take a look at those warnings. 

In general I would suggest to prefer 32 bit int over 64 bits.

I've started to commit some fixes to the win-64bit branch (in hindsight a bad name, since also linux warnings should be fixed ;) ).

**Comment by SuicSoft** [comment]
@stephenjust why would you play on integrated graphics if you have discrete :P

**Comment by deveee** [comment]
Here is a first bug report related to the msvcr100.dll:
https://forum.freegamedev.net/viewtopic.php?f=17&t=7408&start=50#p74127
```while writing this i finished building the project after switching VISUAL STUDIO 15 2017 for VISUAL STUDIO 15 2017 winx64 in CMAKE for the first time succesfully.
But when i try to open the game I get an error that says: " MSVCR100.dll is missing "```

I don't think that we want to include both vs2015 and vs2010 redistributable packages. Ideally it should just depend on msvcrt.dll to avoid recompilation for every newer VS version. But I have no idea if it's possible with VS, I can build the lib using mingw if you want.

Just note that it seems that in 32-bit libogg, the MSVCxxx.dll is statically linked. It directly depends only on kernel32.dll.

**Comment by hiker** [comment]
Hi @deveee 
don't have much time - so could you create a mingw version if it's not too much work? I don't have a windows build environment set up, so if you can do it with mingw it sounds like the easiest solution.

Thanks!
   Joerg

**Comment by deveee** [comment]
I successfully compiled ogg/vorbis and generated the lib files:
https://github.com/supertuxkart/dependencies/commit/5b6dbc1c2fff0f551f63f48327e86bb3e1b68144

@Benau can you recompile the openglrecorder? Because now libvorbis uses different file names.

And pthreadVC2 still depends on msvcr100.dll, so it must be solved too... Maybe just use std::thread? :-P

**Comment by Benau** [comment]
pthreadVC2 and ogr are both re-built

**Comment by deveee** [comment]
Ok, merged. Thanks a lot!

**Comment by Benau** [comment]
fyi hiker 64bit branch is merged

**Comment by Benau** [comment]
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3-rc1/supertuxkart-0.9.3-rc1-win64.exe/download

**Comment by hiker** [comment]
Seems to work fine, so am closing this ticket now.
