### ISSUE TITLE
When you deviate of the road by a mistake, you should to know about it

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#951]
**Author: deveee**

So, you run forward. But for example you did a little shortcuts. Or by a mistake, you run off the road by few seconds. Then you run to the end of lap and you discover that you have still the same number of laps. "Oh nooo, why? Ah, I was off the road for a moment one or two minutes ago...". 

I think, if you have not counted checkpoint, you should to get information about it. For example by displayed text, something like "turn back".

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/895

**Comment by auriamg** [comment]
@Alayan-stk-2 Agreed we could, though is there a specific track where this happened? Usually, we try to place checklines in such a way that it's essentially impossible to miss one while playing normally - actually a "Missed checkline" message would be confusing to most players since they don't even know we use checklines internally. So, unless we find a specific track where this is problematic, I'd actually tend to close this as not being a problem since I don't think I've ever heard a single bug report or complaint about this

**Comment by Alayan-stk-2** [comment]
It can happen on several tracks with some bad luck, if a collision send you flying over the checkline : https://www.youtube.com/watch?v=3weXisF_5rg

**Comment by hiker** [comment]
The proper solution is to fix the physics, not to expose the internal checkline handling. As a compromise: It should be reasonable easy to make the checkline accept karts being higher above them than we already do (4 m). We could add a height parameter to the scene.xml file to manually make them taller.

We also have a command line flag that shows the checklines.

**Comment by Alayan-stk-2** [comment]
Laps that aren't counted because of missed checklines can be a severe issue, but when such instances happen, the fix should be either in the track design or in improving the checkline code (e.g. allowing for more height), so that it remains transparent to the end users.
